### ISSUE TITLE
ibm_db 2.7.0 installs and works fine but 2.7.1 gets compile errors

### ISSUE THREAD

**Issue by amcintyre99** [ibmdb/node-ibm_db#729] opened 2021-01-02 15:18 UTC
I'm running Ubuntu 18.04 with kernel 5.4.0-58-generic and node 12.20.0

ibm_db 2.7.0 install and test worked fine
https://gist.github.com/amcintyre99/55ae2cf6d7d00ec6788a8adfa5dc1a00

ibm_db 2.7.1 gets compile errors
https://gist.github.com/amcintyre99/d52b3f3c0d409635649faf57ab0b61af

/home/andrew/.npm/_logs/2021-01-02T15_11_06_356Z-debug.log
https://gist.github.com/amcintyre99/0df060b13f9fdf6e4154f9d2c3abbb93

thanks,
Andrew

**Comment by bimalkjha** [comment] 2021-01-03 15:27
@amcintyre99 You are getting error about `SQL_DBMS_FUNCTIONLVL` macro which is defined in `sqlcli1.h` header file of clidriver driver.
```
dlndevdbctdev01: nodework/clidriver/include> grep SQL_DBMS_FUNCTIONLVL *
sqlcli1.h:#define  SQL_DBMS_FUNCTIONLVL                203
dlndevdbctdev01: nodework/clidriver/include>
```
Could you please check your sqlcli1.h file? 
If you are installing it on z/OS platform, then check this macro in the odbc header files. It may not be defined and there might be more such defines used in case statement of `odbc_connection.cpp` file. Could you please list all such defines which is used in odbc_connection.cpp but not present in header files on z/OS, so that we can update code accordingly? Thanks.

**Comment by amcintyre99** [comment] 2021-01-03 16:17
Nothing to do with z/OS, this is DB2 LUW 10.5 on x86 64.

And the sqlcli1.h file is the same one used when installing all your ibm_db releases. Only your latest 2.7.1 fails.

And I don't see SQL_DBMS_FUNCTIONLVL in my /opt/ibm/db2/V10.5/include/sqlcli1.h.

Andrew

**Comment by bimalkjha** [comment] 2021-01-03 18:42
@amcintyre99 /opt/ibm/db2/V10.5/ is the root cause. `SQL_DBMS_FUNCTIONLVL` macro was added in v11.1, so you don't see it in older db2. If you install newer client or use the default clidriver that comes with ibm_db when IBM_DB_HOME environment variable is not set before installation, it'll work. Default clidriver which comes with ibm_db is of version v11.5.4.4. Thanks.

**Comment by amcintyre99** [comment] 2021-01-03 19:23
11.1 DB2 LUW x86 64 system gets same errors trying to install 2.7.1 but 2.7.0 works. So same as 10.5.

Why would I need default clidriver when I have a local DB2 system?

Andrew

**Comment by bimalkjha** [comment] 2021-01-05 07:13
@amcintyre99 Db2 V10.5 is out of support now. The SQL_DBMS_FUNCTIONLVL was added in Db2 V11.1.1.1 version. You can download dsdriver of this version from here (https://www.ibm.com/support/pages/node/588269). Probably you installed the GA level of v11.1 so, you are hitting the error. Please check with higher version. I would suggest to install Db2 V11.5 clients. Thanks.

**Comment by amcintyre99** [comment] 2021-01-05 14:11
So because of a change you made in 2.7.1, all your customers will need to upgrade their DB2 systems or install the latest cli driver.

That's not good. And also you didn't mention it anywhere in the readme.

Andrew

**Comment by bimalkjha** [comment] 2021-01-10 16:58
@amcintyre99 I have delivered fix for this issue on github. It would be available as part of next release of ibm_db. Thanks.

**Closed by bimalkjha** 2021-01-10 16:58 UTC
