### ISSUE TITLE
ibm_db v2.7.0 "Add support for Array Insert" is loading invalid characters to the table

### ISSUE THREAD

**Issue by siva-srini** [ibmdb/node-ibm_db#660] opened 2020-06-13 00:07 UTC
### Here is the sample records (Excel sheet data) read by Angular and sends to Node.JS.  Node.JS handles the db2 inserts.

COL1 | COL2 | COL3 | COL4 | COL5 | COL6 | COL7 | COL8 | COL9 | COL10 | COL11 | COL12 | COL13 | COL14
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Group1 | Normal | E | DEV | Desc1 | 6 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group1 | Normal | E | IMP | Desc1 | 6 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group1 | Normal | E | PERF | Desc1 | 6 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group2 | Normal | E | DEV | Desc2 | 3 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group2 | Normal | E | IMP | Desc2 | 3 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group2 | Normal | E | INFR | Desc2 | 3 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group2 | Normal | E | PERF | Desc2 | 3 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group3 | Normal | E | DEV | Desc3 | 1 | XXX | 3 | 3 | NO | - | LDAP | initial | 29
Group3 | Normal | E | IMP | Desc3 | 1 | XXX | 3 | 3 | NO | - | LDAP | initial | 29

### Here is the code that handles the insertion.

```
dbService.insertArray = (sql, params, records) => {
  return new Promise((resolve, reject) => {
    const queryOptions = { sql, params, ArraySize: records };
    console.log(sql);
    console.log(params);
    console.log(records);
    ibmdb.open(connectionString, (err, conn) => {
      if (err) return reject("error connecting to database");
      conn.query(queryOptions, (err, result) => {
        if (err) console.log(err);
        if (err && !err.toString().includes('A character that could not be converted was replaced with a substitute character') &&
          !err.toString().includes('SQLSTATE=23505')) {
          conn.close(() => reject("error executing the statement. details : " + JSON.stringify(err)));
        } else {
          conn.close(() => resolve(result));
        }
      })
    });
  });
}
```

### Node.JS Output

**sql**
```
INSERT INTO QUAL.TABLE (COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11,COL12,COL13,COL14)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?)
```

**params**
```
[
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'Group1', 'Group1',
      'Group1', 'Group2',
      'Group2', 'Group2',
      'Group2', 'Group3',
      'Group3'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'Normal', 'Normal',
      'Normal', 'Normal',
      'Normal', 'Normal',
      'Normal', 'Normal',
      'Normal'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'E', 'E', 'E',
      'E', 'E', 'E',
      'E', 'E', 'E'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'DEV',  'IMP',
      'PERF', 'DEV',
      'IMP',  'INFR',
      'PERF', 'DEV',
      'IMP'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'Desc1', 'Desc1',
      'Desc1', 'Desc2',
      'Desc2', 'Desc2',
      'Desc2', 'Desc3',
      'Desc3'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      6, 6, 6, 3, 3,
      3, 3, 1, 1
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'XXX', 'XXX',
      'XXX', 'XXX',
      'XXX', 'XXX',
      'XXX', 'XXX',
      'XXX'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      3, 3, 3, 3, 3,
      3, 3, 3, 3
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      3, 3, 3, 3, 3,
      3, 3, 3, 3
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'NO', 'NO', 'NO',
      'NO', 'NO', 'NO',
      'NO', 'NO', 'NO'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      '-', '-', '-',
      '-', '-', '-',
      '-', '-', '-'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'LDAP', 'LDAP',
      'LDAP', 'LDAP',
      'LDAP', 'LDAP',
      'LDAP', 'LDAP',
      'LDAP'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      'Initial', 'Initial',
      'Initial', 'Initial',
      'Initial', 'Initial',
      'Initial', 'Initial',
      'Initial'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [
      29, 29, 29, 29, 29,
      29, 29, 29, 29
    ]
  }
]
```

**ArraySize**

```
9
```

### Db2 output with array insert (9 rows) at a time

```
COL2                   COL3    COL4        COL5      
'Normal'               'E'     'DEV'       'Desc1'   
'Normal'               'E'     'MP.'       'Desc1'   
'Normal'               'E'     'RFDE'      'Desc1'   
'Normal'               'E'     '.IM'       'Desc2'   
'Normal'               'E'     'INF'       'Desc2'   
'Normal'               'E'     'ERFD'      'Desc2'   
'Normal'               'E'     'V.IM'      'Desc2'   
'Normal'               'E'     '...'       'Desc3'   
'Normal'               'E'     '...'       'Desc3'   
```

However, when the same array insert is done with only one record in the data, the invalid characters are not getting inserted.  And this does not happen with same column.  it happens to col5 sometimes and based on how much data we are loading.  We tried to change the data type to "VARCHAR" with no luck.  we tried changing the column to unicode or ebcidic in the db2 side, with no luck as well.  we tried changing the column type of COL4 to CHAR, but still same results.

The table has composite primary key. COL1, COL3, COL4 and COL14 are composite primary keys.

Also, is there any way we can let the array insert to continue loading remaining records if one of it fails?  Like if there are any duplicates, we will want the insert query to complete the transaction instead of rolling it back.

**Comment by bimalkjha** [comment] 2020-06-15 14:18
@siva-srini Please confirm that the problem is the presence of dot(.) in the output of COL4. Also, share the CREATE TABLE sql for QUAL.TABLE. Can we reproduce the problem with your shared excel sheet data every time? I'll try once you share the create table sql. Thanks.

**Comment by bimalkjha** [comment] 2020-06-15 14:20
>> Also, is there any way we can let the array insert to continue loading remaining records if one of it fails?
Its the current behavior of Db2 server. If any record is invalid, load will stop and return error. Thanks.

**Comment by siva-srini** [comment] 2020-06-15 18:51
@bimalkjha its not really the presence of dot(.), instead it inserts some invalid characters.. see the latest inserted data on col4

### COL4  
```'DEV' 
'MP.' 
'RFDE'
'.IM' 
'INF' 
'ERFD'
'V.IM'
'...' 
'}..' 
```

### And, here is the DDL..

```
CREATE DATABASE SAMPDB BUFFERPOOL BP3 INDEXBP BP12 STOGROUP DB2APL CCSID EBCDIC;

CREATE TABLESPACE ARRAYLTS IN SAMPDB BUFFERPOOL BP13 CCSID UNICODE;

CREATE TABLE SAMP.LDAP 
  (COL14 INT         NOT NULL
  ,COL1  VARCHAR(60)  NOT NULL FOR SBCS DATA
  ,COL2  VARCHAR(20)  NOT NULL FOR SBCS DATA
  ,COL3  VARCHAR(5)   NOT NULL FOR SBCS DATA
  ,COL4  VARCHAR(5)   NOT NULL FOR SBCS DATA
  ,COL5  VARCHAR(350) NOT NULL FOR SBCS DATA
  ,COL6  INTEGER      NOT NULL
  ,COL7  VARCHAR(35)  NOT NULL FOR SBCS DATA
  ,COL8  INTEGER      NOT NULL
  ,COL9  INTEGER      NOT NULL
  ,COL10 VARCHAR(3)   NOT NULL FOR SBCS DATA
  ,COL11 VARCHAR(35)  NOT NULL FOR SBCS DATA
  ,COL12 VARCHAR(15)  NOT NULL FOR SBCS DATA
  ,COL13 VARCHAR(15)  NOT NULL FOR SBCS DATA
  ,CONSTRAINT LDAP_CPK PRIMARY KEY (COL14, COL1, COL3, COL4))
IN SAMPDB.ARRAYLTS;

CREATE UNIQUE INDEX SAMP.ARRAYLIX ON SAMP.LDAP 
   (COL14 ASC, COL1 ASC, COL3 ASC, COL4 ASC);
```

**Comment by siva-srini** [comment] 2020-06-22 14:49
@bimalkjha any update here?

**Comment by siva-srini** [comment] 2020-06-29 16:00
@bimalkjha any idea where its going wrong? based on your insights, we plan to wait or continue with older version as work around for larger inserts/updates.  please let us know.

**Comment by siva-srini** [comment] 2020-07-24 21:36
@bimalkjha we have deployed this code to our linux server and results are same.  could you please look into this.

**Comment by bimalkjha** [comment] 2020-07-27 21:03
@siva-srini Thanks for sharing the DDL. I think I am able to reproduce the problem. I am getting below data for COL4 after insert and select:
```
Inserted COL4 =  [ 'DEV',  'IMP', 'PERF', 'DEV', 'IMP',  'INFR', 'PERF', 'DEV', 'IMP' ]
Select returns COL4 =  [  'DEV', 'MP',  'RFDE',  '',    'INF', 'ERFD',  'V',   '',    '1']
```
Investigating further. Thanks.

**Comment by bimalkjha** [comment] 2020-07-28 06:01
@siva-srini Issue comes only when size of string data in a array in different. If all fields are of same size in an array, then there is no issue. Investigating further. Thanks.

**Comment by siva-srini** [comment] 2020-07-30 22:33
@bimalkjha sure, got it. let us know what you find out. thanks for all your help with this.

**Comment by bimalkjha** [comment] 2020-08-01 21:28
@siva-srini When size of data in array is different, you should pass `Lenght:<maxDataLength>` in the data object. It causes correct data insertion. In your test program, just define the COL4 data as below and verify.
  {
    ParamType: 'ARRAY',
    DataType: 1,
    **Length:4,**
    Data: [
      'DEV',  'IMP',
      'PERF', 'DEV',
      'IMP',  'INFR',
      'PERF', 'DEV',
      'IMP'
    ]
  },
Thanks.

**Comment by siva-srini** [comment] 2020-08-04 03:41
@bimalkjha ok, it worked after passing Length parm in the object.  However, is this needed only for VARCHAR or CHAR types? didnt pass this for Integer or Timestamp and still worked fine.

And, in real-time, do we have to pass this information for all the columns we insert the data?

**Comment by bimalkjha** [comment] 2020-08-04 05:10
@siva-srini `Length` is not required for Integer or TimeStamp datatype array as all elements of the array will have same size. If it is Integer array, all elements will be on equal size. Problem happens when array elements are of unequal sizes which happens for VARCHAR, CHAR, WCHAR, WVARCHAR, DBCHAR, etc data types. 
In your data only, if you see COL1 and COL2, all fields are of same size, so all elements of Array for COL1 and COL2 is of same size and hence they are working fine without passing the `Length` value. But, in COL4, few array elements are of 3 char and few are of 4 char, hence the problem.
I have pushed few code changes to treat the length of first array element as default value of `Length`, if `Length` is not specified explicitly in array object. Also, value of `Length` can not be less than the length of first element. But, this fix is not needed when you use `Length` explicitly in array object.
Glad to know your issue is resolved now. Hence, I am closing this git issue. Thanks.

**Closed by bimalkjha** 2020-08-04 05:10 UTC

**Comment by lucaskuperman** [comment] 2020-08-18 17:29
Hello! I faced same issue and solved it specifying Length, but now facing same issue not because of different string lengths in the data array, but when having combination of null's AND strings in it. No matter which length I specify, the result is as mentioned in this issue, hence didn't open a new one, but glad to open if you prefer. Thanks!
