### ISSUE TITLE
npm install fail as root on Redhat

### ISSUE THREAD

**Issue by Davissi** [ibmdb/node-ibm_db#565] opened 2019-08-16 09:11 UTC
Hi,

I am trying to install ibm_db on my linux machine but the installation failed when I log in as root:

> ibm_db@2.5.3 install /home/admin/codes/mi-api-hub/node_modules/ibm_db
> node installer/driverInstall.js

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/home/admin/codes/mi-api-hub/node_modules/ibm_db/installer/driverInstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm verb lifecycle ibm_db@2.5.3~install: unsafe-perm in lifecycle false
npm verb lifecycle ibm_db@2.5.3~install: PATH: /var/opt/node-v9.11.2-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/admin/codes/mi-api-hub/node_modules/ibm_db/node_modules/.bin:/home/admin/codes/mi-api-hub/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
npm verb lifecycle ibm_db@2.5.3~install: CWD: /home/admin/codes/mi-api-hub/node_modules/ibm_db
npm info lifecycle ibm_db@2.5.3~install: Failed to exec install script
npm timing action:install Completed in 123ms
npm verb unlock done using /root/.npm/_locks/staging-b71065b9917ae3cc.lock for /home/admin/codes/mi-api-hub/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 149ms
npm timing stage:runTopLevelLifecycles Completed in 6752ms
npm WARN mi-api-hub@1.0.0 No repository field.

npm verb stack Error: ibm_db@2.5.3 install: `node installer/driverInstall.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/var/opt/node-v9.11.2-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
npm verb stack     at EventEmitter.emit (events.js:180:13)
npm verb stack     at ChildProcess.<anonymous> (/var/opt/node-v9.11.2-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:180:13)
npm verb stack     at maybeClose (internal/child_process.js:936:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm verb pkgid ibm_db@2.5.3
npm verb cwd /home/admin/codes/mi-api-hub
npm verb Linux 3.10.0-862.el7.x86_64
npm verb argv "/var/opt/node-v9.11.2-linux-x64/bin/node" "/usr/bin/npm" "install" "ibm_db" "--verbose"
npm verb node v9.11.2
npm verb npm  v6.10.3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.3 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing audit submit Completed in 1570ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1570ms
npm timing audit body Completed in 1ms
npm timing npm Completed in 7540ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-16T09_24_27_480Z-debug.log

The strange thing is that the installation will be successful if I log in using another account and execute "sudo npm install ibm_db". Is there a reason why the above error is happening?

Thanks.

**Comment by bimalkjha** [comment] 2019-08-16 10:47
@Davissi The error you are facing is at the top: `Error: Cannot find module '/home/admin/codes/mi-api-hub/node_modules/ibm_db/installer/driverInstall.js'`
This file should be under `ibm_db`. Please check why this file is unable to reach. May be some permission issue.
Alternatively, you can clone `https://github.com/ibmdb/node-ibm_db` and run `npm install` under `ibm_db` directory. Thanks.

**Comment by Goochimagne** [comment] 2019-08-17 20:26
@Davissi If you execute "npm i <module> --unsafe-perm" this usually takes care of errors while installing modules as root which is not recommended. I had this issue while downloading packages inside a container and passing this flag solved the issue. Not sure if it will work for you but I suggest giving it a try.

**Comment by bimalkjha** [comment] 2019-08-26 15:23
The command `npm install --unsafe-perm ibm_db` works for me on RHEL 7.5 as root user. Without `--unsafe-perm` option, I see install issue. It looks something related to npm and root on RHEL. Nothing related with ibm_db. It can be reproducible with other npm package too. Hence, closing the issue. Thanks.

**Closed by bimalkjha** 2019-08-26 15:23 UTC
