### ISSUE TITLE
Library working locally but not when I spin up a docker container

### ISSUE THREAD

**Issue by hanMarr** [ibmdb/node-ibm_db#605] opened 2020-01-24 19:44 UTC
A colleague and I have been through all of the node-ibm_db documentation and have it up and running (successfully) in a local repo. running 'node index.js' (where index.js is the main file) locally works and makes a successful query to the given DB. The container builds using 'docker-compose build' successfuly (including the downloading/installing of the ibm_driver package. 

However, when we try to spin up the docker container (docker-compose up) we get an error:

marr-lp:nodeapp2 hmarr$ docker-compose up
Recreating nodeapp2_nodeapp2_1 ... done
Attaching to nodeapp2_nodeapp2_1
nodeapp2_1  | Debugger listening
nodeapp2_1  | For help, see: https://nodejs.org/en/docs/inspector
nodeapp2_1  | **/dist/node_modules/bindings/bindings.js:121
nodeapp2_1  |         throw e;
nodeapp2_1  |         ^
nodeapp2_1  | 
nodeapp2_1  | Error: Error loading shared library /dist/node_modules/ibm_db/build/Release/odbc_bindings.node: Exec format error**
nodeapp2_1  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
nodeapp2_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
nodeapp2_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
nodeapp2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
nodeapp2_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
nodeapp2_1  |     at require (internal/modules/cjs/helpers.js:25:18)
nodeapp2_1  |     at bindings (/dist/node_modules/bindings/bindings.js:112:48)
nodeapp2_1  |     at Object.<anonymous> (/dist/node_modules/ibm_db/lib/odbc.js:31:31)
nodeapp2_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
nodeapp2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
nodeapp2_nodeapp2_1 exited with code 1

This exact library with the exact node_modules runs successfully outside of the container. The Dockerfile contains:

FROM node:10-alpine
RUN mkdir /dist
WORKDIR /dist
COPY package*.json /dist/
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install -g nodemon \
    && npm install --production \
    && npm cache clean --force \
    && apk del .gyp
COPY . /dist
USER node
CMD ["node", "index.js"]

**Comment by bimalkjha** [comment] 2020-01-25 17:13
@hanMarr Your issue looks duplicate of issue #217 . Please go through it and specially this comment: https://github.com/ibmdb/node-ibm_db/issues/217#issuecomment-274738255

Since you are using alpine linux image in docker, hence the issue. Please use amazonlinux container. We have tested ibm_db in amazonlinux and it works great! Also, make sure you satisfy the prerequisite for Docker Linux Container as mentioned in ibm_db [documentation](https://github.com/ibmdb/node-ibm_db#prerequisite). Thanks.

**Closed by bimalkjha** 2020-01-25 17:13 UTC
