### ISSUE TITLE
npm install ibm_db not working

### ISSUE THREAD

**Issue by surajdesai87** [ibmdb/node-ibm_db#156] opened 2016-08-30 05:09 UTC
Hi, I am getting following error while installing ibm_db

> node installer/driverInstall.js
> Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz...
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: connect ETIMEDOUT
>     at errnoException (net.js:905:11)
>     at Object.afterConnect [as oncomplete](net.js:896:19)
> npm ERR! weird error 8
> npm ERR! not ok code 0

**Comment by rhtpandeyIN** [comment] 2016-08-30 05:45
Can you please attach the command and full error output.

**Comment by surajdesai87** [comment] 2016-08-30 05:57
attached is the log file

[output.zip](https://github.com/ibmdb/node-ibm_db/files/444103/output.zip)

**Comment by rhtpandeyIN** [comment] 2016-08-30 06:13
Which node version and Nan version you are using?

**Comment by surajdesai87** [comment] 2016-08-30 06:17
node v0.10.36
npm 1.3.6

**Comment by rhtpandeyIN** [comment] 2016-08-30 06:34
It's working fine for me.... can you once check following link is working for you or not? ''' http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz'''

If it's not working then it can be your firewall issue, might be blocking to download from external site.

**Comment by surajdesai87** [comment] 2016-08-30 06:55
It works for me on my windows machine but failing on linux machine, other packages are getting installed only this one is failing.

**Comment by rhtpandeyIN** [comment] 2016-09-02 11:58
Hi @surajdesai87  try now, I checked with my linux machine and now it's working fine for me.

**Comment by bimalkjha** [comment] 2016-09-26 13:22
@surajdesai87 Please try installing using this command and let us know: `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` Thanks.

**Comment by gabrielmancini** [comment] 2016-09-27 18:51
why installation make this download from IBM server? why the code is not in NPM ?

**Comment by bimalkjha** [comment] 2016-09-28 11:49
@gabrielmancini about which IBM server you are taking about? Code is on github and it is under testing now. After proper testing we release the code. After next release you can see the code on NPM too. It is our normal process. I have shared the command to install form git just for testing purpose. Thanks.

**Comment by bimalkjha** [comment] 2016-10-31 21:30
@surajdesai87 Use `npm install ibm_db` now. We have released a new version of ibm_db@1.0.1 that should fix this issue. Please try and let us know. Thanks.

**Comment by vuldin** [comment] 2016-12-14 16:15
The issue seems to be a slow connection to the following location:

[http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//macos64_odbc_cli.tar.gz](http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//macos64_odbc_cli.tar.gz)

Building a project with ibm_db as a dependency works sporadically for me due to this poor connection on the server side. No other dependency runs into this same issue. This happens whether I'm installing dependencies locally or remotely on bluemix, but the problems happens most often when deploying to bluemix.

Many times the first reported error from npm is:

`ETIMEDOUT 170.225.15.112:80`

Followed by:

```
       npm ERR! Linux 3.19.0-33-generic
       npm ERR! argv "/tmp/staged/app/.heroku/node/bin/node" "/tmp/staged/app/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/staged/app/.npmrc"
       npm ERR! node v6.9.1
       npm ERR! npm  v3.10.8
       npm ERR! code ELIFECYCLE
       npm ERR! ibm_db@1.0.1 install: `node installer/driverInstall.js`
```

**Comment by vuldin** [comment] 2016-12-14 16:38
I mentioned the first error is the ETIMEDOUT message given. Here are is the full content of the first error message I get from npm when running `npm install`.

```
       > ibm_db@1.0.1 install /tmp/staged/app/node_modules/ibm_db
       > node installer/driverInstall.js
       Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz...
       events.js:160
       throw er; // Unhandled 'error' event
       ^
       Error: connect ETIMEDOUT 170.225.15.112:80
       at Object.exports._errnoException (util.js:1026:11)
       at exports._exceptionWithHostPort (util.js:1049:20)
```

**Comment by gabrielmancini** [comment] 2016-12-29 17:55
come on guys put the code on npm repository

**Comment by bimalkjha** [comment] 2016-12-30 06:41
@gabrielmancini which code? ibm_db@1.0.1 is already on npm. thanks.

**Comment by vuldin** [comment] 2016-12-30 06:56
@bimalkjha Please read my comments. Especially [this]( https://github.com/ibmdb/node-ibm_db/issues/156#issuecomment-267077339) and [this](https://github.com/ibmdb/node-ibm_db/issues/156#issuecomment-267083966).

I gave all the details that you seem to be consistently missing in those posts. As you probably know, this library downloads drivers from the following link:

http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz

The link above is the one for Linux. If you are on mac or windows then the link will be different. But the results are the same, which is the connection times out more times than it successfully downloads the drivers.

This part is important: The link usually works if you go to it directly from within your browser. But pulling node-ibm_db into an app doesn't use the browser to download this file. Instead, it handles is programmatically. There must be a timeout in the node or npm configuration that decides the link is taking too long and then it gives the error I posted in [this link](https://github.com/ibmdb/node-ibm_db/issues/156#issuecomment-267083966).

Whatever the issue is, it is consistent. I have tried building my app with this library over many times over multiple days and it doesn't work. I haven't tried lately because I decided to manually download the drivers, pull this project into my project code, and then modify this code to pull from the local copies of the driver files. This is not an acceptable long-term solution, and it isn't even a short-term solution for most people.

It's very frustrating that on one hand you continue to post responses, but on the other hand completely fail to understand what the issue is.

**Comment by bimalkjha** [comment] 2017-01-05 10:10
@vuldin . Need few more info to fix it. You see this error only when http://public.dhe.ibm.com is down and file http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz is not accessible or issue occurs frequently? Is it reproducible today also? Want to figure out issue is solely related with http://public.dhe.ibm.com or there is some programming error in installer? Thanks.

**Comment by gabrielmancini** [comment] 2017-01-06 19:07
remove that dependency, put everything on npm

**Comment by whitehorse5353** [comment] 2017-01-18 11:43
This is the third time. I am facing the same issue. @bimalkjha as everyone suggested please keep this `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz ` drivers inside npm registry itself, to avoid further firewall blocking issues.

**Comment by bimalkjha** [comment] 2017-01-18 15:25
@whitehorse5353 I am checking with IBM Product Manager about hosting of ibm proprietary library out of IBM network. Also, requested to ensure high availability of https://public.dhe.ibm.com. Thanks.

**Comment by hem1980** [comment] 2017-01-18 17:52
**I am not able to npm install ibm_db. 
node v7.4.0
npm 4.0.5
Windows 10
Getting following error:**

> ibm_db@1.0.2 install C:\Projects-sctfs\s360.test.api\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

- nan@2.3.5 node_modules\nan



events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1117:19)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN s-360-test-api@1.0.0 No repository field.
npm WARN s-360-test-api@1.0.0 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ibm_db" "--save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@1.0.2 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@1.0.2 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects-sctfs\s360.test.api\npm-debug.log

**Comment by rhtpandeyIN** [comment] 2017-01-19 08:53
Hi @hem1980 , I tried with the same node version on windows 10 and for me it is installing properly.

Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Rohit\node_modules\ibm_db>node -v
v7.4.0

C:\Rohit\node_modules\ibm_db>npm -v
4.0.5

C:\Rohit>npm install ibm_db

> ibm_db@1.0.2 install C:\Rohit\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...




Downloaded 100.00% (25824992 bytes)


****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in C:\Rohit\node_modules\ibm_db\installer   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Download and extraction of DB2 ODBC CLI Driver completed successfully...

**Comment by rhtpandeyIN** [comment] 2017-01-19 09:00
@hem1980 , I guess problem is with your system setup or might be because of the driver downloading site was down yesterday. could you please try again? and are you able to download zip file from followinf link: 
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip

**Comment by gabrielmancini** [comment] 2017-01-20 11:48
> bimalkjha commented  I am checking with IBM Product Manager about hosting of ibm proprietary library out of IBM network. Also, requested to ensure high availability of https://public.dhe.ibm.com. Thanks.

the ibm proprietary library u talk about is a client drive to connect on db2 right?

**Comment by bimalkjha** [comment] 2017-01-23 06:36
@gabrielmancini Yes. you are right. Thanks.

**Comment by gabrielmancini** [comment] 2017-01-24 17:02
why the client driver is proprietary? this still make any sense?

**Comment by bimalkjha** [comment] 2017-01-24 17:11
@gabrielmancini node-ibm_db is using the ODBC/CLI driver available on IBM site here for download by customers: http://www-01.ibm.com/support/docview.wss?uid=swg21385217
Basically node-ibm_db has less dependency to download odbc driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ . User can install IBM Client driver from http://www-01.ibm.com/support/docview.wss?uid=swg21385217 and set IBM_DB_HOME environment variable to point the install directory. If IBM_DB_HOME is set `npm install ibm_db` will not download odbc driver from https://public.dhe.ibm.com. Hope it explains. Thanks.

**Comment by vuldin** [comment] 2017-01-24 18:27
Awesome @bimalkjha this is an adequate solution if it works as you mention. I haven't tested it out yet, but I will need to take this approach in the future.

**Comment by bimalkjha** [comment] 2017-01-27 10:49
Another issue #205 is opened for similar issue. Hence, closing it. Thanks.

**Closed by bimalkjha** 2017-01-27 10:49 UTC

**Comment by Sanjotarm** [comment] 2023-05-11 10:52
Hi,

I am facing the issue while running the commands "npm install" and "node installer/driverInstall.js"

platform = win32, arch = x64, node.js version = v16.17.0

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLIProject\Angular Project\New Project\Nodeserver\node_modules\ibm_db\installer\clidriver. Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), th
en delete the relevant component(s) from your device.
****************************************

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip ...

ECONNREFUSED : https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
Downloading DB2 ODBC CLI Driver from https://github.com/ibmdb/db2drivers/raw/main/clidriver/ntx64_odbc_cli.zip ...

ECONNREFUSED : https://github.com/ibmdb/db2drivers/raw/main/clidriver/ntx64_odbc_cli.zip

=====================================
Error: Installation of ibm_db failed.

Since I am using a corporate system and unable to proceed with the issue. Can someone help on this.

**Comment by bimalkjha** [comment] 2023-05-11 10:58
@Sanjotarm Let us know you are able to download `ntx64_odbc_cli.zip` file from either of the above links or not? You can click on these links and verify it. If not, then you need to check your proxy configuration. Both links are working for us. Thanks.

**Comment by Sanjotarm** [comment] 2023-05-11 11:05
@bimalkjha Yes. I am able to download it from both the above links and I've established the IBM_DB_HOME environment variable and set the path to C:\ntx64_odbc_cli\clidriver. Despite this, I'm still encountering an issue when attempting to run the command "npm install," and the issue I'm facing is as follows:

C:\My Project\Angular Project\New Project\Nodeserver> node server.js
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified module could not be found.
\\?\C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\lib\odbc.js:57:31)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ERR_DLOPEN_FAILED'
}
PS C:\My Project\Angular Project\New Project\Nodeserver>

**Comment by bimalkjha** [comment] 2023-05-11 11:15
@Sanjotarm `cd C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db` and run `npm install`. Share the complete output of `npm install` command here. Thanks.

**Comment by Sanjotarm** [comment] 2023-05-11 11:56
Please find the below ouput of npm install

C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db>npm install
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

> ibm_db@3.2.0 install
> node installer/driverInstall.js

platform = win32, arch = x64, node.js version = v16.17.0
IBM_DB_HOME environment variable have already set to -> C:\ntx64_odbc_cli\clidriver

Downloading of clidriver skipped - build is in progress...

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  odbc.cpp
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc.cpp(216,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc.cpp(228,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc.cpp(722,73): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc.cpp(722,73): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc.cpp(723,33): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc.cpp(723,33): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc.cpp(1514,5): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  odbc_connection.cpp
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(322,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(547,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(929,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(1131,60): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(1185,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(1215,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(1378,55): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(1785,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(1968,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(2173,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(2588,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_connection.cpp(2756,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  odbc_statement.cpp
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(247,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(424,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(581,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(794,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(966,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(997,85): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(1054,85): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(1145,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_statement.cpp(1268,10): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  odbc_result.cpp
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_result.cpp(293,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_result.cpp(321,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_result.cpp(613,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_result.cpp(820,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\src\odbc_result.cpp(976,10): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  strptime.c
  win_delay_load_hook.cc
     Creating library C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\Release\odbc_bindings.lib and object C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\Release\odbc_bindings.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 579 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  odbc_bindings.vcxproj -> C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\Release\\odbc_bindings.node


Kernel additional dependencies removed successfully!


ibm_db installed successfully.
up to date in 18s
3 packages are looking for funding

After ibm_db installed successfully. I am trying to run the node server.js. Its giving me below error.

PS C:\My Project\Angular Project\New Project\Nodeserver> node server.js
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified module could not be found.
\\?\C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\lib\odbc.js:57:31)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ERR_DLOPEN_FAILED'
}
PS C:\My Project\Angular Project\New Project\Nodeserver>

**Comment by Sanjotarm** [comment] 2023-05-11 12:20
C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\Release>dir
 Volume in drive C is OSDisk
 Volume Serial Number is 74C6-F6CD

 Directory of C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\build\Release

05/11/2023  01:51 PM    <DIR>          .
05/11/2023  01:51 PM    <DIR>          ..
05/11/2023  01:51 PM    <DIR>          obj
05/11/2023  01:51 PM               866 odbc_bindings.exp
05/11/2023  01:51 PM         1,626,489 odbc_bindings.iobj
05/11/2023  01:51 PM           367,104 odbc_bindings.ipdb
05/11/2023  01:51 PM             1,940 odbc_bindings.lib
05/11/2023  01:51 PM           283,136 odbc_bindings.node
05/11/2023  01:51 PM         5,115,904 odbc_bindings.pdb
               6 File(s)      7,395,439 bytes
               3 Dir(s)  347,541,438,464 bytes free
------------------------------------------------------------------------------------------------------------------------------------

C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\test>node test-basic-test.js
Trying to open a connection ...
[Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "165.72.20.153".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001
] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -30081,
  state: '08001'
}
node:assert:124
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "165.72.20.153".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001
] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -30081,
  state: '08001'
} == null
    at C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\test\test-basic-test.js:10:10
    at C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\lib\odbc.js:142:11
    at C:\My Project\Angular Project\New Project\Nodeserver\node_modules\ibm_db\lib\odbc.js:371:18 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "165.72.20.153".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001
  ] {
    error: '[ibm_db] SQL_ERROR',
    sqlcode: -30081,
    state: '08001'
  },
  expected: null,
  operator: '=='
}

**Comment by bimalkjha** [comment] 2023-05-11 14:56
Try running `node server.js` just after `node test-basic-test.js` and check outputs. Thanks.
