### ISSUE TITLE
CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000

### ISSUE THREAD

**Issue by dhulke** [ibmdb/node-ibm_db#580] opened 2019-09-19 22:08 UTC
We were having problems with a previous version of this plugin, as described on issue #551, where we would run execureNonQuery functions and some of them would return 0 affected rows, even though we were trying to execute db2 merge statements with `when matched` and `when not matched` directives, which should never return 0 affected rows.

When we updated to version 2.6.1, we started seeing an error, which is now thrown by executeNonQuery: `CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000`.

We are currently using pool to open our connections, similar to this:
```
const pool = new require("ibm_db").Pool;
pool.open(cn, callback);
```

The code that fails works by `open()`ing a connection from the pool, beginning a transaction, and running 500 times the preparestatement and executenonquery methods and closing each statement in the right order. At the end, the code commits the transaction and calls closeSync() on the connection. We have checked and all statements are properly closed. We don't have any apparent leaks, yet, the code breaks with the above message.

Any ideas?

**Comment by dhulke** [comment] 2019-09-19 23:11
One additional information is that I always call executeNonQuery inside the prepare callback and the prepare callback doesn't return an error, just the executeNonQuery. I Tried the same code with and without Pool and they all behave exactly the same.

**Comment by bimalkjha** [comment] 2019-09-20 09:35
@dhulke execureNonQuery() requires stmt to be called. I hope you are closing the stmt object too once done. 
Invalid handle error comes due to invalid logic in the code or when some statement or connection object is not closed properly. I would request to **share small test file** which can reproduce this behavior. Then we can further investigate to find the root cause and fix. Thanks.

**Comment by dhulke** [comment] 2019-09-20 13:51
You are right. I was focusing on one specific executeNonQuery() on that transaction and forgot that I was calling 2 executeNonQuery() on that same transaction and the second operation didn't close the prepared statement. Such a simple error. It was just a matter of closing the prepared statement on that other operation and it started working again. Thank you for all the support.

**Comment by dhulke** [comment] 2019-09-20 14:11
Just out of curiosity, why would this statement leak cause the executeNonQuery() to return a simple warning (0 affected rows) instead of a memory leak error?

**Comment by bimalkjha** [comment] 2019-09-20 16:35
@dhulke When we do not close the stmt or conn object, it remains in the env. The new object in next loop uses same values as in previous loop object. After sometime, when garbage collector of javascript kicks in, it frees the older non-closed  stmt or conn object. That causes the current object invalid and hence invalid connection or handle error. 
Basically, it happens after sometime when garbage collector start its work. Thanks.

**Closed by bimalkjha** 2019-09-20 16:35 UTC

**Comment by GilbertoTADS** [comment] 2021-03-23 18:37
> @dhulke Quando não fechamos o objeto stmt ou conn, ele permanece no env. O novo objeto no próximo loop usa os mesmos valores do objeto de loop anterior. Depois de algum tempo, quando o coletor de lixo de javascript entra em ação, ele libera o objeto stmt ou conn mais antigo não fechado. Isso faz com que o objeto atual seja inválido e, portanto, uma conexão inválida ou um erro de manipulação.
> Basicamente, isso acontece depois de algum tempo quando o coletor de lixo começa a funcionar. Obrigado.

Huummnnn....achei o meu problema kkkk valeu.
