### ISSUE TITLE
fail to install ibm_db for node.js on window 7

### ISSUE THREAD

**Issue by yizhao66** [ibmdb/node-ibm_db#222] opened 2017-02-01 02:02 UTC
node installer/driverInstall.js

**Comment by rhtpandeyIN** [comment] 2017-02-01 03:44
Hi @yizhao66 , Could you please provide more information about error.
like:
node-version?
full error etc.

**Comment by yizhao66** [comment] 2017-02-03 01:41
run

>  npm install ibm_db



get error:



Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/d
rivers/odbc_cli/ntx64_odbc_cli.zip...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:op
enssl\ssl\s23_clnt.c:794:

    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)
npm WARN AcceptanceTest@1.0.0<mailto:AcceptanceTest@1.0.0> No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install" "ibm_db"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@1.0.2<mailto:ibm_db@1.0.2> install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@1.0.2<mailto:ibm_db@1.0.2> install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\CZHMG5R\Documents\Git\cspd-common-integration-code\AcceptanceTest\npm-debug.lo
g



________________________________

**Comment by rhtpandeyIN** [comment] 2017-02-03 15:10
hi @yizhao66 ,
I tried with the same node version on windows 7, I am able to install it successfully.
it seems issue with downloading clidriver package. Are you able to download clidriver package through following link:
'''
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
'''

**Comment by rhtpandeyIN** [comment] 2017-02-06 12:16
Hi @yizhao66 , any update?

**Comment by yizhao66** [comment] 2017-02-06 17:51
Yes, I have download ntx64_odbc_cli.zip from URL that you provide.  Where should I put it?  Where should I un-zip it?



thanks,



________________________________

**Comment by rhtpandeyIN** [comment] 2017-02-06 18:14
well I was just inquiring that - are you able to download zip file from mentioned link.
as now you are able to download, could you please try to install node-ibm_db again.
simply use "npm install ibm_db" command.

Feel free to contact again.

**Comment by amellnik** [comment] 2017-02-06 19:07
I'm seeing the same issue, also on Windows 7 x64:

```
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub
/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
```

I'm behind a corporate proxy.  I'm still looking through [the file](https://github.com/ibmdb/node-ibm_db/blob/master/installer/driverInstall.js) but is it possible it's not respecting the `HTTP_PROXY` environment variable when attempting to download?

**Comment by yizhao66** [comment] 2017-02-06 19:14
I have configured proxy on my machine.



I was able to install ibm_db before and run javascript on node.js without any problem.

The problem now is due to re-image my laptop.  After it, I am not able to instll ibm_db as I could not download this driver.



________________________________

**Comment by rhtpandeyIN** [comment] 2017-02-07 09:25
@yizhao66 ,
Have you configured your npm proxy after re-imaging of laptop?
Please try to config proxy settings for npm first and then try.
follow these steps:
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080

or follow below link:
https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by amellnik** [comment] 2017-02-07 18:10
@rhtpandeyIN -- I don't think this is the issue.  I have both proxy settings set in npm and hundreds of other  packages work fine across the proxy.

**Comment by amellnik** [comment] 2017-02-08 00:12
I have both the `http` and `https` proxies set, and the error is triggered by [this line](https://github.com/ibmdb/node-ibm_db/blob/master/installer/driverInstall.js#L434).  If I `console.log(options)` right before that I see 

```javascript
{ 
  host: 'my.correct.proxy.here',
  port: 'correct port here',
  path: 'https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip' 
}
```

Which is all correct.  I know this should work because I can run from a separate file:

```javascript
var http = require('http');
var fs = require('fs');
var file = fs.createWriteStream("ntx64_odbc_cli.zip");
var options = { host: 'my.correct.proxy',
  port: 'proxy port here',
  path: 'https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip' };
var request = http.get(options, function(res) {
  console.log(res);
  res.pipe(file);
});
```

which returns a 400 code response and actually downloads the file.  Perhaps there's something earlier in the install script that would trigger the socket hang up error?

**Comment by amellnik** [comment] 2017-02-08 22:20
Also I just forked, reverted to https://github.com/ibmdb/node-ibm_db/commit/f4587f05c33691f8a17a9592c90572bd5f7c3101 and built from my local copy via yarn and it's working, so it's definitely some sort of regression since then.  I'll start looking for the exact diff that broke it since I haven't been able to figure it out from just master.

**Comment by amellnik** [comment] 2017-02-09 00:06
I was missing the fairly subtle change [here](https://github.com/ibmdb/node-ibm_db/commit/d7e2d4b4cbeb6f067df8bba7d0b2ac5d40fcfc19#diff-315091eb1586966006e05ebc21cd2a94L7) where the `https` module is being required as `http`.  Apparently making `https` connections over proxies is [more complicated](https://github.com/nodejs/node-v0.x-archive/issues/2474#issuecomment-3481078) than how it's being done on master.  One fairly painless way to handle it is to use `requests` which handles [the hard stuff for you](https://github.com/request/request/blob/master/README.md#proxies).  

I was about to put together a PR, but I just realized that @gildean figured out all this more than a month ago and it's fixed in [his PR](https://github.com/ibmdb/node-ibm_db/pull/185).  Moving discussion there.

**Comment by rhtpandeyIN** [comment] 2017-02-09 07:21
Thanks a lot @amellnik for the well documented help, we are looking into the issue and testing the PR fix code. Very soon we will update the repository with working fix.
Thanks again.

**Comment by rhtpandeyIN** [comment] 2017-02-09 17:03
Hi @amellnik , @yizhao66 , I have updated the code and now we are using request module as per above discussion and suggestions. right now code is not delivered in master branch, I have updated my forked branch, and after full testing we will update the code of master branch too.

Till then could you guys please test below command in your proxy environment?
'''
npm install git+https://git@github.com/rhtpandeyIN/node-ibm_db.git
'''
your feedback would be really helpful.
Cheers!

**Comment by amellnik** [comment] 2017-02-09 17:32
Hi Rohit,

https://github.com/rhtpandeyIN/node-ibm_db/commit/293be3bf271b6337f1a2789372b9952a74dc7388 works for me, but only if I change my `HTTPS_PROXY` environment variable from `https://our-internal.proxy:port` to `http://our-internal.proxy:port`.  In general I think either should be accepted, so I think you might want to parse the proxy URL, switch it over to http if needed, then call 

```javascript
request({
    url: installerfileURL,
    proxy: 'http://our-internal.proxy:port'
}).pipe(outStream);
```

Requests does most of the configuration itself, but it's not quite smart enough to not use a https connection to a proxy when connecting to an external https url.

**Comment by rhtpandeyIN** [comment] 2017-02-10 07:57
@amellnik , 
'''
 but it's not quite smart enough to not use a https connection to a proxy when connecting to an external https url.
'''
Is it correct? I am afraid I didn't get it.
Also If it remains as it is right now, is is not proper? I mean do we really need to parse it here in module, while user can set proxy according to their need. Just asking for more insight for clarification of needs.

@yizhao66 , Is it working for you?

**Comment by gildean** [comment] 2017-02-12 17:54
@rhtpandeyIN No, that's not how it works, as you specifically set `http_proxy` __and__ `https_proxy` (which often are the same address and often only on http). No parsing is necessary as long as the proxy addresses are set correctly.

**Comment by rhtpandeyIN** [comment] 2017-02-13 06:31
@gildean , Pardon, could you please reference your comment. 

because I said above "Do we need to parse proxy here in module, while user can set proxy according to their need?"

and your comment is not clear to me, If you could reference the discussion talks it would be easier to understand.

**Comment by rhtpandeyIN** [comment] 2017-02-17 09:17
Issue has been fixed and delivered.

**Closed** 2017-02-17 10:07 UTC

**Comment by aslansservant42** [comment] 2018-11-01 15:19
for those of you who are having this same issue and do not have access to change or even know your portal settings. I have found that you can download the IBM driver from the above address and extract the files into a dirctory, say c:\drivers\ibm_c4. Then go to your Windows properties and add an environment variable IBM_DB_HOME and point it to that directory. When you run npm install ibm_db it will find the environment variable and use the files from that location rather than trying to download them from the internet.

for more info: https://github.com/ibmdb/python-ibmdb/issues/302
