### ISSUE TITLE
Write a Knex Adapter

### ISSUE THREAD

**Issue by drmikeh** [ibmdb/node-ibm_db#257] opened 2017-05-01 14:40 UTC
Are there any plans to write a Knex adapter for this project? It would be nice to use a knexfile for connecting to DB2 databases and use Knex for building DB2 SQL statements.

Knex already has support for Postgres, MSSQL, MySQL, MariaDB, SQLite3, and Oracle. See http://knexjs.org/

**Comment by mattbrunetti** [comment] 2017-05-04 21:49
Hi @drmikeh , your issue belongs with with the knex repo since that's where all the adapters reside. 

The issue is already there - tgriesser/knex#1350

**Comment by rhtpandeyIN** [comment] 2017-05-05 17:38
@drmikeh thanks for the information, we will see what we can do from our side. Closing the issue now.

**Closed by rhtpandeyIN** 2017-05-05 17:38 UTC
