### ISSUE TITLE
IBM i - setIsolationLevel(32) not working as expected

### ISSUE THREAD

**Issue by rcronin** [ibmdb/node-ibm_db#891] opened 2022-10-27 14:15 UTC
Hello,

We have implemented ibm_db against our IBM i. We have been noticing some record locking on processes using this connector. We have tried to set the isolation level to value 32 when opening the connection (no commit/auto commit). We have noticed on the IBM i job, the commitment control is still set to *CS. No matter what we do, we cannot get this working correctly.

**Code Example**
```
/* eslint-disable import/prefer-default-export */
import { Pool } from 'ibm_db';
import { BindingParameters } from '../types';

export default class DB2Connection {
  connectionString: string;
  pool: Pool;
  trace: boolean;
  connected: boolean = false;

  /**
     * Constructor for DB2Connection class; sets value for
     * connection string
     * @param connectionString - string used for connecting to DB2 tables
     */
  constructor(connectionString: string, poolSize = 1, trace = false) {
    this.connectionString = connectionString;
    this.trace = trace;

    this.pool = new Pool({ maxPoolSize: poolSize });
    this.pool.init(poolSize, this.connectionString);
  }

  /**
     * Creates and connects to an instance of a connection pool
     */
  async connect() {
    try {
      const { connection, error } = await new Promise((resolve, reject) => {
        this.pool.open(this.connectionString, (error, connection) => {
          try {
            // set isolation level to 2= CS (cursor stability), 8 = RR (repeatable read), 32 = NC (No Commit)
            //connection.setIsolationLevel(32);
          } catch (e) {
            console.error(e);
          }
          if (error) reject(error);
          this.connected = true;
          resolve({ connection, error })
        });
      });

      if (error) throw error;

      return connection;
    } catch (error) {
      throw error;
    }
  }

  /**
     * Close connection to connection pool
     */
  async close() {
    try {
      await this.pool.close(null);
      this.connected = false;
    } catch (error) {
      throw error;
    }
  }

  /**
     * Queries database with incoming query string and returns result set
     * @param queryString - SQL string used for querying database
     */
  async query(queryString: string): Promise<any> {
    let connection;
    if (this.trace) {
      console.log(queryString);
    }
    try {
      connection = await this.connect();
      const results = await connection.query(queryString);
      return results;
    }
    catch (error) {
      throw error;
    }
    finally {
      if (connection) {
        await connection.close();
      }
    }
  }

  async call(queryString: string, _parameters?: BindingParameters) {
    let connection;
    if (this.trace) {
      console.log(queryString, _parameters);
    }
    try {
      connection = await this.connect();
      const statement = connection.prepareSync(queryString);
      statement.bindSync(_parameters);
      const results = statement.executeSync();
      return results;
    } catch (error) {
      throw error;
    } finally {
      if (connection) {
        await connection.close();
      }
    }
  }
}
```

Using version 2.8.1 and 3.0.0

**Comment by bimalkjha** [comment] 2022-11-01 18:35
@rcronin Uncomment the ` //connection.setIsolationLevel(32);` code in connect() function. ` connection.setIsolationLevel(32);` should set the isolation level to NC as documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#setIsolationLevelApi)
Alternatively, you can add `TxnIsolation=32;` in connectionString. It will set Isolation Level to SQL_TXN_NOCOMMIT for the connection as documented [here](https://www.ibm.com/docs/en/db2/11.5?topic=keywords-txnisolation).
If still you find that isolation level setting is not effective, please save your test program as test.js and execute below commands from terminal(windows - Administrator command prompt):
```
cd .../ibm_db/installer/clidriver/bin
db2trc on -f 1.trc
node full/path/of/test.js
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```
zip all 1.* files and share here for investigation.
Thanks.

**Comment by rcronin** [comment] 2022-11-02 17:20
My apologies. Our code doesn't actually have the setIsolationLevel commented out. The job on the IBM i does have the commitment control set to *CS. Is that correct?

**Comment by bimalkjha** [comment] 2022-11-02 18:41
@rcronin I think the commitment control on server should be changed to NC. Thanks.

**Comment by rcronin** [comment] 2022-11-02 19:14
I set to NC programmatically and via the connection string and no change. Here is the commitment control for the job.

![image](https://user-images.githubusercontent.com/11710708/199580737-0f764335-e818-404a-b37d-3bc1d283adbf.png)

**Comment by bimalkjha** [comment] 2022-11-02 19:22
@rcronin Please collect the db2trc for the test file as mentioned in previous post. By looking on db2 traces, we can confirm that client is sending the Isolation Level instruction on server or not. Thanks.

**Comment by rcronin** [comment] 2022-11-03 13:40
[Archive.zip](https://github.com/ibmdb/node-ibm_db/files/9929655/Archive.zip)

**Comment by bimalkjha** [comment] 2022-11-04 12:12
@rcronin We need 1.fmtc file too generated using `db2trc fmt -c 1.trc 1.fmtc` command. Also, share 1.trc file too. Thanks.

**Comment by bimalkjha** [comment] 2022-11-04 12:27
Please share your test script too. Thanks.

**Comment by bimalkjha** [comment] 2022-11-04 12:40
@rcronin From the shared traces, I found that connection string used is `DSN=development;UID=user;PWD=********;QueryTimeout=10;CommandTimeout=10;LockTimeout=10;` which do not have txnisolation=32. If you use isolation level in connection string, it will be application since start.
I see call for `connection.setIsolationLevel(32);` in trace, but there is no query executed after it. The `"values current_timestamp"` query is executed by different thread for which isolation level is not set. There could be some logical issue in the test program. You can execute add code to call `setIsolationLevel` in `ibm_db\test\test-basic-test.js` file, update connection string in `ibm_db\test\config.testConnectionStrings.json` file and run test-basic-test.js to verify. Thanks.

**Comment by rcronin** [comment] 2022-11-11 16:08
@bimalkjha - Any update on this?

**Comment by bimalkjha** [comment] 2022-11-19 18:34
@rcronin Thanks for sharing the latest traces. By looking on trace files, I can confirm that Isolation Level = NO COMMIT is effective and queries are getting executed using this isolation level only.
In 1.fmt and 1.fmtc file, we can see the package name used for query execution is SYSSH000. This is the correct package for NO COMMIT isolation level.
```
1.fmt
------
54194	data DB2 UDB DRDA Communication Manager sqljcSend fnc (3.3.54.5.0.1177)
	pid 4600 tid 26872 cpid -1 node -1 probe 1177
	bytes 410

	SEND BUFFER(AR):

            EXCSQLSET RQSDSS                 (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  004ED05100010048 201400442113E2F1   .N.Q...H ..D!...  .+}...........S1
  0010  F0F4F3F1F4F34040 4040404040404040   ......@@@@@@@@@@  043143          
  0020  D5E4D3D3C9C44040 4040404040404040   ......@@@@@@@@@@  NULLID          
  0030  4040E2E8E2E2C8F0 F0F0404040404040   @@........@@@@@@    SYSSH000      
  0040  4040404001010101 010101010001       @@@@..........        ..........
.......................
	pkgnamcsn:
		rdbname    = S1043143          
		rdbcolid   = NULLID            
		pkgname    = SYSSH000          
		pkgcnstkn  = SYSLVL01
		pkgsn      = 4

```
According to the Isolation Level, the package name for query execution get selected by client. As per db2 documentation for package names: https://www.ibm.com/docs/en/db2/11.5?topic=environment-bind-files-package-names
```
The package name format is "SYSSHxyy" where 'x' denotes the isolation level.
'x' is the isolation level: 0=NC, 1=UR, 2=CS, 3=RS, 4=RR
'yy' is the package iteration 00 through FF
```
So, for your query `values current_time`, the package name sent by client is `SYSSH000`, so isolation level NOCOMMIT is effective.
If still you have doubt, then check the package name used at server side for the query. It should give correct info.
Thanks and Regards,
Bimal Jha

**Comment by bimalkjha** [comment] 2022-12-03 21:18
From traces, it looks `setIsolationLevel(32)` is working fine from ibm_db and info is getting sent to server. Hence, closing this issue. Thanks.

**Closed by bimalkjha** 2022-12-03 21:18 UTC
