### ISSUE TITLE
When I use Electron on Windows with the node-ibm_db the app crashes

### ISSUE THREAD

**Issue by kloener** [ibmdb/node-ibm_db#243] opened 2017-04-05 10:06 UTC
Hi,

I've troubles running ibm_db in electron on windows.

I created a test-repository here: https://github.com/kloener/ibm-db-electron 

Steps to the error:
1. git clone `https://github.com/kloener/ibm-db-electron `
2. call `npm install` which will **fail on windows**, because electron's `install-app-deps` (see package.json scripts `postinstall`) tries to rebuild all node-modules, but this don't work on windows out of the box. 
3. It seems that the *rebuild* scripts looks for a *build.zip*, which is not present (anymore). So I've placed it there (node_modules/ibm_db/build.zip) again from your git-repo (https://github.com/ibmdb/node-ibm_db/blob/master/build.zip)
4. call `npm install` again to complete the step
5. It should now be available within electron when I start the app with `npm start`, but it isn't. An error in the web-console tells mit something like "Error: A dynamic link library (DLL) initialization routine failed. \\?\C:\Users\........\ibm_db\build\Release\odbc_bindings.node"
6. So I've tried to rebuild node-modules by using electron-rebuild. So I called `npm install electron-rebuild`
7. And before I can use electorn-rebuild, I've to copy the *include* folder from the [Linux64 clidriver](http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz) into `node_modules/ibm_db/installer/clidriver/`
8. Then I call electron-rebuild with `IBM_DB_HOME=$(pwd)/node_modules/ibm_db/installer/clidriver node_modules/.bin/electron-rebuild --target=1.5.1 --x64` which tells me "Rebuild Complete".
9. re-start the app by calling `npm start` and the ibm_db JavaScript functions are available **BUT** I cannot call `ibm_db.open(connectionstring)`, because it fails on line 177 of the file
`node_modules/ibm_db/lib/odbc.js` when it calls `self.odbc.createConnection(function (err, conn)`.

![Screenshot](https://cloud.githubusercontent.com/assets/737537/24700743/63cdbf5a-19f8-11e7-8f7b-3737bd159124.png)

On another app the electron-app crashes. In the test-repository the app just shows a white blank page. No errors are thrown. It does not matter if the connectionString is a real server or not. 

The expected behaviour is an alert message telling me "Could not connect to locahost db2", because I've no server running.

On MacOS, it works without problems.

I hope you can reproduce it and help me.

kind regards,
Christian

**Comment by kloener** [comment] 2017-04-05 10:39
Additonally, I tried to call ibm_db.open only in the main-process of electron, instead of the renderer-process. Results in the same behaviour/error.

**Comment by rhtpandeyIN** [comment] 2017-04-05 11:15
hi @kloener ,

As I suggested earlier there is no need to build ibm_db again as it already contains pre-compiled binaries for windows. It is working in mac and linux because ibm_db can simply compiled there and generates binary code but in windows it is not that simple. 

well I tried your steps and I got following error:

$ cd ibm-db-electron/

rohit@IBM767-PC07HRFJ MINGW64 /e/electron/ibm-db-electron (master)
$ npm install

> ibm_db@2.0.0 install E:\electron\ibm-db-electron\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub                                                               /software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

11.74% | 3031040 bytes downloaded out of 25824992 bytes.

12.18% | 3145728 bytes downloaded out of 25824992 bytes.
13.74% | 3547136 bytes downloaded out of 25824992 bytes.
100.00% | 25824992 bytes downloaded out of 25824992 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Info                                                               rmix.  The module is licensed under the Apache License 2.0. The package also inc                                                               ludes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the                                                                node module is installed on your system/device. The license agreement to the IB                                                               M ODBC and CLI Driver is available in E:\electron\ibm-db-electron\node_modules\i                                                               bm_db\installer   Check for additional dependencies, which may come with their o                                                               wn license agreement(s). Your use of the components of the package and dependenc                                                               ies constitutes your acceptance of their respective license agreements. If you d                                                               o not accept the terms of any license agreement(s), then delete the relevant com                                                               ponent(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully...


> electron@1.5.1 postinstall E:\electron\ibm-db-electron\node_modules\electron
> node install.js


> ibm-db-electron@1.0.0 postinstall E:\electron\ibm-db-electron
> npm run fix:ibm_db && install-app-deps


> ibm-db-electron@1.0.0 fix:ibm_db E:\electron\ibm-db-electron
> chmod -R +w node_modules/ibm_db/installer

Rebuilding native production dependencies for win32:x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> ibm_db@2.0.0 install E:\electron\ibm-db-electron\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub                                                               /software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...


Error output:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\electron\ibm-db-electron\node                                                               _modules\ibm_db\build.zip'

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                               node_modules\\npm\\bin\\npm-cli.js" "rebuild" "ibm_db"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! ibm_db@2.0.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.0.0 install script 'node installer/driverInstall                                                               .js'.




Now I have few queries about this script. 
1) Why this script again downloading the ibm_db component and trying to build it, because npm install has already done that work. (downloading and installing it perfectly).
2) Why can't electron directly use that installed version of ibm_db rather than rebuilding it again? may be you can avoid that rebuilding step in script. I think it should work.

**Comment by rhtpandeyIN** [comment] 2017-04-05 11:18
duplicate of #239

**Comment by kloener** [comment] 2017-04-05 18:46
Hi @rhtpandeyIN, thanks for your reply! 

Electron recommends to call `install-app-deps` in the postinstall process to install other application dependencies. For this example it's not needed, but may be in a real project.

I didn't find any option to disable rebuilding node-modules when calling `install-app-deps`. Releasing the application means packaging it with **electron-build** which, again, rebuilds all native node-modules. And **electron-rebuild** rebuilds all node-modules, too, as the name says (https://electron.atom.io/docs/tutorial/using-native-node-modules/). 

Nevertheless, I removed the postinstall command in the package.json. And yes, after this the installation works. And I get an error, if I start the app with `npm start` anyway. 
See this screenshot (same error as in step 5 from first post):

<img width="927" alt="bildschirmfoto 2017-04-05 um 19 45 47" src="https://cloud.githubusercontent.com/assets/737537/24720807/98a3524e-1a3e-11e7-8ddf-d4af0e848458.png">

The error you got is correct. I get it, too. See "3." to workaround that. 
Or you remove the *postinstall* line in the *package.json* and no rebuild is done by electron. But then another error occurs.

**Comment by kloener** [comment] 2017-04-06 20:55
I had similar issues with the node-java package and I could fix it by setting some additional paths to the Path environment variable in Windows system settings (JRE path).
Is there any path important to be included in the Path variable for ibm_db to work? May be the clidriver or clidriver/include path? 

We now use node-jdbc and now it works in our application. For me, the issue is not relevant anymore.

kind regards.

**Comment by bimalkjha** [comment] 2017-04-07 07:00
@kloener Add ibm_db/installer/clidriver/bin and ibm_db/installer/clidriver/lib at start of your LIB and PATH system environment variables. Thanks.

**Comment by rhtpandeyIN** [comment] 2017-06-08 09:13
Issue addressed with latest code changes.

**Closed by rhtpandeyIN** 2017-06-08 09:13 UTC
