### ISSUE TITLE
querySync doesn't throw exception but returns an error object

### ISSUE THREAD

**Issue by LsKoder** [ibmdb/node-ibm_db#468] opened 2018-10-18 08:59 UTC
Excuting an "create table" query through querySync(), it returned an object instead an any[] as declared.
The object returned is an error but it's not throws as exception.
The following example could explain better;

try {
  const result = querySync(createQuery);
  console.log("ERROR: "+result.error+");
  console.log("MESSAGE: "+ result.message);
} catch (error){
  console.log("Here exception should be catched: "+error);
}

Output:
 ERROR: [node-ibm_db] Error in ODBCConnection::QuerySync while executing query.'
 MESSAGE: '[IBM][CLI Driver][DB2/LINUXX1234] SQL0542N  The column named "XXX" cannot be a column of a primary key or unique key constraint
because it can contain null values.  SQLSTATE=42831\r\n'

I expect to read the console.log into catch, not a returned error. Also, @types/ibm_db defines querySync() as any[] but in this case it returns an object any (not an array)

Note: In other cases try\catch worked successfully, so the problem occurs just in some cases.

**Comment by bimalkjha** [comment] 2018-10-18 19:22
@LsKoder Its a duplicate of #459 . Please check it for more info. Thanks.

**Closed** 2018-11-05 08:42 UTC
