### ISSUE TITLE
SQLExecute gives -23003 for column that have specific precision

### ISSUE THREAD

**Issue by alexcfyung** [ibmdb/node-ibm_db#542] opened 2019-05-31 22:04 UTC
When using SQLPrepare, SQLBindParameter and SQLExecute, it gives error -23003 for column that have specific precision like `DECIMAL(3)`.

For example, creating a table
```
create table mytab1 (c5 DECIMAL(3))
```
running this query will succeed
```
querySync("insert into mytab1 values (67.98)");
```
but running this query will fail with -23003
```
querySync("insert into mytab1 values (?)", [67.98]);
```
The reason is that in `ODBC::GetNumberParam`, `param->decimals` set to a fixed number 7, changing the decimal to the specified precision will run successfully.
https://github.com/ibmdb/node-ibm_db/blob/46d444e6fd35cf7085a97d7807c753a8860ac88c/src/odbc.cpp#L1092
I suggest determine the decimal by counting trailing zeros and use the calculated decimal instead.

I am testing it on z/OS, I didn't test on other platform so I am not sure if this is a z/OS specific issue or not.

**Comment by davidbowenukibmcom** [comment] 2019-06-19 23:42
This is not a good solution, but in order to keep the SQL stable (so we can use prepared statements) we did the following (adapted to your example):

```
querySync("insert into mytab1 values (CAST(? AS DECIMAL(20,5))", ["67.98000"]);
```

**Comment by alexcfyung** [comment] 2019-06-24 15:18
Currently the test failed in z/OS because of the issue above : https://github.com/ibmdb/node-ibm_db/blob/98d47ef87d24579a3fa9c5521223bada41e9a5c7/test/test-all-data-types.js#L45

**Comment by PriyankaManoharan04** [comment] 2019-06-27 05:08
@alexcfyung  Can you provide the complete output/Error of running the below query.

> ```
> querySync("insert into mytab1 values (?)", [67.98]);
> ```
 Thanks.

**Comment by davidbowenukibmcom** [comment] 2019-06-27 23:01
Hi @PriyankaManoharan04,

We saw this:

```javascript
{
"error":"[node-odbc] SQL_ERROR",
"message":"[IBM][CLI Driver] CLI0111E  Numeric value out of range. SQLSTATE=22003",
"state":"22003",
"sqlcode":-99999
}
```

**Comment by PriyankaManoharan04** [comment] 2019-06-28 07:02
@davidbowenukibmcom i can't reproduce your error can you share your code with `create table` query and  `insert` query.

**Comment by alexcfyung** [comment] 2019-06-28 23:54
@PriyankaManoharan04 Are you testing it in z/OS?

**Comment by PriyankaManoharan04** [comment] 2019-06-29 05:53
@alexcfyung yes i am testing it in z/OS. Can you share your sample code with output.

**Comment by PriyankaManoharan04** [comment] 2019-07-02 10:42
@alexcfyung For inserting the value 

> querySync("insert into mytab1 values (?)", [67.98]);

try to create table with table definition `create table mytab1 (c5 DECIMAL(4,2))` and check can you able to insert the data.You can also refer the test file `test-all-data-types.js` under the test folder for inserting data with decimal datatype.

Thanks.

**Comment by bimalkjha** [comment] 2019-07-02 13:59
@alexcfyung Please check https://github.com/ibmdb/node-ibm_db/blob/master/test/test-all-data-types.js to see how to create table and insert decimal data. Thanks.

**Comment by alexcfyung** [comment] 2019-07-05 21:33
@PriyankaManoharan04 @bimalkjha  I already provide the example where this failed in `test-all-data-types.js`.

> Currently the test failed in z/OS because of the issue above :
> 
> https://github.com/ibmdb/node-ibm_db/blob/98d47ef87d24579a3fa9c5521223bada41e9a5c7/test/test-all-data-types.js#L45

This is a small test case I wrote:
```javascript
var common = require("./test/common")
    , ibmdb = require("./")
    , assert = require("assert")
    , cn = common.connectionString;

ibmdb.debug(true);

ibmdb.open(cn, function (err, conn) {
  console.log("bla");
  if (err) return console.log(err);
  console.log("bla2");

  conn.querySync("drop table mytab1");

  conn.query('create table mytab1 (c5 DECIMAL(3))', function (err, data) {
    if (err) console.log(err);
    else console.log(data);
    err = conn.querySync("insert into mytab1 values (?)", [67.98]);
    conn.querySync("drop table mytab1");
    conn.close(function () {
      console.log('done');
    });
  });
});
```

This is the trace log in EBCDIC
[trace22.log](https://github.com/ibmdb/node-ibm_db/files/3364034/trace22.log)
```
[01000B63 0000000000000001] SQLGetDiagRec( fHandleType=SQL_HANDLE_STMT, hHandle=1, iRecNumber=1, pszSqlState=&50082ef2a0, pfNativeError=&50082ef294, pszErrorMsg=&50082ef2b0, cbErrorMsgMax=1024, pcbErrorMsg=&50082ef298 )
[01000B63 0000000000000001] SQLGetDiagRec( pszSqlState="22003", pfNativeError=-99999, pszErrorMsg="{DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=22003  ERRLOC=4:29:3", pcbErrorMsg=60 )
[01000B63 0000000000000001]     ---> SQL_SUCCESS

[01000B63 0000000000000001] SQLGetDiagRec( fHandleType=SQL_HANDLE_STMT, hHandle=1, iRecNumber=2, pszSqlState=&50082ef2a0, pfNativeError=&50082ef294, pszErrorMsg=&50082ef2b0, cbErrorMsgMax=1024, pcbErrorMsg=&50082ef298 )
[01000B63 0000000000000001] SQLGetDiagRec( )
[01000B63 0000000000000001]     ---> SQL_NO_DATA_FOUND
```
22003 means "A numeric value is out of range". As mentioned before, the issue is caused by the hard coding for decimal place in `odbc.cpp`

> The reason is that in `ODBC::GetNumberParam`, `param->decimals` set to a fixed number 7, changing the decimal to the specified precision will run successfully.
> https://github.com/ibmdb/node-ibm_db/blob/46d444e6fd35cf7085a97d7807c753a8860ac88c/src/odbc.cpp#L1092

**Comment by PriyankaManoharan04** [comment] 2019-07-07 01:34
@alexcfyung 

Instead of using this table definition for create query


> ```js
> 
>   conn.query('create table mytab1 (c5 DECIMAL(3))', function (err, data) {
> ```


use `conn.query('create table mytab1 (c5 DECIMAL(4,2))', function (err, data) {` and check can you able to insert the data.

Thanks.

**Comment by alexcfyung** [comment] 2019-07-08 16:49
@PriyankaManoharan04 I tried with `conn.query('create table mytab1 (c5 DECIMAL(4,2))', function (err, data) {` but still produce the same `22003` error.

**Comment by PriyankaManoharan04** [comment] 2019-07-09 06:09
@alexcfyung  Can you share in which operating system you have installed ibm_db.

Thanks.

**Comment by PriyankaManoharan04** [comment] 2019-07-10 11:00
@alexcfyung

 If you are inserting value  `67.98`

> ```js
> conn.querySync("insert into mytab1 values (?)", [67.98]);
> ```

your table definition should be this as shown below


> ```js
> conn.query('create table mytab1 (c5 DECIMAL(4,2))', function (err, data) {
> ```

For inserting different values you need to change your table definition.Numeric value out of range error is thrown only if the value exceeds the table definition.

For example for inserting value `7899.9090` try to create table with table definition as shown below
```
ibmdb.open(cn, function (err, conn) {

    conn.querySync("drop table mytab1")

    conn.querySync("create table mytab1 (c5 DECIMAL(8,4))");
    conn.querySync("insert into mytab1 values (?)", [7899.9090]);
    var rows = conn.querySync("select * from mytab1")
    console.log(rows);
});
```
Give a try to verify and let us know, if you are still getting that error share your platform and nodejs version and db2level.

Thanks.

**Comment by PriyankaManoharan04** [comment] 2019-07-10 11:27
@davidbowenukibmcom 

Numeric value out of  range error is thrown because in this query, one close bracket is missing.

> querySync("insert into mytab1 values (CAST(? AS DECIMAL(20,5))", ["67.98000"]);

try using this query  as shown below and give a try to verify.

`querySync("insert into mytab1 values (CAST(? AS DECIMAL(20,5)))", ["67.98000"]);`

Thanks.

**Comment by alexcfyung** [comment] 2019-07-10 22:27
@PriyankaManoharan04 The operating system I am using is OS/390 SA2B 25.00 04 3906
This is essentially my test case:
```javascript
var common = require("./test/common")
    , ibmdb = require("./")
    , assert = require("assert")
    , cn = common.connectionString;

ibmdb.debug(true);

ibmdb.open(cn, function (err, conn) {
  console.log("bla");
  if (err) return console.log(err);
  console.log("bla2");

  conn.querySync("drop table mytab1");

  conn.query('create table mytab1 (c5 DECIMAL(4,2))', function (err, data) {
    if (err) console.log(err);
    else console.log(data);
    err = conn.querySync("insert into mytab1 values (?)", [67.98]);
    conn.querySync("drop table mytab1");
    conn.close(function () {
      console.log('done');
    });
  });
});
```
As I mentioned this line is the issue...
https://github.com/ibmdb/node-ibm_db/blob/46d444e6fd35cf7085a97d7807c753a8860ac88c/src/odbc.cpp#L1092
For prepare statement, setting decimals to 7 in hard code convert every number into 7 decimals precision, so 67.98 will convert to 67.9800000 then pass to db2, it throws 22003 error as the column is created as 2 precision.

**Comment by bimalkjha** [comment] 2019-08-26 12:03
@alexcfyung I think you are running this test program on z/OS where ibm_db is using z/OS odbc driver. We used the same program to connect to Db2 for z/OS v12 from ibm_db installed on Linux, and it works fine. So, it looks, the LUW odbc driver and z/OS odbc driver works differently.
> param->decimals      = 7

Can you please clarify, it is precision of scale? From the documentation of [SQLBindParameters](https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/odbc/src/tpc/db2z_fnbindparameter.html), it looks sqlbindparameter require scale not precision and hence `param->decimals` should set the scale of the decimal data. Thanks.

**Comment by bimalkjha** [comment] 2019-08-26 15:50
@alexcfyung I have pushed the fix of this issue on github with latest commit. Please pull the latest code and verify it. Thanks.

**Closed by bimalkjha** 2019-08-26 15:50 UTC
