### ISSUE TITLE
fetchAllSync and closeSync work then stop working (fails on node 4x, 6x, 7x, 8x)

### ISSUE THREAD

**Issue by amcintyre99** [ibmdb/node-ibm_db#295] opened 2017-07-17 03:39 UTC
Ubuntu 16.04.2 LTS
node 8.1.3
ibm_db 2.1.0
db2 11.1

With this code
```
$ cat prep_exec.js 
let db = require("ibm_db")();
db.openSync("DATABASE=xx;UID=yy;PWD=zz");
let stmt = db.prepareSync("select current_time from (values 1)");
for (let i = 0; i < 30; i++) {
  stmt.execute([], function (err, result) {
    data = result.fetchAllSync();
    console.log(data);
    result.closeSync();
    })
}
```
why does it work, then stop working?
```
$ node prep_exec.js 
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[ { '1': '23:26:59' } ]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
```

**Comment by amcintyre99** [comment] 2017-07-18 01:30
This issue is related to the CLI DisableMultiThread keyword because when I disable it in db2cli.ini, the code works a few times and then hangs instead of continuing to print nulls.
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008791.html

**Comment by rhtpandeyIN** [comment] 2017-07-18 17:02
Hi @amcintyre99 ,
I think there is some problem with node 8.x versions, because I tried the same test case (above one) with older versions of nodejs i.e: node 4.x, 6.x, 7.x, and it is working perfectly fine, and giving correct output without breaking any thing.


--------------------------------------------------------
$ node -v
v7.4.0

$ node new.js
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]
[ { '1': '22:25:15' } ]


---------------------------------------------------------------
$ node -v
v6.9.1

$ node new.js
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:32' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]
[ { '1': '22:23:33' } ]

---------------------------------------------------------
but with node 8.x it is giving wrong output:

$ node -v
v8.1.2

$ node new.js
[ { '1': '22:26:17' } ]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

**Comment by rhtpandeyIN** [comment] 2017-07-18 17:04
We recommend to use stable version of nodejs for development purpose. Thanks.

**Comment by amcintyre99** [comment] 2017-07-18 17:42
Node 8.x went to Current status in May and is going LTS in October.
https://github.com/nodejs/LTS

What makes you think this is their issue?

**Comment by rhtpandeyIN** [comment] 2017-07-18 20:08
Well I haven't investigated deeply, but on first glance it looks like it is nodejs issue, as same code is working fine for older nodejs versions and working weirdly with node 8.x, even after when module has been successfully compiled and build with node 8.x. 
So I don't think - any node-ibm_db api should fail with node 8.x, so first look is saying nodejs version has some problem but, still I am not so sure about it hence we need to investigate why this is happening.

**Comment by amcintyre99** [comment] 2017-07-18 21:53
Still fails after changing to executeSync.

However adding DisableMultiThread = 1 to db2cli.ini now returns a msg instead of hanging like execute did.
```
let db = require("ibm_db")();
db.openSync("DATABASE=xx;UID=yy;PWD=zz");
let stmt = db.prepareSync("select current_time from (values 1);");
for (let i = 0; i < 30; i++) {
  result = stmt.executeSync([]);
  data = result.fetchAllSync();
  console.log(data);
  result.closeSync();
};

$ node prep_execsync_orig.js 
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[ { '1': '17:35:53' } ]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

after adding DisableMultiThread = 1 to db2cli.ini
$ node prep_execsync_orig.js 
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]
[ { '1': '17:43:18' } ]

/home/andrew/dma/ibt/node_modules/ibm_db/lib/odbc.js:1122
  return self._executeSync();
              ^
Error: [IBM][CLI Driver] CLI0115E  Invalid cursor state. SQLSTATE=24000

```

**Comment by amcintyre99** [comment] 2017-07-20 03:10
The issue is not just in 8.x. The counter was too low so if you increase it you can see it fail at a different number in each version.

I just tested latest 6.x, 7.x and 8.x. See below. And this is with executeSync, not execute.

The reason this is a concern is I need a prepare then execute path for my code, because I run the execute about a million times a day. If you have an alternative let me know.

And fyi, about 1 out of 10 tests I would see this error msg at the end of the run:
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 92, index = 1
node: ../src/odbc.cpp:609: static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int): Assertion `ret != SQL_INVALID_HANDLE' failed.
Aborted (core dumped)


```
$ cat prep_execsync_orig.js 
let db = require("ibm_db")();
db.openSync("DATABASE=xx;UID=yy;PWD=zz");
let stmt = db.prepareSync("select current_time from (values 1);");
for (let i = 0; i < 500; i++) {
  result = stmt.executeSync([]);
  data = result.fetchAllSync();
  if (data.length == 1) console.log(data,i);
  result.closeSync();
};


$ node -v
v6.11.1
$ node prep_execsync_orig.js 
[ { '1': '22:55:28' } ] 0
[ { '1': '22:55:28' } ] 1
[ { '1': '22:55:28' } ] 2
[ { '1': '22:55:28' } ] 3
..
[ { '1': '22:55:28' } ] 185
[ { '1': '22:55:28' } ] 186
[ { '1': '22:55:28' } ] 187
[ { '1': '22:55:28' } ] 188
$ 


$ node -v
v7.10.1
$ node prep_execsync_orig.js 
[ { '1': '22:38:05' } ] 0
[ { '1': '22:38:05' } ] 1
[ { '1': '22:38:05' } ] 2
[ { '1': '22:38:05' } ] 3
..
[ { '1': '22:38:05' } ] 181
[ { '1': '22:38:05' } ] 182
[ { '1': '22:38:05' } ] 183
[ { '1': '22:38:05' } ] 184
$ 


$ node -v
v8.1.4
$ node prep_execsync_orig.js 
[ { '1': '22:21:33' } ] 0
[ { '1': '22:21:33' } ] 1
[ { '1': '22:21:33' } ] 2
[ { '1': '22:21:33' } ] 3
..
[ { '1': '22:21:33' } ] 137
[ { '1': '22:21:33' } ] 138
[ { '1': '22:21:33' } ] 139
[ { '1': '22:21:33' } ] 140
$ 
```

**Comment by rhtpandeyIN** [comment] 2017-07-20 06:16
great, I will test that. Thanks for the update.

**Comment by amcintyre99** [comment] 2017-07-22 14:30
Still fails with 8.2.1. And still shows CLI0125E msg with DisableMultiThread = 1.
```
$ node -v
v8.2.1
$ node prep_execsync_orig.js 
[ { '1': '10:26:55' } ] 0
[ { '1': '10:26:55' } ] 1
[ { '1': '10:26:55' } ] 2
[ { '1': '10:26:55' } ] 3
..
[ { '1': '10:26:55' } ] 135
[ { '1': '10:26:55' } ] 136
[ { '1': '10:26:55' } ] 137
[ { '1': '10:26:55' } ] 138

/home/andrew/dma/ibt/prep_execsync_orig.js:6
  let data = result.fetchAllSync();
                    ^
Error: [IBM][CLI Driver] CLI0125E  Function sequence error. SQLSTATE=HY010
    at Object.<anonymous> (/home/andrew/dma/ibt/prep_execsync_orig.js:6:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by amcintyre99** [comment] 2017-07-22 15:19
CLI trace showing many SQL_INVALID_HANDLE errors towards the end of the file.
[072217.txt](https://github.com/ibmdb/node-ibm_db/files/1167437/072217.txt)

**Comment by rhtpandeyIN** [comment] 2017-07-22 21:03
Yes I checked the code, and able to reproduce the problem. till 1.0.1 version it was working fine, afterward versions having problem.
I am still figuring out what can be the cause, till now it seems it is because of removal of locking mechanism (I am not sure though), may be due to some other issue also. 
So please wait for our next update, we will fix it soon. Thanks

**Comment by amcintyre99** [comment] 2017-07-22 21:49
Yep, 1.0.1 works. Thanks for the tip.

**Comment by amcintyre99** [comment] 2017-07-22 23:33
Fyi, the above executeSync code also fails with Dan's odbc module, including the latest updates from Ben in March:
https://github.com/wankdanker/node-odbc/commits/master

Fails around 15000+ every time.

**Comment by rhtpandeyIN** [comment] 2017-07-25 15:28
Hi,
We have pushed a fix for this issue, please take the latest code from github and if possible verify it.
Please use following command for that:

`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

Thanks.

**Comment by amcintyre99** [comment] 2017-07-25 16:33
Still fails around 14000+.
```
$ cat prep_execsync_orig.js
"use strict";
let db = require("ibm_db")();
db.openSync("DATABASE=xx;UID=yy;PWD=zz");
let stmt = db.prepareSync("select current_time from (values 1);");
for (let i = 0; i < 50000; i++) {
  let result = stmt.executeSync([]);
  let data = result.fetchAllSync();
  if (data.length == 1) console.log(data,i);
  result.closeSync();
};

$ node -v
v8.2.1
$ node prep_execsync_orig.js
[ { '1': '12:26:13' } ] 0
[ { '1': '12:26:13' } ] 1
[ { '1': '12:26:13' } ] 2
[ { '1': '12:26:13' } ] 3
...
[ { '1': '12:26:17' } ] 14145
[ { '1': '12:26:17' } ] 14146
[ { '1': '12:26:17' } ] 14147
[ { '1': '12:26:17' } ] 14148
$ 
```

**Comment by rhtpandeyIN** [comment] 2017-07-26 07:26
Hi, 
I tested the below code with node 4.6.1 and it's working fine for me, you can see the output it's 40k+


$ node -v
v4.6.1


```
var ibmdb = require("ibm_db");
var cn="DRIVER={DB2 ODBC Driver};DATABASE=SAMPLE;HOSTNAME=localhost;UID=rohit;PWD=password;PORT=50000;PROTOCOL=TCPIP";

var con = ibmdb.openSync(cn);

var stmt = con.prepareSync("select current_time from (values 1)");

for (var i = 0; i < 50000; i++) {

  var result = stmt.executeSync();
  var data = result.fetchAllSync();
  if (data.length == 1) console.log(data,i);
  result.closeSync();
}

stmt.closeSync();

```

[ { '1': '12:47:53' } ] 43899
[ { '1': '12:47:53' } ] 43900
[ { '1': '12:47:53' } ] 43901
[ { '1': '12:47:53' } ] 43902
[ { '1': '12:47:53' } ] 43903
[ { '1': '12:47:53' } ] 43904
[ { '1': '12:47:53' } ] 43905
[ { '1': '12:47:53' } ] 43906
[ { '1': '12:47:53' } ] 43907
[ { '1': '12:47:53' } ] 43908
[ { '1': '12:47:53' } ] 43909
[ { '1': '12:47:53' } ] 43910
[ { '1': '12:47:53' } ] 43911
[ { '1': '12:47:53' } ] 43912

**Comment by rhtpandeyIN** [comment] 2017-07-26 07:32
Also, as per our latest investigation, we got to know that this issue is coming because of Garbage collector.
after some amount of time (varying on different machines), Garbage collector explicitly calling itself and freeing the handle, we fixed some part of it, but still it seems issue is there.
But it won't break for normal values I guess, only as you mentioned for large data it would break.
We are still looking into to, till than I request you to please just try to test it with older node versions and if possible in different platform machines, and keep us update.


Thanks for your time and efforts.

**Comment by amcintyre99** [comment] 2017-07-26 10:54
Sorry but I just tested your code above on the latest 4.x and it failed after 33 lines.
```
$ node -v
v4.8.4
$ node fromibm.js
[ { '1': '06:51:35' } ] 0
[ { '1': '06:51:35' } ] 1
[ { '1': '06:51:35' } ] 2
[ { '1': '06:51:35' } ] 3
[ { '1': '06:51:35' } ] 4
[ { '1': '06:51:35' } ] 5
[ { '1': '06:51:35' } ] 6
[ { '1': '06:51:35' } ] 7
[ { '1': '06:51:35' } ] 8
[ { '1': '06:51:35' } ] 9
[ { '1': '06:51:35' } ] 10
[ { '1': '06:51:35' } ] 11
[ { '1': '06:51:35' } ] 12
[ { '1': '06:51:35' } ] 13
[ { '1': '06:51:35' } ] 14
[ { '1': '06:51:35' } ] 15
[ { '1': '06:51:35' } ] 16
[ { '1': '06:51:35' } ] 17
[ { '1': '06:51:35' } ] 18
[ { '1': '06:51:35' } ] 19
[ { '1': '06:51:35' } ] 20
[ { '1': '06:51:35' } ] 21
[ { '1': '06:51:35' } ] 22
[ { '1': '06:51:35' } ] 23
[ { '1': '06:51:35' } ] 24
[ { '1': '06:51:35' } ] 25
[ { '1': '06:51:35' } ] 26
[ { '1': '06:51:35' } ] 27
[ { '1': '06:51:35' } ] 28
[ { '1': '06:51:35' } ] 29
[ { '1': '06:51:35' } ] 30
[ { '1': '06:51:35' } ] 31
[ { '1': '06:51:35' } ] 32
[ { '1': '06:51:35' } ] 33
$
```

**Comment by rhtpandeyIN** [comment] 2017-07-26 11:22
Did you installed ibm_db using this command : npm install git+https://git@github.com/ibmdb/node-ibm_db.git ?

If yes then use your own code with 4.x and post the output.

Thanks

**Comment by amcintyre99** [comment] 2017-07-26 11:44
Sorry about that... so I just retested your code with the latest ibm_db installed from git and node 4.8.4 and bumped it to 500,000 and it fails around 62000+ every time.
```
$ npm ls --depth=0
/home/andrew/dma/ibt
ibm_db@2.1.0 (git+https://git@github.com/ibmdb/node-ibm_db.git#d89c2c99f57fa8a7680563b0024df95a9c8fed80)

$ node -v
v4.8.4
$ node fromibm.js
...
[ { '1': '07:41:42' } ] 62832
[ { '1': '07:41:42' } ] 62833
[ { '1': '07:41:42' } ] 62834
[ { '1': '07:41:42' } ] 62835
$ 
```

**Comment by rhtpandeyIN** [comment] 2017-07-26 11:54
Good to know, but yeah it's still breaking. As I told earlier this issue is because of Garbage collector, and will vary on different machines. can you verify this on different machine?

**Comment by amcintyre99** [comment] 2017-07-26 12:31
Sorry but only have single server to test with.

Fyi, with your git code and 8.2.1 it runs the longest but still fails at about 175,000 every time.

My code runs anywhere from 1 to 10 million times a day so this execute/executeSync issue is really affecting me.

**Comment by amcintyre99** [comment] 2017-07-26 14:35
Thought I would try node 8.2.1 on test/bench-prepare-execute-closeSync.js with both the npm released 2.1.0 and your github version.

The npm version fails after 382 but your github version makes it to 1 million!!! yea!!!

The only change I made to bench-prepare-execute-closeSync.js was to uncomment this line:
console.log(result.fetchAllSync());

So your fix looks good AND there is something magic about bench-prepare-execute-closeSync.js that we are missing in the other code we've been testing with.

```
without your github fix
$ node bench-prepare-execute-closeSync.js
...
[ { TEST: 380 } ]
[ { TEST: 381 } ]
[ { TEST: 382 } ]
[]
[]
[]

with your github fix
$ node bench-prepare-execute-closeSync.js
....
[ { TEST: 999997 } ]
[ { TEST: 999998 } ]
[ { TEST: 999999 } ]
(1000000 queries issued in 2168.326 seconds, 461.19 query/sec)
```

**Comment by rhtpandeyIN** [comment] 2017-07-26 17:36
Hurray!, 
Finally a good news.

LOL!, that magic thing saved our day :) :) 
Well, I think that wasn't magic, in that test case there is "execute" api not the "executeSync", may be because of this you achieved latest behavior, and I am pretty much sure that during sync api processing happening so fast that Garbage collector freeing the handle unintentionally, but in the aysnc case that Garbage collection process is not freeing the handle before completely executing the process attached with the handle.

Great thing is you gave us a clue, I will check both api's code and will investigate how to optimize the "executeSync" code too.

Thanks.

**Comment by amcintyre99** [comment] 2017-07-26 17:47
I actually wanted execute, I was only testing executeSync because execute wouldn't work. Remember my first post at the top of this issue was using execute.

Now I just have to figure out what is special in bench-prepare-execute-closeSync.js that lets it work, but yet my larger module that uses execute code doesn't work... yet.

Thanks for the help and the fix!!

**Comment by rhtpandeyIN** [comment] 2017-08-14 11:37
Hi, for now, I am closing the issue and if you got something new in this regards please let us know.
Thanks for your time and efforts.

**Closed by rhtpandeyIN** 2017-08-14 11:37 UTC
