### ISSUE TITLE
SSL connection to db2 is slower

### ISSUE THREAD

**Issue by DaisyYangl** [ibmdb/node-ibm_db#930] opened 2023-06-20 03:38 UTC
Hello team, 
We used the connection string to connect DB2 and it worked well, but we met a issue is: it takes too much time to get connection . 
Nodejs:  v14/ v16
ibm_db: "^2.7.3"
const stringconnStr = "DATABASE=database;HOSTNAME=hostname;PORT=port;Security=SSL;SSLServerCertificate=<cert.arm_file_path>;PROTOCOL=TCPIP;UID=username;PWD=passwd;";
This is the time cost:
No ssl connection: 870.773ms
ssl_connection: 3.385s

Do you have any suggestion how to improve this since our each API request will connect to DB2 once?
Thanks so much!

**Comment by bimalkjha** [comment] 2023-06-20 10:41
@DaisyYangl Try using connection pooling as used [this test file](https://github.com/ibmdb/node-ibm_db/blob/master/test/webapp.js) for faster connection. pool.init() will open all connections and will keep it in pool to be used by pool.open().
You can also update your ibm_db to 3.2.1 version which is the latest version and few pool related issues are fixed in it.
Still facing issue, let us know the Operating System name on which you have installed ibm_db. We'll share commands to collect db2traces using which we can find the root cause and which step is taking more time for SSL and non-SSL connection. Thanks.

**Closed** 2023-07-04 05:34 UTC
