### ISSUE TITLE
Could not load the bindings file

### ISSUE THREAD

**Issue by nikixp** [ibmdb/node-ibm_db#108] opened 2016-04-05 12:22 UTC
Something is wrong with the newest node versions. 
When I try to make 

> require("ibm_db")

 I'm receiving the same error like this example in [tonic](https://tonicdev.com/npm/ibm_db)

**Comment by rhtpandeyIN** [comment] 2016-04-05 12:36
Hi @nikixp ,
can you please tell us for which node version and for which machine you are getting this error.

**Comment by nikixp** [comment] 2016-04-05 13:09
Hi @rhtpandeyIN 
Node.js version is v4.4.2-x64 on Windows 10 x64.

**Comment by rhtpandeyIN** [comment] 2016-04-05 15:02
Hi, I am not able to reproduce above error, can you explain you steps.
I am using same machine and same node.js version and I am not getting any error, it's fine for me.

**Comment by nikixp** [comment] 2016-04-05 15:37
I saw where the problem is. 
When I install the package with `npm install ibm_db` from my IDE's terminal (WebStorm 11.0.3) the **build** folder and **installer\clidriver** folder were missing. 
After I install it in the normal way from command prompt everything was fine.
Thanks for the reply @rhtpandeyIN.

**Comment by rhtpandeyIN** [comment] 2016-04-05 17:01
possible reason can be poor internet connectivity at that time frame. Well it's always nice to hear satisfactory words from users. most welcome @nikixp.
and thanks for the feedback. Closing the issue now.

**Closed by rhtpandeyIN** 2016-04-05 17:01 UTC
