### ISSUE TITLE
IBM DB Library Not Working with Higher Version of Node 14

### ISSUE THREAD

**Issue by jsalcedoa** [ibmdb/node-ibm_db#803] opened 2021-10-28 15:22 UTC
Hi I'm getting an error when deploying my application during the docker build process when installing the node packages. I noticed that the tag I was using in my docker file now has a newer version of node, I'm running in my local version 14, so after using a different tag with version 14 I can deploy successfully again. 

Can you please check why a higher version of node 14 is having issues with the library? I even tried upgrading the ibm_db package from 2.7 to 2.8 but it still fail.

This is the screenshot of my console before the error occurs:

![image](https://user-images.githubusercontent.com/29698309/139286247-cd859117-7e56-4730-abe0-fee746cfaaf0.png)

This is the screenshot of my console after the error occurs:

![image](https://user-images.githubusercontent.com/29698309/139286336-2f24496e-d96a-4f0e-a4fa-f4c8a4615725.png)

**Comment by bimalkjha** [comment] 2021-10-30 18:06
@jsalcedoa I checked the error. The output says, you are using node.js v16.11.0. I have tested using both v16.11.0 and v14.18.1 on Linux system. `ibm_db` installation output is as below:
```
> node installer/driverInstall.js

platform = linux, arch = x64, node.js version = v16.11.0
make version =GNU Make 4.1

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /home/bjha/nodework/master/ibm_db/installer/clidriver. Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz ...

100.00% | 24805204 bytes downloaded out of 24805204 bytes.

Downloading and extraction of DB2 ODBC CLI Driver completed successfully.
```
If we compare, above output with yours, we can see that for your case, `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz` has not downloaded completely. It downloaded only **`38.24%`** and download got interrupted. **This is the root cause of the problem.**
The download may got interrupted due to network issue. Please retry again and this issue should be resolved.
If issue still persist, try to manually download `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz` and see if you are able to download or not.
Adding below lines in your script may work:
```
cd $HOME
wget https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
tar xzf linuxx64_odbc_cli.tar.gz
export IBM_DB_HOME=$HOME/clidriver
npm install ibm_db
```
Thanks.

**Comment by bimalkjha** [comment] 2021-11-07 19:49
@jsalcedoa I hope your issue is resolved now, hence closing the issue. Thanks.

**Closed by bimalkjha** 2021-11-07 19:49 UTC

**Comment by jsalcedoa** [comment] 2022-04-21 20:31
Hi @bimalkjha I wanted to give you an update on this issue I opened long time ago. I was able to solve the problem temporarily by using a Docker Hub image with a lower version of node, from **v16.11** to the **v14.17**, and this fixed the problem. But now Docker Hub upgraded the node version to **v14.19** and I started to have issues again. 

So I decided to retake this issue and I want to use the LTS version of node **v16.14**  but I'm still getting the same error. The error only happens when deploying the application using Docker and Kubernetes, it's working fine in my local. I'm getting this error specifically during the docker build command. 

I don't think this is a network issue because I can download the file from the url you shared me and not only me but my coworkers located in different places also have the same issue, and as I mentioned if I use a lower version of node I do not get the error any more. 

**Here is my Docker file commands including your suggestion above:**

```
FROM node:lts-stretch
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y apt-transport-https make g++ python-pip
RUN pip install --no-cache --upgrade pip setuptools

WORKDIR '/app'
COPY ./dist . 
EXPOSE 3000

RUN cd $HOME
RUN wget https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
RUN tar xzf linuxx64_odbc_cli.tar.gz
RUN export IBM_DB_HOME=$HOME/clidriver
RUN npm install ibm_db@2.8.0

RUN npm install --loglevel verbose
ENTRYPOINT ["npm", "start"]
```

**This is the error:**

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/29698309/164545710-6e381cbc-1d80-4ad5-a57f-b0bd4730a625.png">

**Comment by jsalcedoa** [comment] 2022-04-22 01:23
Hi, after trying several things I found out the issue in fact is not related to the **ibm_db** library, there is something wrong with all the versions of the node docker hub images (stretch, alpine, slim, etc...) that uses Node JS versions higher than v14.18. Any version of node lower to that works totally fine. 

The way I found out this, was because in my local I had no problems with the LTS version of Node JS (v16) with the **ibm_db** library and also I found out after I changed my docker file to use the Node JS full official image. 

I will try to report this to the developers of the node images in the Docker Hub to see if they can make any fixes on their end. If you guys can also take a look and see if there is something you can do in the **ibm_db** library then that would work too. Maybe there is a package or library that needs to be installed separate that is missing in the Docker Hub Node JS images. I knew what this library might be I could just install it after importing the image.
