### ISSUE TITLE
0.0.12 fails to install on IBM Bluemix

### ISSUE THREAD

**Issue by knolleary** [ibmdb/node-ibm_db#43] opened 2015-07-31 13:51 UTC
Hi,

as of the 0.0.12 release, the node-red boilerplate on IBM Bluemix no longer installs. It fails with:

```
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! ibm_db@0.0.12 install: `node installer/driverInstall.js`
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! Exit status 1
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR!
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! Failed at the ibm_db@0.0.12 install script.
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! This is most likely a problem with the ibm_db package,
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! not with npm itself.
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! Tell the author that this fails on your system:
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR!     node installer/driverInstall.js
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! You can get their info via:
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR!     npm owner ls ibm_db
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! There is likely additional logging output above.
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! System Linux 3.13.0-39-generic
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! command "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/staged/app/.npmrc"
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! cwd /tmp/staged/app
2015-07-31T14:43:03.22+0100 [STG/0]      OUT        npm ERR! node -v v0.10.40
2015-07-31T14:43:03.23+0100 [STG/0]      OUT        npm ERR! npm -v 1.4.28
2015-07-31T14:43:03.23+0100 [STG/0]      OUT        npm ERR! code ELIFECYCLE
2015-07-31T14:43:03.36+0100 [STG/0]      OUT        npm ERR! not ok code 0
2015-07-31T14:43:03.40+0100 [STG/0]      OUT -----> Build failed
2015-07-31T14:43:03.42+0100 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2015-07-31T14:43:03.42+0100 [STG/0]      ERR
2015-07-31T14:43:03.67+0100 [API/5]      ERR encountered error: App staging failed in the buildpack compile phase
```

**Comment by mtp401** [comment] 2015-07-31 15:02
I hit this this morning. The problem is that ibm_db's package.json specifies a dependency on 'nan' as '*'. The 'nan' module was updated last night from 1.8.x to 2.0.0 and it seems the new 'nan' headers aren't compatible. I've submitted [a pull request](https://github.com/ibmdb/node-ibm_db/pull/44) for a temporary fix.

**Comment by bimalkjha** [comment] 2015-08-01 07:54
Merged the pull request.

**Closed by bimalkjha** 2015-08-01 07:54 UTC

**Comment by aninoy** [comment] 2015-08-03 21:50
I'm still hitting this error even after the temporary fix. How can I integrate the latest fix into my application on Bluemix?

**Comment by bimalkjha** [comment] 2015-08-05 15:52
Check now. The issue should be fixed.

**Comment by knolleary** [comment] 2015-08-05 16:52
Can confirm the module now installs properly on bluemix. Thanks.

**Comment by aninoy** [comment] 2015-08-05 19:14
Yes, it has been fixed. Thanks!

**Comment by icosensehpb** [comment] 2015-09-10 09:28
I'm having the exact same issue today when following the initial steps under "Start Coding with Node-RED" on Bluemix:

Can anybody tell me how to fix this?

 npm ERR! Failed at the ibm_db@0.0.14 install script.
       npm ERR! This is most likely a problem with the ibm_db package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node installer/driverInstall.js
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls ibm_db
       npm ERR! There is likely additional logging output above.
       npm ERR! System Linux 3.19.0-25-generic
       npm ERR! command "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/staged/app/.npmrc"
       npm ERR! cwd /tmp/staged/app
       npm ERR! node -v v0.10.40
       npm ERR! npm -v 1.4.28
       npm ERR! code ELIFECYCLE
       npm ERR! not ok code 0
-----> Build failed
       Your build failed!
       Some possible problems:
       - This version of npm (1.4.28) has several known issues - consider upgrading to the latest release (2.14.2)
         http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
Staging failed: Buildpack compilation step failed

**Comment by icosensehpb** [comment] 2015-09-10 14:14
Nevermind, the issue seems to have been fixed now. I waited a few hours and now it worked!
