### ISSUE TITLE
Getting wrong results of Date format

### ISSUE THREAD

**Issue by itdxsd** [ibmdb/node-ibm_db#647] opened 2020-05-03 05:02 UTC
![image](https://user-images.githubusercontent.com/23701488/80899027-87421d80-8d3d-11ea-8949-df341db65f07.png)

date format from db2 yyyy/mm/dd
executeQuery.
node:  v10.16.3
ibm_db: 2.6.4
windows 10 64

Any help on how to fix this , Thanks in advance.

**Comment by bimalkjha** [comment] 2020-05-04 06:59
@itdxsd Could you please share a test program to quickly reproduce it? Also, how you verified that ibm server returns date as '2020-04-08'?
You can update database connection string in `..\ibm_db\test\config.testConnectionStrings.json` and execute `test\test-all-data-types.js` script to verify the inserted Date and selected Date type values are in same format. You may modify this test file to reproduce your issue and share here. Thanks.

**Comment by itdxsd** [comment] 2020-05-04 10:44
@bimaljha Thanks for the reply
Screenshots 
![image](https://user-images.githubusercontent.com/23701488/80958183-2c8cec80-8e37-11ea-921b-c1b1fefe0c81.png)

The issue was when calling a Stored procedure.

**Comment by bimalkjha** [comment] 2020-05-04 20:49
@itdxsd Ok. I'll check using the SP call. Meanwhile it would be good if you can share some simple script to repro it. That would save my time and help to quickly identify the root cause. Thanks.

**Comment by bimalkjha** [comment] 2020-07-06 20:13
@itdxsd I tried to reproduce the issue using a test program and I am unable to reproduce the issue. My test program returns correct result of date data from SP as below:
```
C:\nodework\master>node sp-date.js
Result for Sync call of proc4 ==>
[ '2020-07-06', [ { C1: 5, C2: '2020-04-22' } ] ]
Result for Async call of proc4 ==>
[ '2020-07-06', [ { C1: 5, C2: '2020-04-22' } ] ]
done.

C:\nodework\master>
```
I have attached my test file sp-date.js too. You can run it against your server after updating the connection string and share the result here. You can modify this test file to reproduce your problem and share back. Thanks.

[sp-date.txt](https://github.com/ibmdb/node-ibm_db/files/4881034/sp-date.txt)

**Comment by itdxsd** [comment] 2020-07-10 01:26
@bimaljha thanks for the reply, this the result
screenshots
![image](https://user-images.githubusercontent.com/23701488/87106145-59261000-c28f-11ea-8114-f80854fbc0f8.png)

**Comment by bimalkjha** [comment] 2020-07-14 10:40
@itdxsd If you see my last update, I am getting the date value in correct format. I have also update test file [test-sp-resultset.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-resultset.js) to test this scenario. 
It seems your server has something configured to return date in `yyyy-dd-mm` format, but I do not see any such date format supported by Db2 server in [documentation](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.nls.doc/doc/r0004572.html).

I would suggest to add `DateTimeStringFormat =1` in connection string to get date in `yyyy-mm-dd` format as documented [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0011525.html). It still it do not work for you after using `DateTimeStringFormat =1` in connection string, then I would suggest collect db2 traces for your test file using below steps:
```
cd ...ibm_db\test
trace <absolute_path_of_your_test_file>
```
It will generate many 1.* files. Zip all 1.* files and send to bjha@rocketsoftware.com. I'll have a look into trace files to find the root cause. Thanks.

**Comment by bimalkjha** [comment] 2020-07-22 12:42
@itdxsd Please let me know if you are still facing this issue. If not, can we close it? Thanks.

**Comment by itdxsd** [comment] 2020-07-23 01:35
@bimaljha thanks, but 'trace' is not recognized as an internal or external command,

**Comment by bimalkjha** [comment] 2020-07-23 17:57
@itdxsd You can see `ibm_db\test\trace` in `ibm_db@2.7.0` only. Since you are using ibm_db version 2.6.4, you can find `ibm_db\installer\testODBCConnection.bat` script and replace the `db2cli validate` command of line number 16 with `node <full_path_of_test_file>`. Then open windows command prompt in Administrator mode and execute `testODBCConnection.bat` script to run the repro and generate trace files. Thanks.

**Comment by bimalkjha** [comment] 2020-08-09 20:25
Closing the issue now. We can reopen it if you have have the trace files for investigation. You can attach generated trace files as a zip file here. Thanks.

**Closed by bimalkjha** 2020-08-09 20:25 UTC
