### ISSUE TITLE
Sporadic issue with transaction commit

### ISSUE THREAD

**Issue by meesun** [ibmdb/node-ibm_db#659] opened 2020-06-11 06:33 UTC
If there are multiple updates within a transaction,  sometimes certain updates are not reflected in the database, and this occurs sporadically. The issue doesn't occur every time and there is no specific pattern or instance.

**Comment by bimalkjha** [comment] 2020-06-15 14:24
@meesun If there is no specific pattern or instance, then its very difficult to identify the root cause. But, in most of the cases we found that such issues occurs due the application logic and the asynchronous behavior of node.js apis. Please verify application code to make sure, transaction always get committed once all updates are done. To rule out the async considerations, you may switch to corresponding sync apis and verify. Thanks.

**Closed** 2020-07-02 13:34 UTC
