### ISSUE TITLE
Error: Could not load the bindings file

### ISSUE THREAD

**Issue by ahmedalhulaibi** [ibmdb/node-ibm_db#272] opened 2017-05-29 19:17 UTC
Hi,

I installed the package successfully and when running the the code below:

`var ibmdb = require('ibm_db')();`

This error is returned:

```
`App threw an error during load
Error: Could not locate the bindings file. Tried:
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\buil
d\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\buil
d\Debug\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\buil
d\Release\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\out\
Debug\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\Debu
g\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\out\
Release\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\Rele
ase\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\buil
d\default\odbc_bindings.node
 ΓåÆ C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\comp
iled\7.4.0\win32\x64\odbc_bindings.node
    at bindings (C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules
\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\s4084934\Documents\ElectronProjects\MDMUI\no
de_modules\ibm_db\lib\odbc.js:27:31)
    at Object.<anonymous> (C:\Users\s4084934\Documents\ElectronProjects\MDMUI\no
de_modules\ibm_db\lib\odbc.js:1770:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)`
```

However, I can see in my folders that the file exists in

`C:\Users\s4084934\Documents\ElectronProjects\MDMUI\node_modules\ibm_db\build\Release\odbc_bindings.node`

**Comment by FMGordillo** [comment] 2017-05-29 20:53
Have you tried like this? `var ibmdb = require('ibm_db');` ?

**Comment by ahmedalhulaibi** [comment] 2017-05-29 21:19
Yes same error

**Comment by rhtpandeyIN** [comment] 2017-05-30 08:57
Hi @ahmedalhulaibi ,
 could you please tell us which node version you are using and platform also.

**Comment by ahmedalhulaibi** [comment] 2017-05-30 12:36
Windows 7 64-bit
Tried with Node 7.10.0 as well as 6.10.3

**Comment by rhtpandeyIN** [comment] 2017-05-31 17:08
I think you are using ibm_db inside your electron project right? it seems there is some issue using with electron. (what we have seen is electron rebuilds the supporting packages too, - when you build the project itself, in that case ibm_db is not building properly, and we are looking into it). if this is not your case then one more thing could happen, I think electron IDE by default uses its own nodejs versions irrespective of system version, so could you please verify it once.

**Comment by ahmedalhulaibi** [comment] 2017-05-31 17:57
Hi @rhtpandeyIN you are right it is Electron. Just tried it without electron and it worked. Is there any way to get around this issue, to prevent Electron from rebuilding ibm_db specifically?

**Comment by rhtpandeyIN** [comment] 2017-05-31 18:19
Hi @ahmedalhulaibi , I am trying to figure out this issue, as I am not expert of electron and other priority tasks also is in pipeline things taking time. as this is second time we are getting feedback about electron issue, I will try to resolve it fast.

Thanks for your time and effort, we appreciate your feedback and support.

**Comment by rhtpandeyIN** [comment] 2017-06-08 09:16
Hi @ahmedalhulaibi Please try to install with the latest code. Pull request #278 addressed above issue. Please verify once.
use : `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` command to install.

**Comment by ahmedalhulaibi** [comment] 2017-06-08 20:45
Hi @rhtpandeyIN Still experienced the same error, odbc_bindings.node file exists in the same place as well. Console logged that it was successfully built, which appears to be something added in #278 

`buildReleaseodbc_bindings.node installed successfully.`

**Comment by rhtpandeyIN** [comment] 2017-06-09 06:15
Could you please tell me the steps for reproducing this error, because I got the same error when I tried but with the new code it got resolved for me.

**Comment by rhtpandeyIN** [comment] 2017-06-09 06:52
Hi @ahmedalhulaibi , this problem is really bigger than what I thought it could be.
I investigated and found that this is the problem with "electron" not with a particular module, because many other modules facing the same problem when used with "electron".

Reference :
https://github.com/libxmljs/libxmljs/issues/253
https://github.com/JustinTulloss/zeromq.node/issues/541
https://github.com/zeromq/zeromq.js/issues/2
https://github.com/nteract/nteract/issues/831
https://github.com/zeromq/zeromq.js#rebuilding-for-electron
https://github.com/realm/realm-js/issues/521

There can be many more, The latest commit is resolving the "build.zip" missing error #243 , but not the one you opened. 
Now as you can see too, finding exact solution would be tough, still I am looking into it. If you find something please update us too.

Thanks.

**Comment by ahmedalhulaibi** [comment] 2017-06-09 16:01
Hi @rhtpandeyIN I've created a repo with this error [electron-ibm_db-sample](https://github.com/ahmedalhulaibi/electron-ibm_db-sample)

Based on the information in the other issues, one would have to rebuild ibm_db against electron headers. Prebuild could ease the process https://github.com/mafintosh/prebuild

**Comment by rhtpandeyIN** [comment] 2017-06-16 05:35
Hi @ahmedalhulaibi , well I tried to repro using your given repository, but I am getting an error due to some other reason : I mean "npm install" itself failing at first time due to below missing script:
`
> install-app-deps

'install-app-deps' is not recognized as an internal or external command,
operable program or batch file.
`

I think you missed to upload this script into project or something like that.

Well we really appreciate your time and efforts, thanks for your support.
I will try to rebuild against electron headers, let see where it goes. :)

**Comment by ahmedalhulaibi** [comment] 2017-06-16 18:15
Hi @rhtpandeyIN not sure, it seemed to work on my co-worker's PC. Thanks anyways, please keep us posted.

**Comment by bimalkjha** [comment] 2017-08-30 14:13
@ahmedalhulaibi If it is working fine on your co-worker's PC and not on your PC, then it should be environment related issue. Are you still facing this problem with latest ibm_db@2.1.0?

**Comment by bimalkjha** [comment] 2017-09-17 19:23
Install ibm_db@2.2.0 and verify. Closing the issue now. Thanks.

**Closed by bimalkjha** 2017-09-17 19:23 UTC
