### ISSUE TITLE
Not all error messages are being returned or logged

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#253] opened 2017-04-18 11:48 UTC
node 7.9
ibm_db 2.0

For debugging purposes i ran some queries using standard syntax
```
conn.query('select 1 from sysibm.sysdummy1', function (err, data) {
    if (err) console.log(err);
    else console.log(data);
  });
```
this sql 
sql = `select 1 from sysibm.sysdummy1 WHERE date ='2017-04-17T22:00:00.000Z'`;

produces 
```
{ Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "DATE" is not valid in the context where it is used.  SQLSTATE=42703

   errors: [],
   error: '[node-ibm_db] SQL_ERROR',
   message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "DATE" is not valid in the context where it is used.  SQLSTATE=42703\n',
   state: '42S22' }
```
BUT this sql 
sql = `select 1 from sysibm.sysdummy1 WHERE CURRENT date ='2017-04-17T22:00:00.000Z'`;

should return 
![image](https://cloud.githubusercontent.com/assets/3482445/25129150/18570d02-243d-11e7-91c7-ce4652d756af.png)

but it returns 
```
{ errors: [] }
```

why wouldn't it return any error message 
thanks

**Comment by rhtpandeyIN** [comment] 2017-04-20 08:20
Hi @huineng , I am afraid to say that I am confused here with your description, at first you said :
This 
'''
sql = select 1 from sysibm.sysdummy1 WHERE date ='2017-04-17T22:00:00.000Z';
'''

produces
'''
{ Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "DATE" is not valid in the context where it is used.  SQLSTATE=42703

   errors: [],
   error: '[node-ibm_db] SQL_ERROR',
   message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "DATE" is not valid in the context where it is used.  SQLSTATE=42703\n',
   state: '42S22' }
'''

and after that you said:
The same Sql
'''
sql = select 1 from sysibm.sysdummy1 WHERE CURRENT date ='2017-04-17T22:00:00.000Z';
'''

Returning 
'''
{ errors: [] }
'''

As you can see both are ambiguous, I want to know which one is ibm_db is producing after running above sql query.

**Comment by rhtpandeyIN** [comment] 2017-04-20 08:25
@huineng Got your point, I am looking into this issue. thanks

**Comment by rhtpandeyIN** [comment] 2017-04-26 12:20
Hi @huineng ,

For me it is giving proper error message with error code.

Following is my test case and output for that :
```
conn.querySync("create table testTable_5 (empId int, value BLOB)");
  conn.query('select 1 from testTable_5 Where CURRENT date ="2017-04-17T22:00:00.000Z"', function (err, data) {
    
	if (err) { console.log(err); }
    else { console.log(data); }
  });
  ```
`output:`
```
conn.querySync("create table testTable_5 (empId int, value BLOB)");
  conn.query('select 1 from testTable_5 Where CURRENT date ="2017-04-17T22:00:00.000Z"', function (err, data) {
    
	if (err) { console.log(err); }
    else { console.log(data); }
  });
  ```

and for your first query following is the test case and output:
```
conn.querySync("create table testTable_5 (empId int, value BLOB)");
  conn.query('select 1 from testTable_5 WHERE date ="2017-04-17T22:00:00.000Z"', function (err, data) {
    
	if (err) { console.log(err); }
    else { console.log(data); }
  });
```
`output:`
```
conn.querySync("create table testTable_5 (empId int, value BLOB)");
  conn.query('select 1 from testTable_5 WHERE date ="2017-04-17T22:00:00.000Z"', function (err, data) {
    
	if (err) { console.log(err); }
    else { console.log(data); }
  });
```

Thanks

**Comment by huineng** [comment] 2017-04-26 16:10
Thanks. That's even more weird. You get a SQL0206N 42703  which is a missing column name error even for current date 

my error was on the string representatiin so maybe test with an invalid date string to get the error 22007

**Comment by rhtpandeyIN** [comment] 2017-04-27 12:03
well as you can see my create table statement, there is no "date" name column specified in that, 
`conn.querySync("create table testTable_5 (empId int, value BLOB)");`
Hence when I am trying to select a date column from that table -
`select 1 from testTable_5 WHERE date ="2017-04-17T22:00:00.000Z"`
Then the SQLCODE: SQL0206N and SQLSTATE=42703 is the expecting error. (Cause : For a SELECT or DELETE statement, the specified column is not a column of any of the tables or views identified in a FROM clause in the statement.)

and for the second query :
`select 1 from testTable_5 Where CURRENT date ="2017-04-17T22:00:00.000Z"`
I think this is more a date format error.  because error message clearly indicating date format is not valid
in the context where it is used. 

And one more thing, from where you get this error (22007), I mean from node-ibm_db and DB2 or from different application and database?

**Comment by huineng** [comment] 2017-04-30 17:33
i found this on the node-odbc which might be related
https://github.com/w1nk/node-odbc/issues/64

looks maybe like an issue with the driver

also SQL0206N and SQLSTATE=42703 is not the error you should see, if you run this in any client like sqldb or dbeaver you get there real error 

![image](https://cloud.githubusercontent.com/assets/3482445/25566566/9a9b5d66-2ddb-11e7-893a-86f65698fe5e.png)

and therefore you should see this error
https://www.ibm.com/support/knowledgecenter/en/SSEPEK_10.0.0/codes/src/tpc/n180.html

**Comment by rhtpandeyIN** [comment] 2017-05-02 11:45
Thanks @huineng , you are right, I think there is some problem while displaying the correct error message. 
I double checked with DB2 client and I got following error message for the invalid datetime string:

```
db2 select * from pari where CURRENT date = '2017-04-17T22:00:00.000Z'
```

`output :`
```
SQL0180N  The syntax of the string representation of a datetime value is
incorrect.  SQLSTATE=22007
```
I will check this issue, Thanks again for your observation.

**Comment by rhtpandeyIN** [comment] 2017-05-02 12:02
Following is the reproducing scenario for the condition where you are getting empty error object.
(in previous case I actually interchanged the "" <double quotation> marks, now I am also getting the empty error object)
```
conn.querySync("create table testTable (stuId int)");
  conn.query("select * from testTable WHERE CURRENT DATE = '2017-04-17T22:00:00.000Z'", function (err, data) {
	if (err) { console.log(err); }
    else { console.log(data); }
  });
```

`output :`
```
{ errors: [] }
```

**Comment by huineng** [comment] 2017-05-11 14:47
not sure if this is still being looked at ,but there's another strange error (maybe related or not)

we have this insert

```
INSERT INTO xxx.xxxtable (
	IBMID
	,LONGNAME
	,ADDRESS
	,CITY
	,STATE
	,ZIP
	,INST_URL
	,STATUS
	,SUBMISSION_DATE
	,EIN
	,POBOX
	)
VALUES (
	'05-1005623'
	,'MY FOUNDATION'
	,'8TH & JOHNSON STREET - YOUR HALL 204'
	,'WINANA'
	,'MN'
	,'55987'
	,NULL
	,'P'
	,'2017-05-11-13.14.07.000000'
	,'23-7079002'
	,'PO BOX 2868'
	)
```

the value for the POBOX is fixed varchar(10) so this should generate an error
and it does when using our local sql client
 
![image](https://cloud.githubusercontent.com/assets/3482445/25955331/416688e2-3669-11e7-8da1-a65b747b3eac.png)

But now when it comes to ibm db , we get a different error
```
error: [IBM][CLI Driver] CLI0114E  Datetime field overflow. SQLSTATE=22008
```

just to say that we were looking for hours to solve that problem in our application till we figured out that ibm_db didn't give us the right error message 

thanks

**Comment by rhtpandeyIN** [comment] 2017-05-11 20:00
@huineng , We are currently verifying and validating the code changes for the fix, very soon we will deliver the fix. Thanks for your endurance and coordination :)

**Comment by rhtpandeyIN** [comment] 2017-05-13 18:10
@huineng , could you please paste the create query also, so that I can test for the same data types.

**Comment by rhtpandeyIN** [comment] 2017-05-16 15:01
Hi @huineng , If you are using non-windows platform then could you please once test and confirm the new code changes for the fix.

Please follow below steps: (as changes yet not delivered into main branch, so you need to install new code from my forked branch, after confirmation we will deliver it into main branch.)

1) npm install git+https://git@github.com/rhtpandeyIN/node-ibm_db.git
2) go to test directory and run "node test-issue253.js"
or you can run your own program to test.

Thanks

**Comment by rhtpandeyIN** [comment] 2017-05-20 15:32
Fix code has been pushed, closing the issue now (but we are still looking for your comments), If you are still facing the same issue after this, please reopen it or comment here. Thanks

**Closed by rhtpandeyIN** 2017-05-20 15:32 UTC
Labels: bug
