### ISSUE TITLE
ibm_db 2.6.1 blob data corrupted

### ISSUE THREAD

**Issue by wnwaynelee** [ibmdb/node-ibm_db#582] opened 2019-10-07 17:13 UTC
Steps to reproduce the problem in 2.6.1
1. edit node_modules\ibm_db\test\config.testConnectionStrings.json to set the db configuration
2. cd node_modules\ibm_db\test
3. node test-blob-insert.js
The output is
----
img1.length = 685239
text.length = 841665
buffer data = 49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35
Lengths after select = 1038449, 841665
buffer after select : 49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35
done
----
Note that the img1.length is 685239 while the Lengths after select is 1038449.  Setting DB2CODEPAGE=1208 according to https://github.com/ibmdb/node-ibm_db/issues/579 does not help.
 
With 2.5.3, the output is
----
img1.length = 685239
text.length = 841665
buffer data = 49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35
Lengths after select = 685239, 841665
buffer after select : 49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35
done
----
Note that the img1.length is identical to the Lengths after select.

**Comment by bimalkjha** [comment] 2019-10-17 07:42
@wnwaynelee This test case is working fine for me on Windows, Linux and Macos. I am  unable to reproduce it. Could you please provide little bit more detail to reproduce it like node.js version, OS name, have installed any db2 client or server in the system, your db2 server is local or remote etc. Thanks.

**Comment by wnwaynelee** [comment] 2019-10-17 11:51
@bimalkjha My node.js is v10.16.3 running on Windows 10 Enterprise 1903 build 18362.295.  There is no db2 client installed on Windows.  Node.js is using the prebuild binary from ibm_db.  My db2 is v11.5.0.0 on Docker 19.03.2 on Ubuntu 18.04.3 LTS.  Thanks.

**Comment by wnwaynelee** [comment] 2019-10-18 14:26
@bimalkjha To rule out that this is an OS or node version issue, I tried
node.js v12.9.1 running on Windows 10 Enterprise 1903 build 18362.295
node.js v10.16.3 running on Ubuntu 18.04.3 LTS
The results are the same, ibm_db 2.5.3 works and 2.6.1 doesn't.
Thanks.

**Comment by bimalkjha** [comment] 2019-10-21 15:22
@wnwaynelee Thanks for sharing the info. I am able to reproduce the issue. I am curious to know why the assert at line https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-insert.js#L87 do not fail? Because of this non working assert, test case was passing in batch run.
Thanks for reporting the issue. We'll fix it soon and update you.

**Comment by wnwaynelee** [comment] 2019-10-21 17:05
@bimalkjha The tests should be done using assert.equal
https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message
or assert.strictEqual
https://nodejs.org/api/assert.html#assert_assert_strictequal_actual_expected_message
not assert
https://nodejs.org/api/assert.html#assert_assert_value_message
Thanks.

**Comment by bimalkjha** [comment] 2019-10-21 17:28
Looks the issue is due to copying of binary data in utf8string by https://github.com/ibmdb/node-ibm_db/blob/master/src/odbc.cpp#L987. Conversion of binary to utf8 causes expansion of data and getting corrupted. 
@bnoordhuis Any idea how to read binary data from js object to c++ here and get its length? Thanks.

**Comment by bnoordhuis** [comment] 2019-10-22 12:15
@bimalkjha Nan only has Utf8String because old versions of Node.js only support UTF-8. If you're okay with using the V8 API directly, you can use `v8::String::WriteOneByte()`:

https://github.com/nodejs/node/blob/31217a8e88d7414579284267f8715112bf8a0fc6/deps/v8/include/v8.h#L2812-L2814

Caveat emptor: it doesn't take an `Isolate*` as its argument in Node.js v8.x so you'll need to `#include "node_version.h"` and then guard on `NODE_MAJOR_VERSION > 8`.

**Comment by bimalkjha** [comment] 2019-10-23 13:04
@wnwaynelee I have delivered the fix for this issue on github. It would be part of next release.
You may install the latest code using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` and verify the fix. Thanks.

**Closed by bimalkjha** 2019-10-23 13:04 UTC
