### ISSUE TITLE
Random driver hanging on getting connection from pool

### ISSUE THREAD

**Issue by ardor91** [ibmdb/node-ibm_db#611] opened 2020-02-12 08:10 UTC
Last week we are having another similar issue, but I'm not sure if it is related to SQL30081N code. Let me describe this:
Because of our DB structure, we are having Deadlock issues very rare (we are investigating this). After first deadlock issue, all connections to DB totally blocked. One way to solve it (except db2stop/restart) is to execute call sysproc.admin_cmd('force application all'). It helps, but after this DB2 driver stopping work without any response code. I did a little investigation and noticed that it hangs on getting new connection from pool:
 ```
console.log("Getting connection");
        this.pool.open(this.config.sslConnectionString, (err, db) => {
            console.log("resolving");
            if(err) {
                console.log("Open pool connection error: ", err);
                reject(err);
            }
```
No more logs after line "Getting connection". Then after about 1 minute I have 500 Timeout response.
We have another app written on PHP that uses same db, and it works good after forcing all connections.
Thanks!

**Comment by bimalkjha** [comment] 2020-02-12 12:04
@ardor91 please share are you using maxpoolsize parameter or not.
After SQL30081N  error, all connections from pool get removed. So, when you call pool.open() after SQL30081N  error, it will try to get actual connection from server as pool is empty. This wait or 1 minute is by the server as client is waiting for response from server for the requested connection for 60 seconds. After 60 seconds, client throws timeout error as it is unable to get connection in 60 seconds. This 60 seconds of connection timeout is set [here](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L1827) in ibm_db. If you want, you can edit odbc.js file and change this connection timeout.
If you would like to know why server is not giving any connection to client in 60 seconds, you need to work with the Db2 Server support team using a support ticket. You may need to collect db2trace on server and share those file with support for investigation. ibm_db is requesting a fresh connection from server, but server do not respond and hence timeout error. Thanks.

**Comment by bimalkjha** [comment] 2020-02-12 12:06
ConnectTimeOut setting is documented [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0021533.html) is db2 knowledge center. Thanks.

**Comment by ardor91** [comment] 2020-02-13 07:19
Hi, thanks for response.
Yes, I'm using maxConnectionPoolSize:
```
this.pool = new Pool(
            {
                //connectTimeout: 30,
                //idleTimeout: 120,
                autoCleanIdle: true,
                maxPoolSize: 100,
            });
```
I don't think, that this is an issue with DB2 server. As I said earlier, we have two applications PHP and Node which intensively working together. When my Node loses connection (as described in issue), PHP is able to restore connection without any wait time.

This issue is quite rare, but if it appears - one way to make Node working again is redeploy app manually. Could you suggest any way to fully reinitialize db2 driver?

**Comment by bimalkjha** [comment] 2020-02-14 09:23
@ardor91 One way to reinitialize the driver would be to kill the running application process and run again using npm start.
To collect more info about the issue, I would suggest to add a line `debug(true);` in application code at start as in `ibm_db\test\test-max-pool-size.js` file and then run it.
Update connection string in `node-ibm_db/installer/testODBCConnection.sh` file for `db2cli validate` command. When the hand issue reproduce, the the testODBCConnection.sh script to collect traces and share the generated file for investigation. Thanks.

**Comment by bimalkjha** [comment] 2020-03-11 18:36
Closing the issue as did not received any response in past 26 days. Thanks.

**Closed by bimalkjha** 2020-03-11 18:36 UTC

**Comment by dlholt** [comment] 2020-05-20 18:49
@bimalkjha it seems my team is experiencing the same thing as @ardor91. The next time we see the hanging behavior, I will do what you described in https://github.com/ibmdb/node-ibm_db/issues/611#issuecomment-586172836 and report back

**Comment by dlholt** [comment] 2020-05-22 19:31
@bimalkjha it turns out our (non-HA) managed Db2 instance was undergoing maintenance. You can disregard my above comment
