### ISSUE TITLE
All binary that larger than 0x80 forcefully transform into 0xFD

### ISSUE THREAD

**Issue by k3nNyJP** [ibmdb/node-ibm_db#379] opened 2018-04-06 07:02 UTC
Hi,

All binary that larger than 0x80 transform into 0xFD when insert with query parameters.
I'm using node.js v8.9.4 and ibm_db@2.2.1

repro
```javascript
const ibm_db = require("ibm_db");

ibm_db.open("<connstr>", (err, db) => {
  if (err) {
    console.log("open failed", err);
    return;
  }

  db.query("CREATE TABLE binary_test ( data BINARY(4) );", (err, res) => {
    if (err) {
      console.log("create failed", err);
      return;
    }

    const buf = Buffer.from('10204080', "hex");
    console.log(buf);

    db.query("INSERT INTO binary_test (data) values (?);",
      [{ CType: "BINARY", DataType: "BINARY", Data: buf }], (err, res) => {
        if (err) {
          console.log("insert failed", err);
          return;
        }

        console.log("insert result", res);

        db.query("SELECT * FROM binary_test;", (err, res) => {
          if (err) {
            console.log("select failed", err);
            return;
          }

          console.log("select result", res);

          db.query("DROP TABLE binary_test;", (err, res) => {
            if (err) {
              console.log("drop failed", err);
              return;
            }

            console.log("drop result", res);
            db.closeSync();
          });
        });
      });
  });
});
```

result
```text
<Buffer 10 20 40 80>
insert result []
select result [ { DATA: '102040FD' } ]
drop result []
```

I want to get '10204080' but returns '102040FD'.

**Comment by rhtpandeyIN** [comment] 2018-04-11 14:09
Hi @k3nNyJP , I think the problem was in column data type value. I tried to run your example with some tweaks, now I am able to insert the exact data also getting the same. 
It was not only converting "10203080" to "102030FD" but, it was converting all values greater than "80" to "FD". Simply it was the usage error.

Please try to run below code sample once, hope it will help you.

`
var fs = require('fs'),
ibmdb = require('./node-ibm_db');
var cn="DATABASE=sample;HOSTNAME=host;UID=uerid;PWD=password;PORT=50000;PROTOCOL=TCPIP";

ibmdb.open(cn, (err, db) => {
  if (err) {
    console.log("open failed", err);
    return;
  }

  db.query("CREATE TABLE binary_test ( data BLOB(1M) );", (err, res) => {
    if (err) {
      console.log("create failed", err);
      db.query("DROP TABLE binary_test;", (err, res) => {
        if (err) {
          console.log("drop failed", err);
          return;
        }
        console.log("drop result", res);
        db.closeSync();
      });
      return;
    }

    const buf = Buffer.from('10203086', 'binary');
    console.log("buf is:");
    console.log(buf.toString());

    db.query("INSERT INTO binary_test (data) values (?);",
      [{ CType: "BLOB", DataType: "BLOB", Data: buf }], (err, res) => {
        if (err) {
          console.log("insert failed", err);
          return;
        }

        console.log("insert result", res);

        db.query("SELECT * FROM binary_test;", (err, res) => {
          if (err) {
            console.log("select failed", err);
            return;
          }

          console.log("select result", res);

          db.query("DROP TABLE binary_test;", (err, res) => {
            if (err) {
              console.log("drop failed", err);
              return;
            }

            console.log("drop result", res);
            db.closeSync();
          });
        });
      });
  });
});
`

I created "BLOB" field rather than "Binary" and then inserted data as "BLOB" only. but make sure your buffer should encode in "binary" format.

For now closing the issue, if you have further queries please feel free to comment here.

**Closed by rhtpandeyIN** 2018-04-11 14:09 UTC

**Comment by rhtpandeyIN** [comment] 2018-04-11 14:41
Duplicate of : Issue #308
