### ISSUE TITLE
nodejs stops to work when inserting .docx to BLOB column

### ISSUE THREAD

**Issue by VitKlus** [ibmdb/node-ibm_db#357] opened 2018-01-19 07:13 UTC
I am trying to insert files to the DB2 database BLOB Column inside nodejs:
`
> var fileObj = {ParamType: 1, DataType: "BLOB", "Data": file.content};
> console.log('Inserting...');
> conn.query('INSERT INTO ATTACHMENTS (CONTENT, TYPE, FILENAME, FILESIZE) VALUES (?, ?, ?, ?)',
> [fileObj, file.file.type, file.file.name, file.file.size], function(err) {
> console.log('Inserted...');
> if (err) {
>     console.log('Insert file error:');
>     console.log(err);
> } 
`
file.content is taken on the frontend using FileReader().
All tested types (text/plain, image/jpeg, application/msword) are inserted correctly.
But if to try to insert **.docx** document with type **application/vnd.openxmlformats-officedocument.wordprocessingml.document** the record itself is successfully inserted to the DB but nodejs server stops to work with no message at all. No any error or message 'Inserted...' appears.
And this happens only with .docx data.
Tried on Nodejs versions 6.11.3 and 8.9.4.

**Comment by bimalkjha** [comment] 2018-04-12 07:12
@VitKlus Could you share your .docx file so that we can reproduce the issue using same file and look for root cause? Thanks.

**Comment by VitKlus** [comment] 2018-04-12 07:25
Hi @bimalkjha. Here is the file in the attachment. 
[Some text.docx](https://github.com/ibmdb/node-ibm_db/files/1901765/Some.text.docx)

**Comment by rhtpandeyIN** [comment] 2018-04-12 09:11
Hi @VitKlus ,

I am able to insert and fetch "docx" files from BLOB column. Please refer to the following test example link and attached sample code snippet:

Link : [test-blob-file.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-file.js)

`
    var fs = require('fs'),
    assert = require("assert"),
    ibmdb = require('./node-ibm_db');
    var cn="DATABASE=sample;HOSTNAME=waldevdbcwtst09.dev.rocketsoftware.com;UID=db2admin;PWD=gr8tcode!;PORT=50000;PROTOCOL=TCPIP";

    ibmdb.open(cn, function (err,conn) {
        if (err) { console.log(err); process.exit(-1); }
        try {
            conn.querySync("drop table newtable");
        } catch (e) {};

        try {
            conn.querySync("create table newtable(data BLOB(1M))");
        } catch (e) {};

        var doc = __dirname + '\\data\\some.docx';
        var len1  = fs.statSync(doc)["size"];
        console.log( "doc.length = " + len1);

        conn.prepare("insert into newtable(data) VALUES (?)", function (err, stmt) {
            if (err) {
                console.log(err);
                return conn.closeSync();
            }

            var docData = {ParamType:"FILE", DataType: "BLOB", "Data":doc};
        
            stmt.execute([docData], function (err, result) {
                if( err ) console.log(err);
                else result.closeSync();

                conn.prepare("select * from newtable", function (err, stmt) {
                    if(err) {
                        console.log(err);
                        return conn.closeSync();
                    }

                    stmt.execute([], function(err, result) {
                        if(err) console.log(err);
                        else {
                            data = result.fetchAllSync();
                            fs.writeFileSync('getDoc.docx', data[0].DATA, 'binary');
                        
                            try {
                                conn.querySync("drop table newtable");
                            } catch (e) {};

                            result.closeSync();
                            var size1 = fs.statSync("getDoc.docx")["size"];
                            console.log("Lengths after select = " + size1);
                            assert(len1, size1);
                        }
                    });
                });
            });
        });
    });
`

Closing the issue for now, If you have further queries please feel free to comment here. Thanks.

**Closed by rhtpandeyIN** 2018-04-12 09:11 UTC
