### ISSUE TITLE
BigInt columns

### ISSUE THREAD

**Issue by gialf** [ibmdb/node-ibm_db#816] opened 2022-01-11 15:38 UTC
Starting from version 2.7.4 BigInt columns are returned as number ( [see issue #750 ](https://github.com/ibmdb/node-ibm_db/issues/750) ) .

Considering the fact that javascript has a Number.MAX_SAFE_INTEGER constant which represents the maximum safe integer value, if we have a bigint column that contains a value larger than Number.MAX_SAFE_INTEGER, then the returned value could be wrong.

Until ibm_db v2.7.1 BigInt were returned as string so there were non issues.

The following is a snippet that shows the issue:

`console.log('JS Number max SAFE value :'+Number.MAX_SAFE_INTEGER);
//9007199254740991 = Number.MAX_SAFE_INTEGER
let maxSafeInt = Number.MAX_SAFE_INTEGER;
let bigIntValue = 9007199254741993n;

conn.openSync(cn);
conn.querySync('create table mytab (c1 bigint, c2 varchar(20))');
conn.querySync(`insert into mytab values (${maxSafeInt}, 'Max Safe Int'),(${bigIntValue}, 'Big Int Value')`);`

conn.queryResult("select * from mytab", function (err, result) {
  if(err) {
    console.log(err);
    return;
  }
  
  let data;
  while( data = result.fetchSync() )
  {
    console.log('Data Type returned :'+typeof data.C1);  
    console.log(data);
    
  }
}

The result is:

JS Number max SAFE value :9007199254740991
Data Type returned :number
{ C1: 9007199254740991, C2: 'Max Safe Int' }
Data Type returned :number
{ C1: **9007199254741992**, C2: 'Big Int Value' }

The second inserted record ha the bigint value 9007199254741993n for the column C2, but 9007199254741992 is returned.
I've checked that values inserted in the db are correct, but they are not correctly returned

**Comment by bimalkjha** [comment] 2022-01-12 10:24
@gialf The root cause for this change from string to number for big int is the issue #693 . Please check it.
Till version 2.7.1, ibm_db was returning bigint as string as you want now. Issue #693 was opened to return big int as number and not string. So, we changed it in vesion 2.7.2, but it has one bug which got fixed finally in version 2.7.4.
I would suggest you to continue your discussion on issue #693 about it. Thanks.

**Comment by bimalkjha** [comment] 2022-01-12 10:39
@gialf You should look into the problem caused by the string representation of bigint number too. Please check [this comment](https://github.com/ibmdb/node-ibm_db/issues/693#issuecomment-722428312) and suggest how to handle such issues?  Thanks.

**Comment by bimalkjha** [comment] 2022-01-12 10:42
My suggestion is if NodeJS application is using a number greater than Number.MAX_SAFE_INTEGER, then its the problem with the app or they should have some mechanism to handle it. ibm_db just trying to return the same value from Database from where many other clients might be accessing data and they might want actual data which may be bigger than Number.MAX_SAFE_INTEGER. If JS can not handle bigger value than Number.MAX_SAFE_INTEGER, then application should deal with it. My two cents. Thanks.

**Comment by gialf** [comment] 2022-01-12 11:08
Hi @bimalkjha 
the problem is that in case of a bigint value in db which is bigger than Number.MAX_SAFE_INTEGER, a JS  application can't control it because it is directly returned wrong. So how can I control it?
Thanks

**Comment by gialf** [comment] 2022-01-13 10:09
ibm_db is a node.js module so I expect it should correctly manage JS datatypes.
I agree that other numeric types are returned as number, but I think BIGINT db datatype should not be returnd as simple JS number because this can lead to unexpected behavior.
Let me say that for example in JS bigint can be also instantiated with a numeric string..
IMHO In big existing applications, in which one could already have BIGINT cols, it is not reasonable to change al DB cols...
Returnig BIGINT as string instead let the developers have more control avoiding unexpected results..

**Comment by bimalkjha** [comment] 2022-04-25 06:03
Fixing this issue will revert the fix of issue #693. Hence closing it until we have common understanding among users. Thanks.

**Comment by markddrake** [comment] 2022-05-16 19:10
try looking at other drivers (Oracle, Postgres etc). They all offer the option to have number (and date for that matter as string), specified. This allows the developer to choose how to handle this issue. For extra points you could also offer the option to return BIGINT as the the javascript bigint class. What is really bugging me is I dont' seem to be able to program around this by using CAST or BIGINT and explicitly passing strings (VARCHAR) with array binds.

**Comment by bimalkjha** [comment] 2022-06-05 20:17
@markddrake Restored the old behavior by latest push. Now, bigint will be returned as string. Fix will be part of next release. Thanks.

**Closed by bimalkjha** 2022-06-05 20:17 UTC
