### ISSUE TITLE
Pool connection issue: SQL30081N

### ISSUE THREAD

**Issue by sandrodesantis** [ibmdb/node-ibm_db#461] opened 2018-10-02 13:29 UTC
Our application is getting an issue with the db2 connection, but, intermittent way, sometimes
application run during days without issue and other times not.

The issue looks like be something with connection time, someone has an idea how fix it?

APP/PROC/WEB/0 message: '[IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "169.55.227.101". Communication function detecting the error: "send". Protocol specific error code(s): "32", "*", "0". SQLSTATE=08001\n',

Regards,

**Comment by rhtpandeyIN** [comment] 2018-10-02 18:30
Closing the issue, as possible duplicate of issue #460 , please track it there.

**Closed by rhtpandeyIN** 2018-10-02 18:30 UTC
