### ISSUE TITLE
? takes long time

### ISSUE THREAD

**Issue by jay763190097** [ibmdb/node-ibm_db#230] opened 2017-03-07 02:21 UTC
when i use ? in sql strings,it takes nearly 1 minute.
but When I fill the question mark with the corresponding argument, it only takes 2 to 3 seconds.
a:use ?
$ node app.js
=================start 2017-03-07T02:14:02.365Z
++++++++++++++end 2017-03-07T02:14:53.621Z
b:donot use ?
$ node app.js
=================start 2017-03-07T02:18:34.942Z
++++++++++++++end 2017-03-07T02:18:37.889Z
result on win64 platform.

**Comment by bimalkjha** [comment] 2017-03-07 09:00
@jay763190097 Please share your app.js to reproduce the problem and verify. We have a test file [test-basic-test.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-basic-test.js) that uses ? to insert data into a table and it do not show any delay. Can you update connection info in `ibm_db\test\config.testConnectionStrings.json` file and run `node test\config.testConnectionStrings.json` to test it? Thanks.

**Comment by jay763190097** [comment] 2017-03-07 09:43
var a = 'select * \
from ( \
      select \'\'||d.DONORID as "donorId", rtrim(d.NAME) as "name", c.DONATIONID as "serialId", \
             nvl(ce.conclusion, case when rtrim(t.FINALRESULT) is null and c.bcdate < to_date(\'2009-01-01\', \'yyyy-mm-dd\') then 6 else nvl(rtrim(t.FINALRESULT),4) end) as "conclusion" \
      from BIS.DONOR d,BIS.BLOODCOLLECTION c,BIS.TESTFINALRESULTLISTING t,bos.lab_conclusion_exclude ce \
      where (d.citizenid in (?, ?) or (d.CERTIFICATETYPE = \'0\' and d.certificateid in (?, ?))) \
        and d.DONORID = c.DONORID \
        and c.DONATIONID = t.SAMPLEID(+) \
        and (? is null or c.DONATIONID = ?) \
        and c.DONATIONID = ce.serialid(+) \
      order by c.BCDATE desc \
      ) \
where rownum = 1';

var b = 'select * \
from ( \
      select \'\'||d.DONORID as "donorId", rtrim(d.NAME) as "name", c.DONATIONID as "serialId", \
             nvl(ce.conclusion, case when rtrim(t.FINALRESULT) is null and c.bcdate < to_date(\'2009-01-01\', \'yyyy-mm-dd\') then 6 else nvl(rtrim(t.FINALRESULT),4) end) as "conclusion" \
      from BIS.DONOR d,BIS.BLOODCOLLECTION c,BIS.TESTFINALRESULTLISTING t,bos.lab_conclusion_exclude ce \
      where (d.citizenid in (\'330107196906080910\', \'330107196906080910\') or (d.CERTIFICATETYPE = \'0\' and d.certificateid in (\'330107196906080910\',\'330107196906080910\'))) \
        and d.DONORID = c.DONORID \
        and c.DONATIONID = t.SAMPLEID(+) \
        and (\'\' is null or c.DONATIONID = \'\') \
        and c.DONATIONID = ce.serialid(+) \
      order by c.BCDATE desc \
      ) \
where rownum = 1';
db2.getConnection(function(err, connection) {
    if(err) {
        console.log('get db2 connection fail:', err);
    } else {
        connection.prepare(a, function (err, stmt) {
            if (err) {
              console.log(err);
              return connection.closeSync();
            }
            console.log('=================start',new Date());
            // when i use a, it takes nearly one minute
            stmt.execute(['330107196906080910', '330107196906080910', '330107196906080910','330107196906080910','',''], function (err, result) {
            //when i use b, it takes two or three seconds
            //stmt.execute(a, function (err, result) {
                 console.log('++++++++++++++end',new Date())
                  if( err ) console.log(err);  
                  else result.closeSync();
                  //Close the connection
                  connection.close(function(err){});
            });
        });
    }
});

**Comment by bimalkjha** [comment] 2017-03-07 11:26
Please share your ibm_db version in use. If you are not using latest ibm_db@2.0.0, please check with it. Thanks.

**Comment by bimalkjha** [comment] 2017-03-07 11:31
Also, I would suggest to call bindSync and then execute as below and see any difference?
```
stmt.bindSync(['330107196906080910', '330107196906080910', '330107196906080910','330107196906080910','','']);
stmt.execute( function (err, result) {
```
Thanks.

**Comment by jay763190097** [comment] 2017-03-08 02:02
// So I did some tests hope that can improve the way of a,but it doesn't work
```
db2.getConnection(function(err, connection) {
    if(err) {
        console.log('get db2 connection fail:', err);
    } else {
        connection.prepare(a, function (err, stmt) {
            if (err) {
              console.log(err);
              return connection.closeSync();
            }
            console.log('=================start',new Date());
            stmt.execute(['330107196906080910', '330107196906080910', '330107196906080910','330107196906080910','',''], function (err, result) {
                        stmt.execute(b, function (err, result) {
                 console.log('++++++++++++++end',new Date())
                  if( err ) console.log(err);  
                  else result.closeSync();
                  connection.close(function(err){});
            });
        });
    }
});
```

**Comment by jay763190097** [comment] 2017-03-08 02:10
// I tried the way that you taught me,today,but it also takes  half of a minute.
```
db2.getConnection(function(err, connection) {
    if(err) {
        console.log('get db2 connection fail:', err);
    } else {
        connection.prepare(a, function (err, stmt) {
            if (err) {
              console.log(err);
              return connection.closeSync();
            }
            console.log('=================start',new Date());
            stmt.bindSync(['330107196906080910', '330107196906080910', '330107196906080910','330107196906080910','','']);
            stmt.execute([],function (err, result) {
                 console.log('++++++++++++++end',new Date())
                  if( err ) console.log(err);  
                  else result.closeSync();
                  //Close the connection
                  connection.close(function(err){});
            });
        });
    }
});
```

**Comment by jay763190097** [comment] 2017-03-08 02:16
// i alse tried the follow way that took nearly one minute
```
db2.getConnection(function(err, connection) {
    if(err) {
        console.log('get db2 connection fail:', err);
    } else {
        var param1 = {ParamType:"INPUT", DataType:"CHAR", "Data":"330107196906080910"}
        var param2 = {ParamType:"INPUT", DataType:"CHAR", "Data":"330107196906080910"}
        var param3 = {ParamType:"INPUT", DataType:"CHAR", "Data":"330107196906080910"}
        var param4 = {ParamType:"INPUT", DataType:"CHAR", "Data":"330107196906080910"}
        var param5 = {ParamType:"INPUT", DataType:"CHAR", "Data":""}
        var param6 = {ParamType:"INPUT", DataType:"CHAR", "Data":""}
        console.log('=================start',new Date());
         var result = connection.querySync(a,[param1,param2,param3,param4,param5,param6]);
         console.log('=================end',new Date());
    }
});
```

**Comment by jay763190097** [comment] 2017-03-08 02:17
i'm sure that i use the version 2.0.0

**Comment by bimalkjha** [comment] 2017-03-09 07:08
How many rows are returned by queries? Is it possible to share DDL of tables BIS.DONOR d,BIS.BLOODCOLLECTION c,BIS.TESTFINALRESULTLISTING t,bos.lab_conclusion_exclude ce? 
If you know how to collect ODBC/CLI trace, please collect and mail to bimaljha@in.ibm.com. Thanks.

**Comment by jay763190097** [comment] 2017-03-10 09:07
only two rows.

**Comment by jay763190097** [comment] 2017-03-13 02:22
i guess you could try insert the placeholders in the SQL string or without placeholders,then compare the time they spend.

**Comment by bimalkjha** [comment] 2017-03-13 09:50
@jay763190097 The test case [test-blocking-issue210.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blocking-issue210.js) does exactly same thing as you described. But we don't see the dynamic sql call is taking more time than static call. Even we see the query using parameter marker(?) is faster than query without parameter marker.

Please take latest code from github using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git`, update connection information in file `ibm_db/test/config.testConnectionStrings.json` and run command `node test/test-blocking-issue210.js` to see the time consumed by queries.

Please modify the test file test-blocking-issue210.js to reproduce your issue and share the updated file. Thanks.

**Comment by jay763190097** [comment] 2017-03-14 04:41
i test it and get the following result.
``$ node test-blocking-issue210.js
0.276 ::  Started pool.open, populate a table MTAB1 of 40K rows.
0.986 ::  Inserted rows in mtab1 =  41810
node-ibm_db logs enabled.
1.047 ::  Opening connection #1
1.048 ::  Connection 1 opened. Start execution of Query1
1.049 ::  odbc.js:query() => Entry
1.05 ::  odbc.js:query() =>  select * from mtab1
1.052 ::  Connection 2 opened. Start execution of Query2
1.052 ::  odbc.js:query() => Entry
1.053 ::  odbc.js:query() =>  select c1, c2 from mtab1
1.053 ::   **** All lines of test file executed, waiting for callback functions
to finish.
2.303 ::  odbc.js:query() => Done.
2.304 ::  Total execution time for Query2 =  1 sec.
3.316 ::  odbc.js:query() => Done.
3.316 ::  Total execution time for Query1 =  2 sec.
3.316 ::  odbc.js:querySync() =>  insert into mtab1 values ('330107196906080910'
, '330107196906080910'), ('330107196906080910', '330107196906080910'), ('3301071
96906080910', '')
3.33 ::  odbc.js:query() => Entry
3.33 ::  odbc.js:query() =>  select c1, c2 from mtab1 where (c1 in (?, ?) or c2
in (?, ?) and (? is null or c2 = ?))
3.393 ::  odbc.js:query() => Done.
[ { C1: '330107196906080910', C2: '330107196906080910' },
  { C1: '330107196906080910', C2: '330107196906080910' },
  { C1: '330107196906080910', C2: null } ]
3.422 ::  Total execution time for Query3 =  0.092 sec. **** <<==
3.422 ::  odbc.js:query() => Entry
3.422 ::  odbc.js:query() =>  select c1, c2 from mtab1 where (c1 in ('3301071969
06080910', '330107196906080910') or c2 in ('330107196906080910', '33010719690608
0910') and ('' is null or c2 = ''))
3.464 ::  odbc.js:query() => Done.
[ { C1: '330107196906080910', C2: '330107196906080910' },
  { C1: '330107196906080910', C2: '330107196906080910' },
  { C1: '330107196906080910', C2: null } ]
3.466 ::  Total execution time for Query4 =  0.044 sec. **** <<==
3.466 ::  odbc.js:querySync() =>  drop table mtab1
node-ibm_db logs disabled.

**Comment by jay763190097** [comment] 2017-03-14 05:07
//i updated some codes,then did a test
```
var common = require("./common")
	, ibmdb = require("../")
	, pool = new ibmdb.Pool()
	, connectionString = common.connectionString
    , assert = require("assert")
	, connections = []
	, connectCount = 2;

var startTime1, startTime2, totalTime1, totalTime2, dropTable = 0;
var elapsedTime = ibmdb.getElapsedTime;
var ret = pool.init(connectCount, connectionString); 
if(typeof ret === 'object') assert.equal(ret.message, undefined);

//moment().format("YYYY-MM-DD HH:mm:ss.SSS"));
console.log(elapsedTime(), "Started pool.open, populate a table MTAB1 of 40K rows.");
/*pool.open(connectionString, function( err, conn) {
    try { conn.querySync("drop table mtab1");
          conn.querySync("drop table mtab2"); } catch(e) {};
    conn.querySync("create table mtab1(c1 varchar(30), c2 varchar(20))");
    conn.querySync("create table mtab2(c1 varchar(30), c2 varchar(20))");
    conn.querySync("Insert into mtab1 values ('1', 'bimal'),('2','kumar'),('3', 'jha'), ('4', 'kamal'), ('5', 'ibm')");
    conn.querySync("Insert into mtab1 values ('1', 'bimal'),('2','kumar'),('3', 'jha'), ('4', 'kamal'), ('5', 'ibm')");
    for(var i = 0; i < 9 ; i++) {
      conn.querySync("insert into mtab2 (select * from mtab1)");
      conn.querySync("insert into mtab1 (select * from mtab2)");
      }
    conn.querySync("drop table mtab2");
    console.log(elapsedTime(), "Inserted rows in mtab1 = ", conn.querySync("select count(*) from mtab1")[0]['1']);
    conn.close(function(err){});
});*/

ibmdb.debug(true);
var q1time, q2time;
console.log(elapsedTime(), "Opening connection #1");
pool.open(connectionString, function (err, connection) {
        console.log(elapsedTime(), "Connection 1 opened. Start execution of Query1");
        startTime1 = new Date();
        // connection.query("select * from mtab1", function(err, data) {
        //         if(err) console.log(err);
                totalTime1 = (new Date() - startTime1)/1000;
                q1time = parseInt(totalTime1%60);
                console.log(elapsedTime(), "Total execution time for Query1 = ", q1time, "sec."); 
                dropTable++;
                if(dropTable == 2) {
                  assert.equal(q1time > 10, false);
                  testLongTime(connection);
                }
        // });
});

pool.open(connectionString, function (err, connection) {
        console.log(elapsedTime(), "Connection 2 opened. Start execution of Query2");
        startTime2 = new Date();
        // connection.query("select c1, c2 from mtab1", function(err, data) {
        //         if(err) console.log(err);
                totalTime2 = (new Date() - startTime2)/1000;
                q2time = parseInt(totalTime2%60);
                console.log(elapsedTime(), "Total execution time for Query2 = ", q2time, "sec."); 
                dropTable++;
                if(dropTable == 2) {
                  assert.equal(q2time > 10, false);
                  testLongTime(connection);
                }
        // });
});

// Test case for issue #230
function testLongTime(conn) {
    //conn.querySync("insert into mtab1 values ('330107196906080910', '330107196906080910'), "+
                   //"('330107196906080910', '330107196906080910'), ('330107196906080910', '')");
    var query1 = 'select * \
                    from ( \
                          select \'\'||d.DONORID as "donorId", rtrim(d.NAME) as "name", c.DONATIONID as "serialId", \
                                 nvl(ce.conclusion, case when rtrim(t.FINALRESULT) is null and c.bcdate < to_date(\'2009-01-01\', \'yyyy-mm-dd\') then 6 else nvl(rtrim(t.FINALRESULT),4) end) as "conclusion" \
                          from BIS.DONOR d,BIS.BLOODCOLLECTION c,BIS.TESTFINALRESULTLISTING t,bos.lab_conclusion_exclude ce \
                          where (d.citizenid in (?, ?) or (d.CERTIFICATETYPE = \'0\' and d.certificateid in (?, ?))) \
                            and d.DONORID = c.DONORID \
                            and c.DONATIONID = t.SAMPLEID(+) \
                            and (? is null or c.DONATIONID = ?) \
                            and c.DONATIONID = ce.serialid(+) \
                          order by c.BCDATE desc \
                          ) \
                    where rownum = 1';
    var query2 = 'select * \
                    from ( \
                          select \'\'||d.DONORID as "donorId", rtrim(d.NAME) as "name", c.DONATIONID as "serialId", \
                                 nvl(ce.conclusion, case when rtrim(t.FINALRESULT) is null and c.bcdate < to_date(\'2009-01-01\', \'yyyy-mm-dd\') then 6 else nvl(rtrim(t.FINALRESULT),4) end) as "conclusion" \
                          from BIS.DONOR d,BIS.BLOODCOLLECTION c,BIS.TESTFINALRESULTLISTING t,bos.lab_conclusion_exclude ce \
                          where (d.citizenid in (\'330107196906080910\', \'330107196906080910\') or (d.CERTIFICATETYPE = \'0\' and d.certificateid in (\'330107196906080910\',\'330107196906080910\'))) \
                            and d.DONORID = c.DONORID \
                            and c.DONATIONID = t.SAMPLEID(+) \
                            and (\'\' is null or c.DONATIONID = \'\') \
                            and c.DONATIONID = ce.serialid(+) \
                          order by c.BCDATE desc \
                          ) \
                    where rownum = 1';
    var params = ['330107196906080910', '330107196906080910', '330107196906080910','330107196906080910','',''];
    startTime1 = new Date();
    conn.query(query1, params, function(err, rows) {
        if(err) console.log(err);
        else console.log(rows);
        totalTime1 = (new Date() - startTime1)/1000;
        console.log(elapsedTime(), "Total execution time for Query3 = ", totalTime1, "sec. **** <<==");
        startTime2 = new Date();
        conn.query(query2, function(err, rows) {
            if(err) console.log(err);
            else console.log(rows);
            totalTime2 = (new Date() - startTime2)/1000;
            console.log(elapsedTime(), "Total execution time for Query4 = ", totalTime2, "sec. **** <<==");

            // Clean up
            //conn.querySync("drop table mtab1");
            ibmdb.debug(false);
            pool.close();
        });
    });
}
console.log(elapsedTime(), " **** All lines of test file executed, waiting for callback functions to finish. ");
```

//get the following result
```
$ node test-blocking-issue210.js
0.307 ::  Started pool.open, populate a table MTAB1 of 40K rows.
node-ibm_db logs enabled.
0.314 ::  Opening connection #1
0.315 ::  Connection 1 opened. Start execution of Query1
0.315 ::  Total execution time for Query1 =  0 sec.
0.316 ::  Connection 2 opened. Start execution of Query2
0.316 ::  Total execution time for Query2 =  0 sec.
0.317 ::  odbc.js:query() => Entry
0.318 ::  odbc.js:query() =>  select *                     from (
            select ''||d.DONORID as "donorId", rtrim(d.NAME) as "name", c.DONATI
ONID as "serialId",                                  nvl(ce.conclusion, case whe
n rtrim(t.FINALRESULT) is null and c.bcdate < to_date('2009-01-01', 'yyyy-mm-dd'
) then 6 else nvl(rtrim(t.FINALRESULT),4) end) as "conclusion"
         from BIS.DONOR d,BIS.BLOODCOLLECTION c,BIS.TESTFINALRESULTLISTING t,bos
.lab_conclusion_exclude ce                           where (d.citizenid in (?, ?
) or (d.CERTIFICATETYPE = '0' and d.certificateid in (?, ?)))
          and d.DONORID = c.DONORID                             and c.DONATIONID
 = t.SAMPLEID(+)                             and (? is null or c.DONATIONID = ?)
                             and c.DONATIONID = ce.serialid(+)
         order by c.BCDATE desc                           )
where rownum = 1
0.32 ::   **** All lines of test file executed, waiting for callback functions t
o finish.
65.005 ::  odbc.js:query() => Done.
[ { donorId: '1500057265',
    name: '欧柯祥',
    serialId: '9001211039266  ',
    conclusion: '1' } ]
65.055 ::  Total execution time for Query3 =  64.739 sec. **** <<==
65.056 ::  odbc.js:query() => Entry
65.056 ::  odbc.js:query() =>  select *                     from (
             select ''||d.DONORID as "donorId", rtrim(d.NAME) as "name", c.DONAT
IONID as "serialId",                                  nvl(ce.conclusion, case wh
en rtrim(t.FINALRESULT) is null and c.bcdate < to_date('2009-01-01', 'yyyy-mm-dd
') then 6 else nvl(rtrim(t.FINALRESULT),4) end) as "conclusion"
          from BIS.DONOR d,BIS.BLOODCOLLECTION c,BIS.TESTFINALRESULTLISTING t,bo
s.lab_conclusion_exclude ce                           where (d.citizenid in ('33
0107196906080910', '330107196906080910') or (d.CERTIFICATETYPE = '0' and d.certi
ficateid in ('330107196906080910','330107196906080910')))
      and d.DONORID = c.DONORID                             and c.DONATIONID = t
.SAMPLEID(+)                             and ('' is null or c.DONATIONID = '')
                           and c.DONATIONID = ce.serialid(+)
       order by c.BCDATE desc                           )                     wh
ere rownum = 1
66.578 ::  odbc.js:query() => Done.
[ { donorId: '1500057265',
    name: '欧柯祥',
    serialId: '9001211039266  ',
    conclusion: '1' } ]
66.579 ::  Total execution time for Query4 =  1.523 sec. **** <<==
node-ibm_db logs disabled.
```

**Comment by bimalkjha** [comment] 2017-03-14 12:11
@jay763190097 Since by just changing SQL, the new SQL is taking long time, I suspect the time is taken by server and not the client. Assuming you are on Mac or Linux, please run below commands and send the generated trace files to bimaljha@in.ibm.com:
```
$ cd ibm_db/clidriver
$ source ./db2profile
$ db2trc on -t -f 1.trc   # If it fails on Mac use - db2trc on -t -l 2m
$ node <testfile.js>
$db2trc off  # For Mac db2trc dump 1.trc; db2trc off
$db2trc flw -t 1.trc 1.flw
$db2trc fmt 1.trc 1.fmt
$db2trc fmt -cli 1.trc 1.cli
$db2trc fmt -c 1.trc 1.fmtc
```
Thanks.

**Comment by kevindashgit** [comment] 2017-03-20 20:55
My team is also seeing this behavior with the latest changes of the node-ibm module. 

I have a query that runs:
 -  ~3s static.
 - ~17s with a single integer parameter
 - ~8s with utilizing the `stmt.bind` method as opposed to `connection.query(query, params, callback)`

**Comment by kevindashgit** [comment] 2017-03-20 22:09
@bimalkjha I sent you a trace as well.

**Comment by bimalkjha** [comment] 2017-03-21 10:31
Thanks @kevindashgit for sharing the trace files. In 1.flw file, we can see below lines:

pid = 50346 tid = 123145338073088 node = -1
13212          0.107618000   SQLExecute entry
13226          0.107627000   | SQLExecute2 entry
13231          0.107638000   | | CLI_sqlPrepare entry
13281          0.107678000   | | CLI_sqlPrepare exit
13282          0.107681000   | | CLI_sqlOpen entry
13403          0.108310000   | | | csmOpen entry
13404          0.108315000   | | | | sqljrDrdaArOpen entry
13472          0.108725000   | | | | | sqljrRecv entry
13473          0.108725000   | | | | | | sqljcReceive entry
13474          0.108726000   | | | | | | | sqlccrecv entry
13475          0.108726000   | | | | | | | sqlccrecv data [probe 1]
13476          0.108726000   | | | | | | | sqlccrecv data [probe 2]
13477          0.108726000   | | | | | | | sqlccrecv data [probe 3]
13478          0.108726000   | | | | | | | sqlccrecv data [probe 4]
13479          0.108727000   | | | | | | | sqlccrecv data [probe 120]
13480          0.108727000   | | | | | | | sqlccrecv data [probe 130]
13481          0.108727000   | | | | | | | | sqlcctcprecv entry
13482          0.108727000   | | | | | | | | sqlcctcprecv data [probe 1]
13483          0.108728000   | | | | | | | | | tcprecv entry
13484          8.075288000   | | | | | | | | | tcprecv data [probe 2]
13485          8.075293000   | | | | | | | | | tcprecv exit
13486          8.075296000   | | | | | | | | sqlcctcprecv exit
13487          8.075296000   | | | | | | | sqlccrecv data [probe 5]
13488          8.075297000   | | | | | | | sqlccrecv exit
13489          8.075298000   | | | | | | sqljcReceive data [probe 100]
13490          8.075298000   | | | | | | sqljcReceive data [probe 1178]
13491          8.075299000   | | | | | | sqljcReceive exit
13492          8.075300000   | | | | | sqljrRecv exit

The first column is trace number and it is in sequence based on which function is called. Second column is the time elapsed since start of the thread. Look for below two entries:

13483          0.108728000   | | | | | | | | | tcprecv entry
13484          8.075288000   | | | | | | | | | tcprecv data [probe 2]

Here we can see the 8 second is consumed by tcprecv() function which is just waiting for 8 second to get response from server. So, actually it is the DB2 server that takes time to execute query and not the ibm_db client driver. Please contact your DBA or open PRM against server team to know why server takes so long to respond to client. You need to collect similar db2trace with "db2trc on" on server. Thanks.

**Comment by bimalkjha** [comment] 2017-04-10 14:23
Closing the issue as it seems a server issue. Thanks.

**Closed by bimalkjha** 2017-04-10 14:23 UTC

**Comment by kevindashgit** [comment] 2017-04-10 20:14
Just to poke this again (and to confirm your analysis @bimaljha) we were able to (intermittently) reproduce the issue one on system, and not on another (even using varying version of this module) - which made even more apparent that the issue was something on the server.
