### ISSUE TITLE
Where clause with accent characters (è, é, and ê) and multi-lingual characters return empty result

### ISSUE THREAD

**Issue by Hasneet** [ibmdb/node-ibm_db#615] opened 2020-03-09 12:33 UTC
I am working with ibm_db version 2.6.1, and am working with multi-lingual data with DB2 database service of IBM Cloud. The database consist of multi-lingual text within a certain column of a database table.
On querying the database table from SQL Workbench/J using a query which consist of a where clause that compares the given text against that column which consist of multi-lingual data everything works fine and I can retrieve the rows that match the where clause. 

However running the same query with ibm_db returns empty result set without any errors. Something is going wrong and I guess this has something to do with unicode characters and I am really confused how shall I proceed for this.

The query is of the sorts
SELECT COLUMN FROM TABLE WHERE COLUMN_NAME LIKE '%médias numériques%';

please help, how do I handle this issue?
I am running Node version 10.x

**Comment by bimalkjha** [comment] 2020-03-10 05:28
@Hasneet What is the name of OS on which you have installed ibm_db and facing this issue? Your issue looks duplicate of issue #614 . Please check it for solution. Thanks.

**Comment by Hasneet** [comment] 2020-03-10 07:31
@bimalkjha  This DB2 service is an instance I purchased from IBM Cloud DB2 Service, it is hosted on linux OS, I have been using ibm_db npm package version 2.6.1 and facing this issue. 
As I am seeing issue #614  it says using process.env.DB2CODEPAGE env variable and set it to 1208. 
where exactly do I need to pass this environment variable, can you brief me a little how should I configure it?

**Comment by bimalkjha** [comment] 2020-03-11 06:01
@Hasneet First of all I would suggest to use ibm_db@2.6.4. Version 2.6.1 has many bugs and your issue may be due to that.
Do you mean the ibm_db is part of the DB2 service on IBM Cloud that you are using or only DB2 Server is the service?
If you are facing issue with local installation of ibm_db, then DB2CODEPAGE need to be set in the system where ibm_db is installed. DB2CODEPAGE can be set as an environment variable. The update on issue 614 tells it to add process.env.DB2CODEPAGE=1208; code in your node.js application so that node application can also set the environment variable. Thanks.

**Comment by Hasneet** [comment] 2020-03-11 16:13
@bimalkjha I will try updating the package to 2.6.4 and let you know if that resolves this issue.

No this ibm_db is not a part of the DB2 Service, I just have the DB2 Server as an IBM Cloud service,
I am using ibm_db as an npm package into my node_modules to run through my node application to connect to the DB2 Server  as a service of IBM Cloud.

I tried setting the DB2CODEPAGE as an environment variable in my node application to 1208, however it did not work, and for the time being I have to maintain the ASCII encoded data within my DB2 Server to get the job done, however I want the Queries running through my node app using ibm_db package to just put the data passed to it as is, and not parse anything to ASCII encoding scheme.

**Comment by bimalkjha** [comment] 2020-03-19 06:08
@Hasneet Please share update if you have installed ibm_db@2.6.4. Let us know if issue is resolved. Thanks.

**Closed** 2020-03-24 17:45 UTC
