### ISSUE TITLE
use statement operate many datas lost some rows bug

### ISSUE THREAD

**Issue by JohnsenZhang0702** [ibmdb/node-ibm_db#406] opened 2018-06-04 07:24 UTC
version: 2.3.1
windows 7
use statement operate many datas lost some rows bug
for example
```var DBClass = require('ibm_db').Database;'
var connStr = "database=database;hostname=xx.xx.xx.xx;port=9527;uid=xxxx;pwd=aaaa;";
var sql = 'insert into tablename (col1,col2,col3,col4) values(?,?,?,?)';

var datas = [];
for(var i = 0 ; i < 1000 ; i++){
     datas.push(['a'+i,'b'+i,'c'+i,'d'+i]);
}

function conn(cb){
    var ibmdb = new DBClass();
    ibmdb.open(connStr, function(err,conn){
         if(err){
         }else{
             if(typeof cb === 'function'){
                  cb(ibmdb);
             }
         }
    })
}

var exec = function(){
     function useStatement(ibmdb){
           var len = datas.length;
           if(len == 0){
               ibmdb.query('select count(-1) as cnt from tablename',function(err,result){
                       ibmdb.close();
                       if(err){
                       }else{
                           console.dir(result);   // the cnt is not 1000, lost some rows; but use query insert is 1000 rows
                       }
               })
           }else{
                  var tmpData = datas[0];
                  ibmdb.prepare(sql,function(err,stmt){
                          if(err){
                              ibmdb.close();
                          }else{
                               stmt.execute(tmpData,function(err,result){
                                   if(err){
                                        ibmdb.close();
                                   }else{
                                        datas.shift();
                                        ibmdb.close();
                                        conn(connCB)
                                   }
                               })
                          }
                  })
           }
     }

     function connCB(ibmdb){
        useStatement(ibmdb);
     }

     conn(connCB);
}

exec()
```

**Comment by bimalkjha** [comment] 2018-06-04 09:33
@JohnsenZhang0702 Code in function conn(cb) should be as below:
```             if(typeof cb === 'function'){
                  cb(conn);
```
Thanks.

**Comment by bimalkjha** [comment] 2018-06-05 05:21
@JohnsenZhang0702 Update code to pass conn as argument of useStatement not the ibmdb. conn - means the object passed by ibmdb.open to the callback function not the conn function written by you. I would suggest to rename your conn function to something else to avoid confusion between conn object and conn function.
```
    ibmdb.open(connStr, function (err, conn) {
        if (err) {
        } else {
            useStatement(conn)
        }
    })
```
You should also define the function definition of useStatement as -  `function useStatement(conn)` and use conn variable to have more meaning full code.
Thanks.

**Comment by JohnsenZhang0702** [comment] 2018-06-05 05:56
sorry! the code is `useStatement(ibmdb)`

**Comment by bimalkjha** [comment] 2018-06-05 06:22
@JohnsenZhang0702 It happens due to logical error in coding. Before all stmt.execute() completes execution, ibmdb.query('select') statement get executed. So, whatever no of row was inserted it returns. 
You should run the select statement when stmt.execute has finished execution.
I have modified your `useStatement` function as in below code and it works fine. You can just copy and paste useStatement function from below example:
```
var DBClass = require('ibm_db').Database;
var ibmdb = new DBClass();
var connStr = "database=database;hostname=xx.xx.xx.xx;port=9527;uid=xxxx;pwd=aaaa";
var sql = 'insert into tablename (col1,col2,col3,col4) values(?,?,?,?)';
var createtable = true;

var datas = [];
for (var i = 0; i < 1000; i++) {
    datas.push(['a' + i, 'b' + i, 'c' + i, 'd' + i]);
}

function conn() {
    var ibmdb = new DBClass();
    ibmdb.open(connStr, function (err, conn) {
        if (err) {
           console.log(err);
        } else {
            if(createtable)
            {
              ibmdb.querySync("drop table tablename");
              ibmdb.querySync("create table tablename (col1 varchar(10), col2 varchar(10), col3 varchar(10), col4 varchar(10))");
              createtable = false;
            }
            useStatement(ibmdb)
        }
    })
}

function useStatement(ibmdb) {
    var tmpData = datas[0];
    ibmdb.prepare(sql, function (err, stmt) {
        if (err) {
            console.log(err);
            ibmdb.closeSync();
        } else {
            stmt.execute(tmpData, function (err, result) {
                if (err) {
                    console.log(err);
                    ibmdb.closeSync();
                } else {
                    datas.shift();
                    stmt.closeSync();
                    if(datas.length) {
                      ibmdb.closeSync();
                      conn();
                    }
                    else {
                      ibmdb.query('select count(-1) as cnt from tablename', function (err, result) {
                        if (err) {
                          console.log(err);
                        } else {
                          console.dir(result);
                        }
                        ibmdb.closeSync();
                      })
                    }
                }
            })
        }
    })
}

conn();
```
Closing the issue now. Thanks.

**Closed by bimalkjha** 2018-06-05 06:22 UTC

**Comment by JohnsenZhang0702** [comment] 2018-06-07 00:53
@bimalkjha I update the 'conn' name but the result is the same.
ibmdb is new DBClass's entity ,so conn is undefined。
If use `var ibmdb = require('ibmdb')` the conn is a Database;
If use ```
var DBClass = require('ibmdb').Database; 
var ibmdb = new DBClass();
ibmdb.open(connStr,function(err,connection){
    console.log(connection); // the connection is undefined;
})
```
Thanks

**Comment by bimalkjha** [comment] 2018-06-07 06:15
@JohnsenZhang0702 The issue was not with conn or DBClass usage. The issue is the if statement in your test program where ibmdb.query() is getting called before all stmt.execute() of else part finishes. Please read my previous update and run the test program that I shared. It is giving correct result. In my test program ibmdb.query() to get the count of inserted data is called in the callback function of stmt.execute(). You can use the same test program or modify yours accordingly. Thanks.
