### ISSUE TITLE
SQL_INVALID_HANDLE on x86_64 

### ISSUE THREAD

**Issue by grahamwhiteuk** [ibmdb/node-ibm_db#507] opened 2019-01-31 08:37 UTC
I'm running x86_64 RHEL 6 and DB2 version 10.5.  Regularly seeing:

```
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 12, index = 1
node: ../src/odbc.cpp:673: static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int): Assertion `ret != -2' failed.
```

I'm not sure if this is related to the only other bug I could find on this issue, #293.  But it looks like the -2 error code above relates to SQL_INVALID_HANDLE.  

A bit of research into the above error code and I am wondering whether ibm_db needs to include the `-DODBC64` flag when compiling the ODBC cli?  According to [an IBM support page](https://www-01.ibm.com/support/docview.wss?uid=swg21454064) it looks as though this flag is required.  Could you advise whether you've left the flag off deliberately?

Thanks!

**Comment by bimalkjha** [comment] 2019-02-02 06:04
@grahamwhiteuk `-DODBC64` is applicable only on `ntx64` when an application is linking with IBM ODBC Driver not IBM CLI Driver i.e. when `-lodbc` is used in command and not when `-ldb2` is used. 
On [this page](https://www-01.ibm.com/support/docview.wss?uid=swg21454064), we can see that under "Resolving the problem" section, with g++ command either `-lm -lodbc -DODBC64` or `-lm -ldb2` is used. The key is - linking with `odbc` or `db2`? ibm_db always link with `db2` and never with `odbc`, so we are not using `-DODBC64` flat in `ibm_db/binding.gyp` file for Windows.

Since, you are on RHEL, so ODBC64 is out of scope here. We have observed that such error occurs due to logical error in the application program where connection handle is freed while fetching data from the server is still in progress. It happens due to asynchronous nature of node.js that while data is still getting fetched, another code that closes connection and frees statement handle get called. To solve such issue, we need to look into application code and fix the programming logic to make sure any statement or connection get freed only when all results are retrieved from the server.
If your sample code which can repro the issue is smaller and can be shared, I would like to look into that to find root cause. Thanks.

**Comment by grahamwhiteuk** [comment] 2019-02-03 20:58
Thanks for the explanation @bimaljha, it makes a lot of sense.  From what you've said it sounds like we probably have some timing issues in our code so I'll get @jdp1g09 to check it through.  I'll talk to him about whether we can get you a copy of the code as well.  I'm not sure we'll want to share it publicly but may well be able to email or Slack it to you.  Thanks again for taking the time to respond, I'm very much looking forward to getting this sorted out.

**Comment by jdp1g09** [comment] 2019-02-04 10:42
I've trawled through our code - can't see anywhere we use the result after closing a connection. Our application trips up in the following function:
```
exports.query = function (query, params) {
  console.log('[DB QUERY] -> Query:')
  console.log(query)
  console.log('[DB QUERY] -> Params:')
  console.log(params)

  return new Promise (function(resolve, reject) {
    ibm_db.open(cn, function (err, conn) {
      if (err) {
        console.log('[DB QUERY] -> Error:');
        console.error(err);
        reject(err);
      }
      conn.query(query, params, function (err, rows) {
        if (err) {
          console.log('couldnt prepare')
          //could not prepare for some reason
          console.error(err);
          conn.close(function() {
            reject(err);
          })
        } else {
          conn.close(function(err) {
            console.log('close callback')
            if (err) {
              console.log('[DB QUERY] - CONN CLOSED ERROR')
              reject(err)
            } else {
              console.log('[DB QUERY] - CONN CLOSED')
              resolve(rows);
            }
          });
        }
        // console.log(rows);
      })
    });
  })
}
```
In the terminal I see the following:
```
[DB QUERY] -> Query:
<query removed for confidentiality>
[DB QUERY] -> Params:
[ '2019-01-01', '2019-02-04', '<email@emailaddress.com>' ]
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 12, index = 1
Assertion failed: (ret != SQL_INVALID_HANDLE), function GetColumnValue, file ../src/odbc.cpp, line 673.
Abort trap: 6
```

**Comment by jdp1g09** [comment] 2019-02-05 10:02
we've also since added another console.log in the callback of the `open` to confirm it does connect/open okay - which it consistently does. It's the `conn.query` call where it trips.

**Comment by grahamwhiteuk** [comment] 2019-02-05 10:04
Thanks, @jdp1g09.

@bimalkjha is the above information enough for you to debug or make some suggestions for us to try out?

**Comment by bimalkjha** [comment] 2019-02-06 08:18
@jdp1g09 @grahamwhiteuk I would suggest to move `resolve(rows);` before calling `conn.close()` in `else` block of `conn.query` API like below and test for any difference in behavior:
```
        } else {
          resolve(rows);
          console.log(rows);
          conn.close(function(err) {
```
Thanks.

**Comment by jdp1g09** [comment] 2019-02-06 10:05
@bimalkjha unfortuanely, the code doesn't even get into the callback of the `.query` function:

I added a new `console.log()` in the callback:
```
exports.query = function (query, params) {
  console.log('[DB QUERY] -> Query:')
  console.log(query)
  console.log('[DB QUERY] -> Params:')
  console.log(params)

  return new Promise (function(resolve, reject) {
    ibm_db.open(cn, function (err, conn) {
      if (err) {
        console.log('[DB QUERY] -> Error:');
        console.error(err);
        reject(err);
      }
      console.log('[DB QUERY] - CONN OPENED')
      conn.query(query, params, function (err, rows) {
        if (err) {
          console.log('couldnt prepare')
          //could not prepare for some reason
          console.error(err);
          conn.close(function() {
            reject(err);
          })
        } else {
          console.log('[DB QUERY] - NO ERROR')
          conn.close(function(err) {
            console.log('close callback')
            if (err) {
              console.log('[DB QUERY] - CONN CLOSED ERROR')
              reject(err)
            } else {
              console.log('[DB QUERY] - CONN CLOSED')
              resolve(rows);
            }
          });
        }
      })
    });
  })
}
```
The `console.log('[DB QUERY] - NO ERROR')` is never shown in the logs (see below) so it is the `conn.query` function that trips.

```
<query removed for confidentiality>
[DB QUERY] -> Params:
[ '2019-02-04', '2019-02-10', '<email@emailaddress.com>' ]
[DB QUERY] - CONN OPENED
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 91, index = 2
node: ../src/odbc.cpp:673: static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int): Assertion `ret != -2' failed.
```

It's also worth mentioning, this is not consistent behaviour, sometimes we can go an hour without seeing the problem (performing the same tasks) - sometimes 2 seconds. It's also not always the same query either and there are queries both with and without parameters that make it fall over.

**Comment by jdp1g09** [comment] 2019-02-06 10:25
Interestingly, without any code changes, noticed that this same query just tripped but this time printed out a different error, struggling to open the connection. Realised we don't have the second piece wrapped in an `else` (if unable to connect) - so going to change that now

```
[DB QUERY] -> Query:
<query removed for confidentiality>
[DB QUERY] -> Params:
[ '2019-01-21', '2019-01-27', '<email@emailaddress.com>' ]
[DB QUERY] -> Error:
{ errors: [] }
[DB QUERY] - CONN OPENED
couldnt prepare
{ message: 'Connection not open.',
  sqlstate: '08001',
  sqlcode: -30081 }
{ errors: [] }
```

Because the error was handled in the error callback, we handled it fine back to our application and since then the calls have worked fine.

**Comment by jdp1g09** [comment] 2019-02-06 11:05
updated code (wrapped in else of error) that still causes the same trip in the same place:

```
return new Promise (function(resolve, reject) {
    ibm_db.open(cn, function (err, conn) {
      if (err) {
        console.log('[DB QUERY] -> ERROR OPENING CONNECTON:');
        console.error(err);
        reject(err);
      } else {
        console.log('[DB QUERY] - CONN OPENED')
        conn.query(query, params, function (err, rows) {
          if (err) {
            console.log('[DB QUERY] -> ERROR QUERYING:')
            //could not prepare for some reason
            console.error(err);
            conn.close(function() {
              reject(err);
            })
          } else {
            console.log('[DB QUERY] - NO ERROR')
            conn.close(function(err) {
              console.log('close callback')
              if (err) {
                console.log('[DB QUERY] - CONN CLOSED ERROR')
                reject(err)
              } else {
                console.log('[DB QUERY] - CONN CLOSED')
                resolve(rows);
                console.log('[DB QUERY] - AFTER PROMISE')
              }
            });
          }
          // console.log(rows);
        })
      }
    });
  })
```

```
<query removed for confidentiality>
[DB QUERY] -> Params:
[ '2019-02-04', '2019-02-10', '<email@emailaddress.com>' ]
[DB QUERY] - CONN OPENED
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 91, index = 2
node: ../src/odbc.cpp:673: static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int): Assertion `ret != -2' failed.```

**Comment by bimalkjha** [comment] 2019-02-08 06:54
@jdp1g09 Please issue a command ` rm -rf build; npm install -debug;` under ibm_db to enable debug logs in the code and then run the repro script. The debug logs will get printed on stdout so you need to redirect the test script output to a file and share the output file as attachment here or mail to bjha@rocketsoftware.com.
You can revert the debug log of ibm_db by using `rm -rf build; npm install` command. Thanks.

**Comment by grahamwhiteuk** [comment] 2019-04-04 13:53
@bimaljha sorry it has taken so long but we're still struggling with the stability of the library so I have sent you some debug output via email.  Please let us know if you need any more info - many thanks!

**Comment by bimalkjha** [comment] 2019-04-04 16:18
@grahamwhiteuk Thanks for sharing the debug logs. It seems, the problem is with your (conn.prepare, stmt.execute, result.fetch) code where result, stmt and conn are not getting closed by the code. As a side effect, conn.query() get impacted. There is no issue with your conn.query() call. Please look into the part of code which uses prepare and execute logic.
```
[DB PREPARE] -> Query:
DELETE FROM ETS.TIMER_RECORD WHERE LOWER(USER_EMAIL) = LOWER(?) AND ENTRY_DATE = ? AND PROJECT_CODE = ? AND RECORD_TYPE = 'T'
[DB EXECUTE] -> Params:
[ 'GWHITE@uk.ibm.com', '2019-04-05', 'IBM0003' ]
```
The code which has above logs has the issue. Please verify. Thanks.

**Comment by grahamwhiteuk** [comment] 2019-04-04 17:00
Thanks very much. We'll take a look next week and get back with our results.

**Comment by jdp1g09** [comment] 2019-04-12 14:46
ISSUE SOLVED:

Needed to `.closeSync()` each instance of a `result` and `stmt` in our common library that we'd created. This had nothing to do with the `.query()` call, but inf act the call directly preceding this each time.

Our common library contains a `prepare` and `execute` function, which now look like this:

```javascript
exports.prepare = function (conn, query) {
  return new Promise (function(resolve, reject) {
    conn.prepare(query, function (err, statement) {
      if (err) {
        if (statement) {
          statement.closeSync();
        }
        conn.closeSync();
      } else {
        resolve(statement);
      }
    })
  })
}

exports.execute = function (stmt, params, fetchOptions) {
  return new Promise (function(resolve, reject) {
    stmt.execute(params, function (err, result) {
      if (err) {
        stmt.closeSync();
        if (result) {
          result.closeSync();
        }
        reject(err);
      } else {
        fetchOptions = fetchOptions ? fetchOptions: {}
        result.fetchAll(fetchOptions, function (err, rows) {
          if (err) {
            reject(err)
          } else {
            resolve(rows)
          }
          stmt.closeSync();
          result.closeSync();
        })
      }
    })
  })
}
```

noting the `stmt.closeSync();` and `result.closeSync();`. The issue was caused by Javascript's garbage collection was taking control given that we never closed these and caused the error originally raised. 

Given this, the issue has now been resolved, thank you so much for your help @bimalkjha

**Closed** 2019-04-12 15:46 UTC
