### ISSUE TITLE
Driver install fails

### ISSUE THREAD

**Issue by lohart13** [ibmdb/node-ibm_db#865] opened 2022-06-20 05:11 UTC
The installation of the driver fails as the https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli url is returning a 500 error when trying to download file.

Any otherways to get around this error?

**Comment by DaisyYangl** [comment] 2022-06-20 06:11
Hello, there's no 'linuxx64_odbc_cli.tar.gz' file in https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/.   So download this file returns 500 error.
Could anybody give any suggestion about this error?  And is there a slack channel for supporting questions?
Thanks....

**Comment by ibmbendev** [comment] 2022-06-20 06:56
same here. please check https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip 500 error.

**Comment by shikharani16** [comment] 2022-06-20 09:49
same here
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz ...

Error: Request failed with status code 500

**Comment by hizir-bc** [comment] 2022-06-20 09:56
Same here, verified with MacOS and Windows x64, the file download fails due to the 500 internal server error

**Comment by dragomir-enachi-ibm** [comment] 2022-06-20 12:59
I had to add to /etc/resolv.conf
129.35.224.112 public.dhe.ibm.com
to make it work again.

with other IPs it's resolving to I get 500 Internal Server Error when trying to download stuff.

**Comment by bimalkjha** [comment] 2022-06-20 16:00
Issue was due to migration of the hosting service to new env yesterday by IBM. The issue is fixed now. Thanks.

**Closed by bimalkjha** 2022-06-20 16:00 UTC

**Comment by shikharani16** [comment] 2022-07-04 12:11
I see this issue again today.
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz ...

Error: Request failed with status code 500
