### ISSUE TITLE
ibm_db fails to install in bluemix cf app

### ISSUE THREAD

**Issue by subinpc** [ibmdb/node-ibm_db#392] opened 2018-04-27 06:51 UTC
When we deploy our nodejs app in bluemix, it fails because ibm_db package fails to install. This was working fine a day back.

I'm including relevant log entries - 
```
2018-04-27T06:13:03.73+0000 [STG/0] OUT -----> Installing binaries
   2018-04-27T06:13:03.75+0000 [STG/0] OUT        engines.node (package.json):  8.x
   2018-04-27T06:13:03.75+0000 [STG/0] OUT        engines.npm (package.json):   unspecified (use default)
   2018-04-27T06:13:03.75+0000 [STG/0] OUT
   2018-04-27T06:13:03.75+0000 [STG/0] OUT        Resolving node version 8.x via 'node-version-resolver'
   2018-04-27T06:13:04.28+0000 [STG/0] OUT        Installing IBM SDK for Node.js (8.9.4) from cache
   2018-04-27T06:13:07.76+0000 [STG/0] OUT        Using default npm version: 5.6.0
   2018-04-27T06:13:07.76+0000 [STG/0] OUT -----> Restoring cache
   2018-04-27T06:13:08.16+0000 [STG/0] OUT        Skipping cache restore (new runtime signature)
   2018-04-27T06:13:08.16+0000 [STG/0] OUT -----> Checking and configuring service extensions before installing dependencies
   2018-04-27T06:13:08.30+0000 [STG/0] OUT -----> Building dependencies
   2018-04-27T06:13:08.30+0000 [STG/0] OUT        Installing node modules (package.json)
   2018-04-27T06:13:29.89+0000 [STG/0] OUT        > node-gyp rebuild
   2018-04-27T06:13:29.89+0000 [STG/0] OUT
   2018-04-27T06:13:29.89+0000 [STG/0] OUT
   2018-04-27T06:13:29.89+0000 [STG/0] OUT        > ursa@0.9.4 install /tmp/app/node_modules/ursa
   2018-04-27T06:13:31.77+0000 [STG/0] OUT        make: Entering directory `/tmp/app/node_modules/ursa/build'
   2018-04-27T06:13:31.77+0000 [STG/0] OUT        CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
   2018-04-27T06:13:34.66+0000 [STG/0] OUT        SOLINK_MODULE(target) Release/obj.target/ursaNative.node
   2018-04-27T06:13:34.74+0000 [STG/0] OUT        COPY Release/ursaNative.node
   2018-04-27T06:13:34.75+0000 [STG/0] OUT        make: Leaving directory `/tmp/app/node_modules/ursa/build'
   2018-04-27T06:13:34.78+0000 [STG/0] OUT
   2018-04-27T06:13:34.78+0000 [STG/0] OUT        > ibm_db@2.3.1 install /tmp/app/node_modules/ibm_db
   2018-04-27T06:13:34.79+0000 [STG/0] OUT        > node installer/driverInstall.js
   2018-04-27T06:13:34.79+0000 [STG/0] OUT
 2018-04-27T06:13:35.26+0000 [STG/0] OUT        Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...
   2018-04-27T06:13:35.26+0000 [STG/0] OUT
   2018-04-27T06:14:04.87+0000 [STG/0] OUT
   2018-04-27T06:14:04.87+0000 [STG/0] OUT 100.00% | 536 bytes downloaded out of 536 bytes.{ Error: incorrect header check
   2018-04-27T06:14:04.87+0000 [STG/0] OUT        at Gunzip.zlibOnError (zlib.js:153:15) errno: -3, code: 'Z_DATA_ERROR' }
   2018-04-27T06:14:05.97+0000 [STG/0] OUT        npm ERR! code ELIFECYCLE
   2018-04-27T06:14:05.97+0000 [STG/0] OUT        npm ERR! errno 1
   2018-04-27T06:14:05.97+0000 [STG/0] OUT        npm ERR! ibm_db@2.3.1 install: `node installer/driverInstall.js`
   2018-04-27T06:14:05.98+0000 [STG/0] OUT        npm ERR! Exit status 1
   2018-04-27T06:14:05.98+0000 [STG/0] OUT        npm ERR!
   2018-04-27T06:14:05.98+0000 [STG/0] OUT        npm ERR! Failed at the ibm_db@2.3.1 install script.
   2018-04-27T06:14:05.98+0000 [STG/0] OUT        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
   2018-04-27T06:14:06.17+0000 [STG/0] OUT        npm ERR! A complete log of this run can be found in:
   2018-04-27T06:14:06.17+0000 [STG/0] OUT
   2018-04-27T06:14:06.17+0000 [STG/0] OUT        npm ERR!     /home/vcap/.npm/_logs/2018-04-27T06_14_06_034Z-debug.log
   2018-04-27T06:14:06.19+0000 [STG/0] OUT -----> Build failed
   2018-04-27T06:14:06.21+0000 [STG/0] OUT
   2018-04-27T06:14:06.21+0000 [STG/0] OUT
   2018-04-27T06:14:06.21+0000 [STG/0] ERR Failed to compile droplet: Failed to compile droplet: exit status 1
   2018-04-27T06:14:06.22+0000 [STG/0] OUT Exit status 223
   2018-04-27T06:14:06.23+0000 [STG/0] ERR Staging failed: STG: Exited with status 223
   2018-04-27T06:14:06.24+0000 [STG/0] OUT Stopping instance b4990f45-3860-4e6a-b746-d53e161dee09
   2018-04-27T06:14:06.24+0000 [STG/0] OUT Destroying container
   2018-04-27T06:14:07.04+0000 [STG/0] OUT Successfully destroyed container
```

I've tried multiple versions of the package - 2.3.1, 2.3.0 and 2.2.1.
I've also tried using an older version of cf sdk-for-nodejs buildpack, but I'm still encountering this error.

I've seen #389 and #390, but created a separate issue because the manner in which it's failing seems to be different from theirs.

**Comment by bimalkjha** [comment] 2018-04-27 08:34
@subinpc ibm_db installation fails due to below error:

2018-04-27T06:13:35.26+0000 [STG/0] OUT        Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...
   2018-04-27T06:13:35.26+0000 [STG/0] OUT
   2018-04-27T06:14:04.87+0000 [STG/0] OUT
   2018-04-27T06:14:04.87+0000 [STG/0] OUT 100.00% | 536 bytes downloaded out of 536 bytes.{ Error: incorrect header check
   2018-04-27T06:14:04.87+0000 [STG/0] OUT        at Gunzip.zlibOnError (zlib.js:153:15) errno: -3, code: 'Z_DATA_ERROR' }

It seems bluemix application is unable to download the file https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz. it is showing `536 bytes downloaded out of 536 bytes`, but size of this tar.gz file is of 17.8MB and it should show `18703240 bytes downloaded out of 18703240 bytes.`

Sometimes the  https://public.dhe.ibm.com site goes down or encountered some issue. If the problem is with older version of ibm_db too, then some setting in the bluemix firewall might have changed which is not allowing to download the file from  https://public.dhe.ibm.com. 

Please investigate why bluemix app is unable to downlaod https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz file? Try to run below command after login to the bluemix server:
```
cd ~
wget https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
tar xzf linuxx64_odbc_cli.tar.gz
export IBM_DB_HOME=$HOME/clidriver
npm install ibm_db
```
Thanks.

**Comment by subinpc** [comment] 2018-04-27 09:29
Thanks @bimalkjha. I just checked again now, and it seems like odbc driver is getting downloaded properly inside cf container.

**Comment by bimalkjha** [comment] 2018-04-27 09:37
So, are you able to push your app successfully now? If now, please share the latest full error output. thanks.

**Comment by subinpc** [comment] 2018-04-27 09:58
Yes, I'm able to push my app successfully now.

**Comment by bimalkjha** [comment] 2018-04-27 12:31
@subinpc Thanks for the update. Closing the issue now.

**Closed by bimalkjha** 2018-04-27 12:31 UTC
