### ISSUE TITLE
ibm_db query() returns no error when encountering connection error

### ISSUE THREAD

**Issue by fangzhuchen** [ibmdb/node-ibm_db#683] opened 2020-08-24 08:51 UTC
Using query() method, we normally receive error code and message if SQL went wrong. 
But it seems when following error occurs, there is no error code and result is empty. So that application might think the result was SQL100 and take wrong action.

　sqlcode:-1
　state:S1000
　message:CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000

Is there a way to differentiate this error from a SQL=100 (not found) code?

**Comment by bimalkjha** [comment] 2020-08-26 18:47
@fangzhuchen You can check for sqlca.sqlcode value to distinguish from 100 code. Thanks.

**Comment by fangzhuchen** [comment] 2020-08-27 00:10
@bimalkjha Thanks!!
Could you please share some sample code how to get sqlca.sqlcode from the result object after calling .query(sqlQuery [, bindingParameters], callback)?
Do we have to use .queryResult(sqlQuery [, bindingParameters], callback) to do that?

**Comment by bimalkjha** [comment] 2020-08-27 08:46
@fangzhuchen `query()` API also returns `sqlca` as last argument in callback function. You can see example in [API Documentation here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-3-querysqlquery--bindingparameters-callback). 
You can grep for `sqlca` in `ibm_db/test` directory to see examples. test-basic-test.js & test-open-connectTimeout.js shows sqlca & sqlca.sqlcode. Thanks.

**Comment by fangzhuchen** [comment] 2020-08-31 01:03
@bimalkjha  Thanks.
I tried to use sqlca. However it seems when the error code is "-1" (message:CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000), the return code of sqlca was set as "0", so we cannot tell if it is a normal case or exception case.
Any good idea to resolve this?

**Comment by bimalkjha** [comment] 2020-08-31 08:58
@fangzhuchen Good to share some small test program to reproduce the problem quickly. Otherwise, I'll try to reproduce and then update you about solution. Thanks.

**Comment by fangzhuchen** [comment] 2020-09-23 03:11
@bimalkjha 
It is very difficult to reproduce it 100%.
I found it is tend to happen easily when the result data size is bigger (and include BLOB data). Is there anything to configure about the result size?

**Comment by bimalkjha** [comment] 2021-08-07 21:01
@fangzhuchen I am unable to reproduce the scenario where query() returns CLI0600E error but sqlca.sqlcode is 0. This error is reproducible if we add `conn.closeSync()` before line number 57 in test-basic-test.js, but we can figure it out using error.sqlcode which is -1. In your program you can add check for error.sqlcode to identify this error.
This error comes, if connection is closed before query() is able to fetch all data from the server. This happens mostly due to logical error in the code. I would suggest to install the latest version of ibm_db and check. It might be fixed. Otherwise work around it by checking error.sqlcode as mentioned. Closing the issue now. Thanks.

**Closed by bimalkjha** 2021-08-07 21:01 UTC
