### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by nsanthoshkumar** [ibmdb/node-ibm_db#1006] opened 2024-10-10 00:56 UTC
# Please provide below information while opening an issue to understand your problem

- Operating System Name where ibm_db is installed: Linux Docker Container
- Target Db2 Server Version or output of `db2level` command from Db2 database system: DB2 Warehouse

## Please provide below problem specific info:
=========================================

### For Installation related issue
I am trying to deploy a node app  using docker with the following information in the Dockerfile. The docker build used to work previously for versions 18 and below and I updated the following node versions to 20 and changed the python to 3 instead of 2.7
and it is currently hanging before downloading the driver file. Any help is really appreciated? Thank you.

```Dockerfile
FROM registry.access.redhat.com/ubi8/nodejs-20

USER 0

WORKDIR /usr/src/app

COPY . /usr/src/app



# Install prerequisites for ibm_db
RUN yum install -y gcc python3 make gcc gcc-c++ openssl-devel bzip2-devel
RUN npm install

RUN rm -rf /usr/src/app/node_modules/ibm_db/installer/clidriver
RUN ls && cd node_modules/ibm_db && npm install --unsafe-perm 
RUN npm install 

```

I am using the following command to build the docker image

```sh
docker build --platform linux/amd64 -t <app_name:version>  .
```

<img width="867" alt="image" src="https://github.com/user-attachments/assets/83a24b64-cf36-4ff8-899b-634a5cb4ebf4">

**Comment by nsanthoshkumar** [comment] 2024-10-14 18:31
@bimaljha Can you please let me know if you have any insight or any help is really appreciated?

**Comment by bimalkjha** [comment] 2024-10-15 06:22
@nsanthoshkumar Problem that you see is: `hanging before downloading the driver file while installation`.
Installation messages on screen for successful installation looks like below:
```
> ibm_db@3.2.4 install
> node installer/driverInstall.js

platform = linux, arch = x64, node.js version = v20.16.0
make version =GNU Make 4.2.1

****************************************
....
```
We can see that before downloading clidriver, driverInstall.js file is trying to find the version of make by executing `make -v` command. I think it is hanging in printMakeVersion() function of https://github.com/ibmdb/node-ibm_db/blob/master/installer/driverInstall.js#L819 while calling `execSync` API of `child_process` package. i.e. hanging before trying to download clidriver.
To reproduce the issue, you can paste the code of printMakeVersion() function in a test file run it. Share the result.
Run `make -v` manually and see if it is working or not. These tests should help us to move forward towards resolution. Thanks.

**Comment by nsanthoshkumar** [comment] 2024-10-15 22:30
Thank @bimalkjha  for the reply,  Below are the results of the testing
On the local machine running make -v
<img width="636" alt="image" src="https://github.com/user-attachments/assets/8c080f53-8754-4ac6-a586-a96d376571df">

Ran from the node.js test code below

```js 

var os = require('os');
var silentInstallation = false;

function printMakeVersion() {
    console.log("I am triggered");
    var platform = os.platform();
  if (platform != 'win32') {
    try {
      var makeVersion = execSync('make -v').toString();
      makeVersion = makeVersion.split('\n')[0];
      if( downloadProgress == 0 ) printMsg("make version =" + makeVersion);
    } catch (e) {
      printMsg("Unable to find 'make' in PATH. Installation may fail!");
    }
  }
}

function printMsg(msg) {
    if (!silentInstallation) {
        console.log(msg);
    }
}
printMakeVersion();
```


<img width="461" alt="image" src="https://github.com/user-attachments/assets/c3593315-476d-4b50-a205-0c7b0a120607">

I checked the pafth and added the following  line to the path `/usr/local/opt/make/libexec/gnubin` and still the same error.


I edited the docker file and I tried running the make version on the docker. It also gets the same error as above.

**Comment by bimalkjha** [comment] 2024-10-16 14:36
@nsanthoshkumar Your issue looks similar to https://stackoverflow.com/questions/43763494/make-command-not-found-in-docker-container
Add `build-essential` too in your `yum install` command and try. Your dockerfile should have below code:
```
# Install prerequisites for ibm_db
RUN yum update
RUN yum install -y build-essential gcc python3 make gcc gcc-c++ openssl-devel bzip2-devel
RUN make -v
RUN npm install
```
Thanks.

**Comment by nsanthoshkumar** [comment] 2024-10-17 21:30
@bimalkjha  I don't think build-essential exists on the Redhat image. Also, the issue is happening only in the docker image creation process and the process is hanging at execSync. I changed it to print node version. It also hangs there.

**Comment by bimalkjha** [comment] 2024-10-21 08:04
@nsanthoshkumar Update your dockerfile to run a command `node -e "console.log(require('child_process').execSync('node -v').toString())"` after yum install. If it hangs or fails, ibm_db installation too will fail. It it works for you, please share result here.
Thanks.

**Comment by bimalkjha** [comment] 2024-11-02 12:53
@nsanthoshkumar Usually, we can find make as /usr/bin/make in the systems post installation. Since, it is at different location, node is unable to find it. you need to add /usr/local/opt/make/libexec/gnubin in PATH in docker script.
You mentioned that `make -v` is working locally. Since, you are using dockerfile, so any command working locally is irrelevant as it need to work inside docker.
I checked my docker linux image and can see /usr/bin/make file. Not sure why it is installed at different location for you.
I would suggest to update your dockerfile as below and then run:
```
# Install prerequisites for ibm_db
RUN yum update
RUN yum install -y gcc python3 make gcc gcc-c++ openssl-devel bzip2-devel
RUN make -v
RUN export PATH= /usr/local/opt/make/libexec/gnubin:$PATH
RUN which make
RUN make -v
RUN npm install
```
Please let us know if command `node -e "console.log(require('child_process').execSync('node -v').toString())"` is working for you or not. Thanks.

**Comment by nsanthoshkumar** [comment] 2024-11-12 21:11
@bimalkjha  Thanks for the update and sorry for the delay
I tried the following  and it did not work
https://github.com/ibmdb/node-ibm_db/issues/1006#issuecomment-2425917870 

I will try the following https://github.com/ibmdb/node-ibm_db/issues/1006#issuecomment-2452981361 and update you.

**Comment by nsanthoshkumar** [comment] 2024-11-26 19:34
@bimalkjha  I tried and it is still failing. For now, I got the issue resolved by using linux server, The issue is with Mac M1 processor. I will try to see once the ODBC bindings are released for Mac M1. Below is  what we found https://ibm-data-and-ai.ideas.ibm.com/ideas/DB2CON-I-92.

**Comment by bimalkjha** [comment] 2024-12-01 17:04
@nsanthoshkumar ibm_db@3.3.0 is released with support for Mac M1 Chip system. You can try installing latest version of ibm_db and verify. Thanks.

**Comment by bimalkjha** [comment] 2024-12-11 08:28
@nsanthoshkumar Closing the issue now as required support is already released. You can update here or open new issue if you face any problem using latest version of ibm_db driver. Thanks.

**Closed by bimalkjha** 2024-12-11 08:28 UTC
